/* Serial authenticated Arena race requests and recoverable central-wallet settlement. */
(function(){
'use strict';let saving=0,payment=Promise.resolve();
const user=()=>typeof firebase!=='undefined'&&firebase.auth().currentUser;
async function api(data){const u=user();if(!u)throw Error('login');const token=await u.getIdToken(),c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch('https://asia-southeast1-english-pet-game.cloudfunctions.net/arenaRaceV1',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({data}),signal:c.signal}),b=await r.json();if(!r.ok||b.error)throw Error(b.error?.message||'network');return b.result??b.data;}finally{clearTimeout(timer);}}
function mergeCredit(r){if(!r.save?.data)return 0;const remote=JSON.parse(r.save.data),receipts=state.arenaRaceReceipts||{};let amount=0;for(const [key,total]of Object.entries(remote.arenaRaceReceipts||{}))if(Number.isSafeInteger(total)&&total>(receipts[key]||0)){amount+=total-(receipts[key]||0);receipts[key]=total;}if(amount)addCoins(amount);state.arenaRaceReceipts=receipts;saveState();return amount;}
function settle(code,credit){const uid=user()?.uid;if(!uid)return Promise.resolve();payment=payment.catch(()=>{}).then(async function settlePending(){if(user()?.uid!==uid)return;if(typeof authPushSaveAwait==='function')await authPushSaveAwait(true);saving++;try{const r=await api({action:'settle',code});if(user()?.uid===uid){const n=mergeCredit(r);if(credit)credit(n);}return r;}finally{saving--;}});return payment;}
function create(hooks){let code='',closed=false,busy=false,snapshot=null,nextAt=0,generation=0,sessionBase=null,paid=0,lastError=-10000,retryAt=0,actionAt=-1000;
function error(){nextAt=retryAt=performance.now()+3000;if(!closed&&performance.now()-lastError>5000){lastError=performance.now();hooks.status('เชื่อมต่อการแข่งขันไม่ได้ · กำลังลองใหม่');}}
async function request(action,extra={}){if(closed||busy||!code||performance.now()<retryAt||(action!=='sync'&&action!=='drop'&&performance.now()-actionAt<250))return false;if(action!=='sync')actionAt=performance.now();busy=true;const g=generation,c=code;try{const r=await api({action,code:c,...extra});if(closed||g!==generation)return false;if(!snapshot||r.version>=snapshot.version){const previous=snapshot;snapshot=r;if(sessionBase===null)sessionBase=r.self.earned;hooks.snapshot(r,previous,Math.max(0,r.self.earned-sessionBase));if(r.self.earned>paid){paid=r.self.earned;settle(c,n=>{if(!closed)hooks.credit(n);}).catch(()=>{paid=0;error();});}}nextAt=performance.now()+1500;return true;}catch(e){if(g===generation)error();return false;}finally{busy=false;}}
const u=user(),key=u?'vw.arena.races.'+u.uid:'';let old=[];try{old=JSON.parse(localStorage.getItem(key)||'[]');}catch{}for(const c of old)if(/^r(?:2[1-9]|3[0-5])$/.test(c))settle(c,n=>{if(!closed)hooks.credit(n);}).catch(error);
return{get snapshot(){return snapshot},get busy(){return busy},get ready(){return !!snapshot&&!closed},tick(room){const next=room?.joined&&room.online?'r'+room.room:'';if(next!==code){code=next;generation++;snapshot=null;sessionBase=null;paid=0;nextAt=0;hooks.reset();if(code&&key&&!old.includes(code)){old.push(code);localStorage.setItem(key,JSON.stringify(old));}}if(code&&!busy&&performance.now()>=nextAt)request('sync');},pickup:(item,revision)=>request('pickup',{item,revision}),bank:()=>snapshot?request('bank',{revision:snapshot.self.revision,round:snapshot.word.round}):false,drop:()=>snapshot?request('drop',{revision:snapshot.self.revision}):false,hit:(owner,revision)=>request('hit',{owner,revision}),raid:(owner,revision)=>request('raid',{owner,revision}),sync:()=>request('sync'),close(){closed=true;generation++;if(code)settle(code).catch(()=>{});}};}
window.ArenaRace={create,get saving(){return saving>0},mergeCredit};
})();
