/* Vocab World: Frontline 1944 — ADMIN PREVIEW ONLY
 * Wide orthographic 2.5D battlefield prototype. New isolated runtime; no global engine rewrite.
 */
(function(){
'use strict';
const CFG={
  letterCoins:1,wordBonus:50,mapW:320,mapH:230,viewW:64,dpr:1.5,
  playerSpeed:17,playerHP:100,shotSpeed:55,shotLife:1.35,shotDamage:12,
  enemyCap:10,projectileCap:48,fxCap:72,fortressSites:6,
  fortressTrigger:35,fortressCoreHP:95,bossBaseHP:145,defendersBase:4
};
const G={running:false,starting:false,root:null,renderer:null,scene:null,camera:null,clock:null,raf:0,last:0,
  layers:{},player:null,fortress:null,enemies:[],shots:[],enemyShots:[],fx:[],smoke:[],keys:new Set(),listeners:[],
  joy:{x:0,y:0,id:null},firing:false,fireAt:0,fortressSerial:0,word:null,pos:0,wordRunId:'',wordsDone:0,
  objectiveSite:-1,sites:[],claimed:new Set(),lowFx:false,audit:null,toastTimer:0,routeTried:false,routeDenied:false};
const $=s=>G.root&&G.root.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), dist2=(a,b)=>{const x=a.x-b.x,z=a.z-b.z;return x*x+z*z;};
function listen(t,n,f,o){t.addEventListener(n,f,o);G.listeners.push(()=>t.removeEventListener(n,f,o));}
function adminAllowed(){
  // Home V2's current authoritative world gate uses the bare isAdmin() identifier.
  // A top-level lexical binding may not exist on window, so resolve it directly first.
  try{if(typeof isAdmin === 'function' && isAdmin() === true)return true;}catch(e){}
  try{if(typeof canAccessAdmin === 'function' && canAccessAdmin() === true)return true;}catch(e){}
  const fns=['isAdmin','canAccessAdmin'];
  for(const n of fns){try{const v=window[n];if(typeof v==='function'&&v()===true)return true;if(v===true)return true;}catch(e){}}
  try{if(window.AdminGate&&typeof window.AdminGate.allowed==='function'&&window.AdminGate.allowed()===true)return true;}catch(e){}
  return false; // fail closed: never infer admin from email, query string or editable profile data.
}
function lockNotice(){if(typeof toast==='function')toast('🔒 Vocab Frontline 1944 เป็น ADMIN PREVIEW เท่านั้น');}
function syncAdminEntry(){
  const ok=adminAllowed();
  for(const id of ['btn-rail-frontline1944','btn-frontline1944-admin-launcher']){
    const b=document.getElementById(id);if(!b)continue;b.hidden=!ok;b.setAttribute('aria-hidden',ok?'false':'true');
    if(ok&&!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',()=>open());}
  }
}
function normalizeWord(x){let en='',th='';if(Array.isArray(x)){en=x[0];th=x[1]||'';}else if(x&&typeof x==='object'){en=x.en||x.word||x.eng||x.english||'';th=x.th||x.meaning||x.thai||'';}en=String(en||'').trim().toUpperCase().replace(/[^A-Z]/g,'');return en.length>=2&&en.length<=10?{en,th:String(th||'')}:null;}
function vocabPool(){
  let raw=[];
  try{if(typeof f1VocabForStudent==='function')raw=f1VocabForStudent()||[];}catch(e){}
  if(!raw.length)try{if(typeof vocabForStudent==='function')raw=vocabForStudent()||[];}catch(e){}
  const seen=new Set(),out=[];for(const x of raw){const w=normalizeWord(x);if(w&&!seen.has(w.en)){seen.add(w.en);out.push(w);}}
  return out;
}
function auditVocabulary(){
  const grades=['ป.1','ป.2','ป.3','ป.4','ป.5','ป.6'],out={},student=window.state&&state.student,old=student&&student.grade;
  if(!student)return {source:typeof f1VocabForStudent==='function'?'f1VocabForStudent':typeof vocabForStudent==='function'?'vocabForStudent':'missing',counts:out};
  try{for(const grade of grades){student.grade=grade;const p=vocabPool();out[grade]={count:p.length,unique:new Set(p.map(w=>w.en)).size};}}finally{student.grade=old;}
  G.audit={source:typeof f1VocabForStudent==='function'?'f1VocabForStudent':'vocabForStudent',counts:out};
  console.info('[Frontline1944] Vocabulary audit',G.audit);return G.audit;
}
function ensureProgress(){
  if(!window.state)return null;
  state.frontline1944=state.frontline1944||{};const p=state.frontline1944;
  p.claims=Array.isArray(p.claims)?p.claims:[];p.wordsDone=Number(p.wordsDone)||0;p.fortressSerial=Number(p.fortressSerial)||0;
  G.claimed=new Set(p.claims);G.wordsDone=p.wordsDone;G.fortressSerial=p.fortressSerial;return p;
}
function persist(){const p=ensureProgress();if(!p)return;p.word=G.word&&G.word.en||'';p.meaning=G.word&&G.word.th||'';p.letterPos=G.pos;p.wordRunId=G.wordRunId;p.wordsDone=G.wordsDone;p.fortressSerial=G.fortressSerial;p.claims=Array.from(G.claimed).slice(-160);if(typeof saveState==='function')saveState();if(typeof authPushSave==='function')try{authPushSave(false);}catch(e){}}
function claim(id,coins){if(G.claimed.has(id))return false;G.claimed.add(id);if(typeof addCoins==='function')addCoins(coins);persist();return true;}
function chooseWord(forceNew){
  const pool=vocabPool();if(!pool.length){showToast('ไม่พบคลังคำศัพท์','Frontline จะไม่สร้างฐานคำศัพท์ซ้ำเอง');return false;}
  const p=ensureProgress(),saved=!forceNew&&p&&p.word&&normalizeWord({en:p.word,th:p.meaning});
  if(saved&&p.letterPos<saved.en.length){G.word=saved;G.pos=clamp(Number(p.letterPos)||0,0,saved.en.length);G.wordRunId=p.wordRunId||('W'+Date.now().toString(36));}
  else{const prev=G.word&&G.word.en;let pick=pool[Math.floor(Math.random()*pool.length)];if(pool.length>1&&pick.en===prev)pick=pool[(pool.indexOf(pick)+1)%pool.length];G.word=pick;G.pos=0;G.wordRunId='W'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
  updateHud();return true;
}
function pronounce(w){try{if(typeof speakWord==='function'){speakWord(w);return;}if(typeof pronounceWord==='function'){pronounceWord(w);return;}if(typeof speechSynthesis!=='undefined'){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(w));}}catch(e){}}
function awardLetter(fortressId){if(!G.word||G.pos>=G.word.en.length)return;const ch=G.word.en[G.pos],id='fortress:'+fortressId;if(!claim(id,CFG.letterCoins))return;G.pos++;showToast('ยึดตัวอักษร '+ch,'+'+CFG.letterCoins+' เหรียญ · '+G.word.en.slice(0,G.pos));burst(G.player.group.position.clone(),0xffda72,18);if(G.pos>=G.word.en.length){const done=G.word.en,bid='word:'+G.wordRunId;if(claim(bid,CFG.wordBonus)){G.wordsDone++;if(window.state&&state.frontline1944)state.frontline1944.wordsDone=G.wordsDone;showToast(done+' สำเร็จ!','โบนัส +'+CFG.wordBonus+' เหรียญ · เตรียมคำถัดไป');pronounce(done);burst(G.player.group.position.clone(),0xffef9a,32);}setTimeout(()=>{if(G.running){chooseWord(true);activateNextFortress();}},1000);}else{persist();activateNextFortress();}updateHud();}
function loadThree(){return new Promise((res,rej)=>{if(window.THREE){res();return;}const old=document.querySelector('script[data-fl44-three]');if(old){old.addEventListener('load',()=>res(),{once:true});old.addEventListener('error',rej,{once:true});return;}const s=document.createElement('script');s.src='js/vendor/three.min.js';s.dataset.fl44Three='1';s.onload=()=>res();s.onerror=()=>rej(new Error('THREE load failed'));document.head.appendChild(s);});}
function makeDom(){
  const r=document.createElement('div');r.id='vw-frontline1944';r.innerHTML=`<div class="fl44-loading"><div><b>Vocab World: Frontline 1944</b><small>กำลังจัดกำลังรบ · ADMIN PREVIEW</small></div></div><div class="fl44-hud"><div class="fl44-top"><div class="fl44-panel fl44-player"><div class="fl44-player-row"><b>PLAYER</b><span id="fl44-hptext">100/100</span></div><div class="fl44-bar"><i id="fl44-hp"></i></div></div><div class="fl44-panel fl44-word"><small>TARGET WORD</small><b id="fl44-word">—</b><div class="fl44-slots" id="fl44-slots"></div></div><div class="fl44-panel fl44-coins"><span>เหรียญรวม</span><strong id="fl44-coins">0</strong><span id="fl44-grade"></span></div></div><div class="fl44-panel fl44-boss" id="fl44-boss"><div class="fl44-boss-name" id="fl44-bossname">FORTRESS COMMANDER</div><div class="fl44-bar"><i id="fl44-bosshp"></i></div></div><div class="fl44-panel fl44-objective"><b id="fl44-objective">ค้นหาฐานศัตรู</b><span id="fl44-distance">—</span><div class="fl44-arrow" id="fl44-arrow">➤</div></div><div class="fl44-panel fl44-state" id="fl44-state">เดินทางไปยังฐานเป้าหมาย</div></div><div class="fl44-controls"><div class="fl44-stick" id="fl44-stick"><i class="fl44-knob"></i></div><button class="fl44-fire" id="fl44-fire">FIRE</button></div><button class="fl44-exit" id="fl44-exit">ออก</button><div class="fl44-toast" id="fl44-toast"><b></b><span></span></div>`;document.body.appendChild(r);G.root=r;
  $('#fl44-exit').onclick=close;bindControls();
}
function showToast(a,b){if(!G.root)return;const t=$('#fl44-toast');t.querySelector('b').textContent=a;t.querySelector('span').textContent=b||'';t.classList.add('on');clearTimeout(G.toastTimer);G.toastTimer=setTimeout(()=>t&&t.classList.remove('on'),1700);}
function mat(color,rough=.9){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.03});}
function box(w,h,d,color){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.castShadow=m.receiveShadow=true;return m;}
function plane(w,h,color,opacity=1){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshLambertMaterial({color,transparent:opacity<1,opacity,depthWrite:opacity>=1}));m.rotation.x=-Math.PI/2;m.receiveShadow=true;return m;}
function add(layer,o){G.layers[layer].add(o);return o;}
function buildLayers(){for(let i=0;i<8;i++){const g=new THREE.Group();g.name='FrontlineLayer'+i;g.renderOrder=i;G.scene.add(g);G.layers[i]=g;}}
function buildWorld(){
  const T=THREE;G.scene=new T.Scene();G.scene.background=new T.Color(0x9ca98f);G.scene.fog=new T.FogExp2(0xa8ad99,.0095);buildLayers();
  const amb=new T.HemisphereLight(0xdde2cb,0x4e4938,1.35);G.scene.add(amb);const sun=new T.DirectionalLight(0xffefc8,1.5);sun.position.set(-55,80,35);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-85;sun.shadow.camera.right=85;sun.shadow.camera.top=85;sun.shadow.camera.bottom=-85;G.scene.add(sun);
  add(1,plane(CFG.mapW,CFG.mapH,0x66764e));
  // Major terrain regions: deliberately broad/irregular-looking color fields, not a repeated square tilemap.
  const fields=[[-105,-55,70,44,0x8b824b],[-35,-75,50,36,0x798244],[45,-70,58,40,0x9a8c51],[110,-56,60,48,0x7b7444],[-108,35,58,56,0x687349],[-43,40,64,52,0x737a4e],[56,38,72,48,0x656f48],[118,52,54,58,0x596848]];
  fields.forEach((f,i)=>{const p=plane(f[2],f[3],f[4]);p.position.set(f[0],.025,f[1]);p.rotation.z=(i%3-1)*.06;add(1,p);for(let n=0;n<7;n++){const row=plane(f[2]*.92,.35,i%2?0x5f673d:0x73673d,.42);row.position.set(f[0],.04,f[1]-f[3]*.36+n*f[3]*.12);row.rotation.z=p.rotation.z;add(2,row);}});
  const river=plane(16,CFG.mapH*.96,0x486f78,.92);river.position.set(18,.06,0);river.rotation.z=.045;add(2,river);for(const z of [-65,8,73]){const bridge=box(24,.55,6,0x776a54);bridge.position.set(18,.45,z);add(4,bridge);for(let x=-10;x<=10;x+=4){const rail=box(.35,1.2,6.4,0x4b493d);rail.position.set(18+x,1,z);add(4,rail);}}
  const roads=[[-120,-3,95,8,.06],[-35,-2,100,8,-.02],[77,-2,105,8,.04],[-48,72,120,7,-.18],[86,-72,115,7,.12]];roads.forEach(r=>{const p=plane(r[2],r[3],0x796d58);p.position.set(r[0],.075,r[1]);p.rotation.z=r[4];add(2,p);});
  // trenches / defensive line
  for(let i=0;i<9;i++){const t=box(8,.35,1.3,0x514b36);t.position.set(-5+i*8,.25,86+(i%2)*2);t.rotation.y=(i%2?-.22:.15);add(3,t);}
  // recognizable village / ruins / camp
  [[-75,8,0],[72,62,1],[-78,73,2]].forEach(([x,z,kind])=>{for(let i=0;i<7;i++)makeHouse(x+(i%4)*8,z+Math.floor(i/4)*10,kind===2&&i%2);});
  for(let i=0;i<22;i++)makeTree(-132+Math.random()*48,-5+Math.random()*85,1+Math.random()*.3);
  for(let i=0;i<18;i++)makeTree(72+Math.random()*70,-5+Math.random()*85,.9+Math.random()*.4);
  for(let i=0;i<10;i++)makeTree(-10+Math.random()*42,-105+Math.random()*52,.8+Math.random()*.35);
  for(let i=0;i<24;i++){const c=box(.7,.35,.7,0x4c4938);c.position.set(-150+Math.random()*300,.2,-105+Math.random()*210);c.rotation.y=Math.random()*Math.PI;add(3,c);}
  for(let i=0;i<8;i++){const s=makeSmoke();s.position.set(-135+Math.random()*270,5,-95+Math.random()*190);add(7,s);G.smoke.push({sprite:s,phase:Math.random()*10,baseY:s.position.y});}
  buildSites();makePlayer();
}
function makeHouse(x,z,ruined){const g=new THREE.Group();const body=box(6,ruined?2.2:3.4,5,ruined?0x766a59:0x91866d);body.position.y=body.geometry.parameters.height/2;g.add(body);if(!ruined){const roof=new THREE.Mesh(new THREE.ConeGeometry(4.6,2.5,4),mat(0x574c3f));roof.position.y=4.5;roof.rotation.y=Math.PI/4;roof.castShadow=true;g.add(roof);roof.renderOrder=6;}else{const wall=box(2.2,2.3,.5,0x665d50);wall.position.set(2.4,2.5,0);g.add(wall);wall.renderOrder=6;}g.position.set(x,0,z);add(4,g);}
function makeTree(x,z,s=1){const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.42*s,.6*s,3.4*s,7),mat(0x57472f));trunk.position.set(x,1.7*s,z);trunk.castShadow=true;add(4,trunk);const canopy=new THREE.Group();const m=mat(0x3f5d39);for(const [dx,dy,dz,sc] of [[0,0,0,1],[1.1,.15,.1,.8],[-1,.1,.2,.75],[.2,.35,-.8,.7]]){const q=new THREE.Mesh(new THREE.DodecahedronGeometry(1.75*s*sc,0),m);q.position.set(dx*s,dy*s,dz*s);q.castShadow=true;canopy.add(q);}canopy.position.set(x,4.1*s,z);canopy.renderOrder=6;canopy.userData.occluder=true;add(6,canopy);return {trunk,canopy};}
function makeSmoke(){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d'),g=x.createRadialGradient(32,32,2,32,32,30);g.addColorStop(0,'rgba(58,59,54,.45)');g.addColorStop(1,'rgba(58,59,54,0)');x.fillStyle=g;x.fillRect(0,0,64,64);const tx=new THREE.CanvasTexture(c),m=new THREE.SpriteMaterial({map:tx,transparent:true,depthWrite:false});const s=new THREE.Sprite(m);s.scale.set(12,12,1);return s;}
function makeChibi(color=0x496547,enemy=false){const g=new THREE.Group(),skin=mat(0xd9b38c),cloth=mat(color),dark=mat(enemy?0x4d4036:0x293a2e);const body=box(1.6,2.0,1.05,color);body.position.y=2;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.72,12,9),skin);head.position.y=3.55;head.castShadow=true;g.add(head);const helmet=new THREE.Mesh(new THREE.SphereGeometry(.78,12,7,0,Math.PI*2,0,Math.PI*.55),dark);helmet.position.y=3.7;g.add(helmet);for(const sx of [-.42,.42]){const leg=box(.5,1.2,.55,0x393d32);leg.position.set(sx,.65,0);g.add(leg);}const gun=box(.18,.18,1.55,0x3b3730);gun.position.set(.68,2.2,-.65);gun.rotation.x=.1;g.add(gun);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});return g;}
function makePlayer(){const g=makeChibi(0x48664d,false);g.position.set(-135,0,-78);g.renderOrder=5;add(5,g);G.player={group:g,hp:CFG.playerHP,maxHp:CFG.playerHP,vel:new THREE.Vector3(),yaw:0,invuln:0};}
function buildSites(){G.sites=[[-112,-58],[-54,68],[55,-72],[112,45],[0,88],[126,-28]].map((p,i)=>({x:p[0],z:p[1],i,usedAt:-999}));G.objectiveSite=0;}
function activateNextFortress(){
  if(G.fortress){disposeGroup(G.fortress.group);G.fortress=null;}G.enemies.splice(0).forEach(e=>disposeGroup(e.group));
  const pp=G.player?G.player.group.position:{x:0,z:0},candidates=G.sites.filter(s=>Math.hypot(s.x-pp.x,s.z-pp.z)>70).sort((a,b)=>a.usedAt-b.usedAt);const site=(candidates[0]||G.sites[(G.objectiveSite+1)%G.sites.length]);site.usedAt=G.fortressSerial;G.objectiveSite=site.i;G.fortressSerial++;
  G.fortress=makeFortress(site,G.fortressSerial);persist();updateHud();
}
function makeFortress(site,serial){const g=new THREE.Group();g.position.set(site.x,0,site.z);add(4,g);const sand=mat(0x756a4d);for(let i=-3;i<=3;i++){for(const [x,z] of [[i*2.4,-9],[i*2.4,9],[-9,i*2.4],[9,i*2.4]]){if(Math.abs(x)<3&&z===9)continue;const w=new THREE.Mesh(new THREE.BoxGeometry(2.2,1.1,1.3),sand);w.position.set(x,.55,z);w.rotation.y=(Math.abs(x)===9?Math.PI/2:0);w.castShadow=true;g.add(w);}}
  const core=box(5.5,4.2,5.5,0x5a5444);core.position.y=2.1;g.add(core);const tower=box(2.8,3.4,2.8,0x49483e);tower.position.y=5.5;g.add(tower);const flag=box(.12,4,.12,0x423c31);flag.position.set(0,9,0);g.add(flag);const flagcloth=box(2,.8,.08,0x8a7853);flagcloth.position.set(1,10.4,0);g.add(flagcloth);
  return {group:g,site,serial,id:'F'+serial,state:'dormant',core,coreHP:CFG.fortressCoreHP,maxCoreHP:CFG.fortressCoreHP,boss:null,defendersSpawned:false};}
function spawnDefenders(){if(!G.fortress||G.fortress.defendersSpawned)return;G.fortress.defendersSpawned=true;G.fortress.state='defenders';const n=Math.min(7,CFG.defendersBase+Math.floor(G.fortress.serial/4));for(let i=0;i<n;i++){const a=i/n*Math.PI*2,r=13+Math.random()*5;spawnEnemy(G.fortress.group.position.x+Math.cos(a)*r,G.fortress.group.position.z+Math.sin(a)*r,false);}showToast('เข้าสู่เขตฐานศัตรู','ทำลายหน่วยป้องกันเพื่อเรียกบอส');updateHud();}
function spawnEnemy(x,z,boss){if(G.enemies.length>=CFG.enemyCap&&!boss)return null;const g=boss?makeBossFigure():makeChibi(0x6a5b43,true);g.position.set(x,0,z);g.renderOrder=5;add(5,g);const max=boss?CFG.bossBaseHP+G.fortress.serial*12:30+Math.min(25,G.fortress.serial*2),e={group:g,hp:max,maxHp:max,boss,fireAt:Math.random(),speed:boss?5.2:6.3,dead:false};G.enemies.push(e);if(boss)G.fortress.boss=e;return e;}
function makeBossFigure(){const g=new THREE.Group(),base=box(3.8,1.2,5.4,0x4e5540);base.position.y=1;g.add(base);const turret=box(2.5,1.1,2.8,0x62634b);turret.position.y=2;g.add(turret);const barrel=box(.35,.35,3.8,0x353a32);barrel.position.set(0,2.2,-2.4);g.add(barrel);for(const sx of [-1.8,1.8]){const track=box(.55,.8,5.6,0x292d29);track.position.set(sx,.6,0);g.add(track);}g.traverse(o=>{if(o.isMesh)o.castShadow=true;});return g;}
function spawnBoss(){if(!G.fortress||G.fortress.boss)return;G.fortress.state='boss';const p=G.fortress.group.position;spawnEnemy(p.x,p.z-6,true);showToast('BOSS: Fortress Commander','สังเกตจังหวะยิงและเคลื่อนที่หลบ');updateHud();}
function firePlayer(){if(!G.running||!G.player||G.shots.length>=CFG.projectileCap)return;const now=performance.now();if(now<G.fireAt)return;G.fireAt=now+150;const p=G.player.group.position,v=new THREE.Vector3(Math.sin(G.player.yaw),0,-Math.cos(G.player.yaw));const m=new THREE.Mesh(new THREE.SphereGeometry(.16,6,5),new THREE.MeshBasicMaterial({color:0xffdb78}));m.position.copy(p).add(new THREE.Vector3(0,2.2,0)).addScaledVector(v,1.5);m.renderOrder=7;add(7,m);G.shots.push({mesh:m,v:v.multiplyScalar(CFG.shotSpeed),life:CFG.shotLife,damage:CFG.shotDamage});}
function enemyFire(e){if(G.enemyShots.length>=CFG.projectileCap>>1)return;const p=e.group.position,d=G.player.group.position.clone().sub(p);d.y=0;if(d.lengthSq()<4)return;d.normalize();const m=new THREE.Mesh(new THREE.SphereGeometry(.18,6,5),new THREE.MeshBasicMaterial({color:e.boss?0xff6d3c:0xe6b96a}));m.position.copy(p).add(new THREE.Vector3(0,e.boss?2.1:2,0)).addScaledVector(d,1.2);add(7,m);G.enemyShots.push({mesh:m,v:d.multiplyScalar(e.boss?24:20),life:2.3,damage:e.boss?14:8});}
function burst(pos,color,n){n=G.lowFx?Math.ceil(n*.45):n;n=Math.min(n,CFG.fxCap-G.fx.length);for(let i=0;i<n;i++){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.09+Math.random()*.12,0),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.95,depthWrite:false}));m.position.copy(pos).add(new THREE.Vector3(0,1.5,0));add(7,m);G.fx.push({mesh:m,v:new THREE.Vector3((Math.random()-.5)*8,2+Math.random()*6,(Math.random()-.5)*8),life:.4+Math.random()*.6});}}
function damageEnemy(e,d){if(e.dead)return;e.hp-=d;burst(e.group.position.clone(),e.boss?0xff8a4c:0xe7c36d,e.boss?4:2);if(e.hp<=0){e.dead=true;burst(e.group.position.clone(),0xffa24e,e.boss?28:12);if(e.boss){G.fortress.state='core';G.fortress.boss=null;showToast('บอสถูกทำลาย','Fortress Core เปิดจุดอ่อนแล้ว');}disposeGroup(e.group);e.group=null;updateHud();}}
function damagePlayer(d){if(G.player.invuln>0)return;G.player.hp=Math.max(0,G.player.hp-d);G.player.invuln=.55;burst(G.player.group.position.clone(),0xff7048,8);if(G.player.hp<=0){G.player.hp=G.player.maxHp;G.player.group.position.set(-135,0,-78);showToast('ถอยกลับจุดรวมพล','ฟื้น HP แล้ว · ภารกิจยังดำเนินต่อ');}updateHud();}
function destroyCore(){const f=G.fortress;if(!f||f.state!=='core')return;f.state='destroyed';burst(f.group.position.clone(),0xffb351,36);showToast('FORTRESS DESTROYED','กำลังยึดตัวอักษรจากฐาน');const id=f.id;setTimeout(()=>{if(G.running)awardLetter(id);},650);updateHud();}
function tickFortress(dt){const f=G.fortress;if(!f)return;const pd=Math.sqrt(dist2(G.player.group.position,f.group.position));if(f.state==='dormant'&&pd<CFG.fortressTrigger)spawnDefenders();if(f.state==='defenders'){const live=G.enemies.some(e=>!e.dead&&!e.boss);if(f.defendersSpawned&&!live)spawnBoss();}}
function tickEnemies(dt,now){for(const e of G.enemies){if(e.dead||!e.group)continue;const p=e.group.position,d=G.player.group.position.clone().sub(p);d.y=0;const L=d.length();if(L>(e.boss?8:6)&&L<48){d.normalize();e.group.position.addScaledVector(d,e.speed*dt);e.group.rotation.y=Math.atan2(d.x,d.z)+Math.PI;}if(now>e.fireAt&&L<34){enemyFire(e);e.fireAt=now+(e.boss?700:1100)+Math.random()*700;}}G.enemies=G.enemies.filter(e=>!e.dead&&e.group);}
function tickShots(dt){for(const s of G.shots){s.life-=dt;s.mesh.position.addScaledVector(s.v,dt);let hit=false;for(const e of G.enemies){if(!e.dead&&e.group&&dist2(s.mesh.position,e.group.position)<(e.boss?11:3.3)){damageEnemy(e,s.damage);hit=true;break;}}const f=G.fortress;if(!hit&&f&&f.state==='core'&&dist2(s.mesh.position,f.group.position)<14){f.coreHP-=s.damage;burst(s.mesh.position.clone(),0xffb861,4);hit=true;if(f.coreHP<=0)destroyCore();}if(hit)s.life=0;}for(let i=G.shots.length-1;i>=0;i--)if(G.shots[i].life<=0){disposeObj(G.shots[i].mesh);G.shots.splice(i,1);}
  for(const s of G.enemyShots){s.life-=dt;s.mesh.position.addScaledVector(s.v,dt);if(dist2(s.mesh.position,G.player.group.position)<2.4){damagePlayer(s.damage);s.life=0;}}for(let i=G.enemyShots.length-1;i>=0;i--)if(G.enemyShots[i].life<=0){disposeObj(G.enemyShots[i].mesh);G.enemyShots.splice(i,1);}}
function tickFx(dt,t){for(const f of G.fx){f.life-=dt;f.v.y-=7*dt;f.mesh.position.addScaledVector(f.v,dt);f.mesh.material.opacity=clamp(f.life*2,0,1);}for(let i=G.fx.length-1;i>=0;i--)if(G.fx[i].life<=0){disposeObj(G.fx[i].mesh);G.fx.splice(i,1);}for(const s of G.smoke){s.sprite.position.y=s.baseY+Math.sin(t*.0005+s.phase)*1.5;s.sprite.material.opacity=.45+Math.sin(t*.0007+s.phase)*.1;}}
function tickPlayer(dt){const p=G.player,ix=(G.keys.has('ArrowRight')||G.keys.has('KeyD')?1:0)-(G.keys.has('ArrowLeft')||G.keys.has('KeyA')?1:0)+G.joy.x,iz=(G.keys.has('ArrowDown')||G.keys.has('KeyS')?1:0)-(G.keys.has('ArrowUp')||G.keys.has('KeyW')?1:0)+G.joy.y;let x=clamp(ix,-1,1),z=clamp(iz,-1,1),L=Math.hypot(x,z);if(L>.08){x/=Math.max(1,L);z/=Math.max(1,L);p.group.position.x=clamp(p.group.position.x+x*CFG.playerSpeed*dt,-CFG.mapW*.47,CFG.mapW*.47);p.group.position.z=clamp(p.group.position.z+z*CFG.playerSpeed*dt,-CFG.mapH*.47,CFG.mapH*.47);p.yaw=Math.atan2(x,-z);p.group.rotation.y=p.yaw;}p.invuln=Math.max(0,p.invuln-dt);p.group.visible=p.invuln<=0||Math.floor(p.invuln*18)%2===0;if(G.firing||G.keys.has('Space')||G.keys.has('KeyJ'))firePlayer();}
function cameraTick(dt){const p=G.player.group.position,target=new THREE.Vector3(p.x+27,38,p.z+31);G.camera.position.lerp(target,1-Math.pow(.002,dt));G.camera.lookAt(p.x,0,p.z);}
function updateObjective(){if(!G.fortress||!G.player)return;const a=G.player.group.position,b=G.fortress.group.position,dx=b.x-a.x,dz=b.z-a.z,ang=Math.atan2(dx,-dz)*180/Math.PI,meters=Math.round(Math.hypot(dx,dz)*4);const ar=$('#fl44-arrow');if(ar)ar.style.transform='rotate('+ang+'deg)';const ds=$('#fl44-distance');if(ds)ds.textContent=meters+' m';}
function fortressStateText(){const f=G.fortress;if(!f)return 'กำลังค้นหาเป้าหมาย';return ({dormant:'เดินทางไปยังฐานเป้าหมาย',defenders:'ทำลายหน่วยป้องกัน',boss:'กำจัดบอสประจำฐาน',core:'บอสพ่ายแล้ว · ทำลาย Fortress Core',destroyed:'ฐานถูกทำลาย · รับตัวอักษร'})[f.state]||f.state;}
function updateHud(){if(!G.root)return;const hp=G.player?G.player.hp:CFG.playerHP,$hp=$('#fl44-hp');if($hp)$hp.style.width=(hp/CFG.playerHP*100)+'%';const ht=$('#fl44-hptext');if(ht)ht.textContent=Math.ceil(hp)+'/'+CFG.playerHP;const w=$('#fl44-word');if(w)w.textContent=G.word?G.word.en:'—';const slots=$('#fl44-slots');if(slots){slots.innerHTML='';if(G.word)for(let i=0;i<G.word.en.length;i++){const s=document.createElement('i');s.className='fl44-slot'+(i<G.pos?' done':'');s.textContent=i<G.pos?G.word.en[i]:'_';slots.appendChild(s);}}const c=$('#fl44-coins');if(c)c.textContent=window.state?Number(state.coins||0).toLocaleString():'0';const gr=$('#fl44-grade');if(gr)gr.textContent=(window.state&&state.student&&state.student.grade)||'';const st=$('#fl44-state');if(st)st.textContent=fortressStateText();const b=$('#fl44-boss'),be=G.fortress&&G.fortress.boss;if(b)b.classList.toggle('on',!!be);if(be){$('#fl44-bossname').textContent='FORTRESS COMMANDER · ฐาน '+G.fortress.serial;$('#fl44-bosshp').style.width=clamp(be.hp/be.maxHp*100,0,100)+'%';}const ob=$('#fl44-objective');if(ob)ob.textContent=G.fortress?'Fortress '+G.fortress.serial:'ค้นหาฐานศัตรู';}
function bindControls(){
  const down=e=>{G.keys.add(e.code);if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();},up=e=>G.keys.delete(e.code);listen(window,'keydown',down,{passive:false});listen(window,'keyup',up);
  const stick=$('#fl44-stick'),knob=stick.querySelector('.fl44-knob');function joy(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,m=r.width*.36,L=Math.hypot(dx,dy)||1,k=Math.min(1,m/L);dx*=k;dy*=k;G.joy.x=dx/m;G.joy.y=dy/m;knob.style.transform='translate('+dx+'px,'+dy+'px)';}
  listen(stick,'pointerdown',e=>{G.joy.id=e.pointerId;stick.setPointerCapture(e.pointerId);joy(e);e.preventDefault();},{passive:false});listen(stick,'pointermove',e=>{if(e.pointerId===G.joy.id){joy(e);e.preventDefault();}},{passive:false});const end=e=>{if(e.pointerId===G.joy.id){G.joy.id=null;G.joy.x=G.joy.y=0;knob.style.transform='translate(0,0)';}};listen(stick,'pointerup',end);listen(stick,'pointercancel',end);
  const fire=$('#fl44-fire'),fd=e=>{G.firing=true;fire.classList.add('on');fire.setPointerCapture&&fire.setPointerCapture(e.pointerId);e.preventDefault();},fu=e=>{G.firing=false;fire.classList.remove('on');e.preventDefault();};listen(fire,'pointerdown',fd,{passive:false});listen(fire,'pointerup',fu,{passive:false});listen(fire,'pointercancel',fu,{passive:false});listen(window,'blur',()=>{G.keys.clear();G.firing=false;G.joy.x=G.joy.y=0;});listen(document,'visibilitychange',()=>{if(document.hidden){G.keys.clear();G.firing=false;}});
}
function resize(){if(!G.renderer||!G.camera)return;const w=innerWidth,h=innerHeight,aspect=w/Math.max(1,h),vw=CFG.viewW,vh=vw/aspect;G.camera.left=-vw/2;G.camera.right=vw/2;G.camera.top=vh/2;G.camera.bottom=-vh/2;G.camera.updateProjectionMatrix();G.renderer.setSize(w,h,false);}
function initThree(){const c=document.createElement('canvas');G.root.insertBefore(c,G.root.firstChild);G.renderer=new THREE.WebGLRenderer({canvas:c,antialias:!(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4),alpha:false,powerPreference:'high-performance'});G.renderer.setPixelRatio(Math.min(devicePixelRatio||1,CFG.dpr));G.renderer.shadowMap.enabled=true;G.renderer.shadowMap.type=THREE.PCFSoftShadowMap;G.renderer.outputEncoding=THREE.sRGBEncoding||G.renderer.outputEncoding;G.camera=new THREE.OrthographicCamera(-32,32,18,-18,.1,260);G.camera.position.set(-108,38,-48);G.camera.lookAt(-135,0,-78);resize();listen(window,'resize',resize);listen(window,'orientationchange',()=>setTimeout(resize,120));buildWorld();activateNextFortress();}
function loop(now){if(!G.running)return;const dt=Math.min(.034,G.last?(now-G.last)/1000:.016);G.last=now;tickPlayer(dt);tickFortress(dt);tickEnemies(dt,now);tickShots(dt);tickFx(dt,now);cameraTick(dt);updateObjective();if((now|0)%240<35)updateHud();G.renderer.render(G.scene,G.camera);G.raf=requestAnimationFrame(loop);}
function disposeObj(o){if(!o)return;try{o.parent&&o.parent.remove(o);if(o.geometry)o.geometry.dispose();if(o.material){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{if(m.map)m.map.dispose();m.dispose&&m.dispose();});}}catch(e){}}
function disposeGroup(g){if(!g)return;g.traverse&&g.traverse(o=>{if(o!==g&&o.isMesh){o.geometry&&o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m&&m.dispose&&m.dispose());}});g.parent&&g.parent.remove(g);}
async function open(){
  if(!adminAllowed()){lockNotice();return false;}if(G.running||G.starting)return true;G.starting=true;makeDom();try{await loadThree();ensureProgress();G.lowFx=!!(window.state&&state.noAnim)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4);auditVocabulary();if(!chooseWord(false))throw new Error('Vocabulary source unavailable');initThree();G.running=true;G.last=0;const l=$('.fl44-loading');if(l)l.remove();if(typeof Music!=='undefined'&&Music.suspendBg)Music.suspendBg();G.raf=requestAnimationFrame(loop);showToast('Frontline 1944','ทำลายฐาน → บอส → Fortress Core → ยึดตัวอักษร');return true;}catch(e){console.error('[Frontline1944]',e);const l=$('.fl44-loading');if(l)l.innerHTML='<div><b>เปิด Frontline ไม่สำเร็จ</b><small>'+String(e&&e.message||e)+'</small></div>';setTimeout(close,2200);return false;}finally{G.starting=false;}}
function close(){if(!G.root&&!G.running)return;G.running=false;G.starting=false;cancelAnimationFrame(G.raf);G.raf=0;clearTimeout(G.toastTimer);G.listeners.splice(0).forEach(f=>{try{f();}catch(e){}});G.keys.clear();try{persist();}catch(e){};try{if(typeof speechSynthesis!=='undefined')speechSynthesis.cancel();}catch(e){};if(G.scene){G.scene.traverse(o=>{if(o.isMesh||o.isSprite){o.geometry&&o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{if(m&&m.map)m.map.dispose();m&&m.dispose&&m.dispose();});}});}if(G.renderer){G.renderer.dispose();G.renderer.forceContextLoss&&G.renderer.forceContextLoss();}if(G.root)G.root.remove();if(typeof Music!=='undefined'&&Music.resumeBg)Music.resumeBg();Object.assign(G,{root:null,renderer:null,scene:null,camera:null,player:null,fortress:null,enemies:[],shots:[],enemyShots:[],fx:[],smoke:[],layers:{},last:0,firing:false});if(typeof renderDashboard==='function')try{renderDashboard();}catch(e){};}
function routeCheck(){syncAdminEntry();let requested=window.__VW_FRONTLINE1944_ROUTE__===true;try{requested=requested||new URLSearchParams(location.search).get('go')==='frontline1944';}catch(e){}if(!requested)return;if(adminAllowed()){if(!G.routeTried){G.routeTried=true;open();}}else if(!G.routeDenied){G.routeDenied=true;lockNotice();}}
function occlusionAcceptance(){if(!window.THREE)return {pass:false,reason:'THREE not loaded'};const tree=G.layers[6]&&G.layers[6].children.find(x=>x.userData&&x.userData.occluder);return {pass:!!(tree&&tree.renderOrder===6&&G.player&&G.player.group.renderOrder===5),layerPlayer:G.player&&G.player.group.renderOrder,layerCanopy:tree&&tree.renderOrder,depthTest:!!(tree&&tree.children[0]&&tree.children[0].material.depthTest)};}
window.Frontline1944={open,close,auditVocabulary,adminAllowed,_t:{CFG,G,vocabPool,chooseWord,awardLetter,activateNextFortress,occlusionAcceptance,updateHud}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',routeCheck,{once:true});else routeCheck();
let polls=0;const poll=setInterval(()=>{syncAdminEntry();routeCheck();if(++polls>90||document.getElementById('btn-rail-frontline1944')&&!document.getElementById('btn-rail-frontline1944').hidden)clearInterval(poll);},500);
})();
