"use strict";
/* ============================================================
   🚗🐾 PET SHOPPING 3D — รอบ 1164
   โลกสั้น first-person แยกจาก Adventure3D: ร้านใกล้, GPS ชัด,
   ร้านสร้างเป็นองค์ประกอบสถาปัตย์จริง ไม่ใช่กล่องแปะภาพ
   ============================================================ */
window.PetShopping3D=(()=>{
  const STORE_POS=Object.freeze({food:Object.freeze({x:-42,z:-82}),fashion:Object.freeze({x:42,z:-82})});
  let root,scene,camera,renderer,raf,last=0,running=false,paused=false,target='food',carId='car_01';
  let car={x:0,z:18,yaw:Math.PI,speed:0,steer:0},keys={},listeners=[],routeLine,storeBtn,gpsEl,wheelEl,petEl,speedEl,radioEl;
  let steerCtl=0,padThr=false,padBr=false,gearR=false,kBack=false,dSpeed=0,dSteer=0,dVelX=0,dVelZ=0,dCamYaw=0,dRoll=0,dRollV=0,carRevBeepAt=0,collisionAt=0;
  let steerHitEl,steerKnobEl,throttleEl,brakeEl,gearDEl,gearREl,hornEl,turnEl,turnDotEl;
  let dashEl,dashImgEl,gaugeEl,gaugeCtx,radioListEl,radioVizEl,radioVizCtx,mirrorRearEl,mirrorLEl,mirrorREl;
  let engineEl,beltEl,goEl,startEl,lawEl,camEl,seatEl,wiperEl,visorEl,warningEl,carMesh;
  let mirrorRearCam,mirrorLCam,mirrorRCam,cam3=false,seatLevel=0,wiperOn=false,visorOn=false;
  let carEngineOn=false,carBelted=false,carStartOpen=true,carBeltFined=false,carOverSpeed=false,carFines=[];
  let turnSig=0,turnAt=0,turnYawOn=0,turnReturnAt=0,turnClickPhase=-1;
  let solidRects=[],solidCircles=[];
  const disposables=[];
  const C={food:0x81b89a,fashion:0xd694be,road:0x59636b,walk:0xe9d8bf};
  /* ============================================================
     🚗🏙️ รอบ 1164 — คัดลอกระบบขับรถจาก “เมืองกำแพงเพชร” โดยตรง
     Source of truth: js/adventure3d.js โซน 🚗 โหมด drive (KPP), ไม่ใช่บ้านโพธิ์สวัสดิ์
     ยกมาทั้ง physics, cockpit, gauges, mirrors, camera, start/belt, D/R,
     turn signal, radio/equalizer และเสียง; GPS ยังเป็น Pet Shopping เดิมเท่านั้น
     ============================================================ */
  const CAR_ACCEL=11,CAR_BRAKE=15,CAR_VMAX=55.6,CAR_VMAX_OFF=7,CAR_VREV=6.5,CAR_WB=2.6,CAR_STEER_MAX=.52;
  const CAR_EYE=1.55,CAR_LEGAL_KMH=90,CAR_FINE_SPEED=200,CAR_FINE_BELT=300,CAR_REPAIR_FEE=1000;
  const DASH_CROP_Y=.54,CAR_ROLL_MAX=.035,CAR_ROLL_GAIN=.0024,CAR_ROLL_SPRING=36,CAR_ROLL_DAMP=14;
  const WORLD_HALF=700,DRIVE_LIMIT=480;
  const RADIO_RECT=[560,514,835,606];
  const CAR_RADIO_RECT={car_01:[555,456,856,606],car_02:[585,518,821,652],car_03:[555,524,787,645],car_04:[506,471,789,591],car_05:[512,543,749,669],car_06:[550,500,788,606],car_07:[563,580,782,685],car_08:[528,598,710,700],car_09:[550,501,786,592],car_10:[521,520,808,669]};
  const radioBars=new Float32Array(32);
  function onRoad(x,z){return Math.abs(x)<=15||Math.abs(z+55)<=13;}
  const CarSnd={ctx:null,master:null,osc:null,osc2:null,gain:null,lp:null,on:false,rpm:0,skidGain:null,skidBp:null,
    ac(){if(!this.ctx){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;this.ctx=new A();this.master=this.ctx.createGain();this.master.gain.value=1;this.master.connect(this.ctx.destination);}if(this.ctx.state==='suspended')this.ctx.resume();return this.ctx;},
    start(){if(this.on)return;try{const c=this.ac();if(!c)return;this.gain=c.createGain();this.gain.gain.value=0;this.lp=c.createBiquadFilter();this.lp.type='lowpass';this.lp.frequency.value=520;this.osc=c.createOscillator();this.osc.type='sawtooth';this.osc.frequency.value=55;this.osc2=c.createOscillator();this.osc2.type='square';this.osc2.frequency.value=28;const g2=c.createGain();g2.gain.value=.5;this.osc.connect(this.lp);this.osc2.connect(g2);g2.connect(this.lp);this.lp.connect(this.gain);this.gain.connect(this.master);this.osc.start();this.osc2.start();this.on=true;this.rpm=0;}catch(e){}},
    ignite(){try{const c=this.ac();if(!c)return;const t=c.currentTime,o=c.createOscillator(),g=c.createGain(),lfo=c.createOscillator(),lg=c.createGain();o.type='sawtooth';o.frequency.setValueAtTime(72,t);lfo.frequency.value=11;lg.gain.value=26;lfo.connect(lg);lg.connect(o.frequency);g.gain.setValueAtTime(.07,t);g.gain.setValueAtTime(.07,t+.62);g.gain.exponentialRampToValueAtTime(.001,t+.8);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+.85);lfo.start(t);lfo.stop(t+.85);setTimeout(()=>{this.start();if(this.on)this.rpm=.95;},680);}catch(e){}},
    update(th,sp,dt){if(!this.on)return;const mute=(typeof state!=='undefined'&&state.sound===false)||!running;if(this.master)this.master.gain.setTargetAtTime(mute?0:1,this.ctx.currentTime,.08);const tgt=.18+Math.min(1,sp/CAR_VMAX)*.72+(th>0?.14:0);this.rpm+=(tgt-this.rpm)*Math.min(1,dt*3);this.osc.frequency.value=48+this.rpm*175;this.osc2.frequency.value=24+this.rpm*88;this.lp.frequency.value=360+this.rpm*950;this.gain.gain.value=.03+this.rpm*.05;},
    skidStart(){if(this.skidGain||!this.ctx)return;try{const c=this.ctx,nb=c.createBuffer(1,c.sampleRate*2,c.sampleRate),d=nb.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const src=c.createBufferSource();src.buffer=nb;src.loop=true;const bp=c.createBiquadFilter();bp.type='bandpass';bp.frequency.value=1650;bp.Q.value=5.5;const g=c.createGain();g.gain.value=0;src.connect(bp);bp.connect(g);g.connect(this.master);src.start();this.skidGain=g;this.skidBp=bp;}catch(e){}},
    setSkid(amt){if(typeof state!=='undefined'&&state.sound===false){if(this.skidGain)this.skidGain.gain.value=0;return;}if(!this.ctx)return;if(!this.skidGain)this.skidStart();if(!this.skidGain)return;const a=Math.max(0,Math.min(1,amt)),tgt=a*a*.13,g=this.skidGain.gain;g.value+=(tgt-g.value)*.35;if(this.skidBp)this.skidBp.frequency.value=1350+a*900;},
    tone(freq,dur=.2,vol=.055,type='square'){try{const c=this.ac();if(!c)return;const t=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur+.02);}catch(e){}},
    revBeep(){this.tone(1000,.2,.055);},horn(){this.tone(440,.42,.09);this.tone(554,.42,.09);},
    thud(){this.tone(86,.3,.18,'sine');},
    tlClick(hi){this.tone(hi?1480:960,.05,.07);this.tone(hi?420:300,.07,.05,'sine');},
    beltClick(){try{const c=this.ac();if(!c)return;const t=c.currentTime,n=c.createBufferSource(),nb=c.createBuffer(1,c.sampleRate*.22,c.sampleRate),d=nb.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);n.buffer=nb;const bp=c.createBiquadFilter();bp.type='bandpass';bp.frequency.value=2600;const ng=c.createGain();ng.gain.value=.06;n.connect(bp);bp.connect(ng);ng.connect(this.master);n.start(t);[[.24,2000],[.32,1150]].forEach(([dt0,f])=>{const o=c.createOscillator(),g=c.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.14,t+dt0);g.gain.exponentialRampToValueAtTime(.001,t+dt0+.05);o.connect(g);g.connect(this.master);o.start(t+dt0);o.stop(t+dt0+.07);});}catch(e){}},
    stop(){if(this.skidGain)this.skidGain.gain.value=0;if(this.master&&this.ctx)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.05);}
  };
  function sndKick(){CarSnd.ac();}
  function syncGearUi(){if(!gearDEl||!gearREl)return;gearDEl.classList.toggle('on',!gearR);gearREl.classList.toggle('on',gearR);throttleEl&&throttleEl.classList.toggle('rev',gearR);const lb=throttleEl&&throttleEl.querySelector('small');if(lb)lb.textContent=gearR?'ถอย':'เร่ง';}
  function setGear(rev){if(gearR===rev)return;gearR=rev;syncGearUi();if(typeof sfx!=='undefined'&&sfx.select)sfx.select();}
  function mat(color,opt={}){const m=new THREE.MeshStandardMaterial({color,roughness:opt.roughness??.7,metalness:opt.metalness??.05,transparent:!!opt.transparent,opacity:opt.opacity??1});disposables.push(m);return m;}
  function mesh(g,m,x,y,z,parent=scene){const q=new THREE.Mesh(g,m);q.position.set(x,y,z);parent.add(q);disposables.push(g);return q;}
  function box(x,y,z,w,h,d,m,parent=scene){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,parent);}
  function solidRect(x,z,w,d,pad=.75){solidRects.push({x,z,hw:w/2+pad,hd:d/2+pad});}
  function solidCircle(x,z,r){solidCircles.push({x,z,r:r+1.15});}
  function hitsSolid(x,z){for(const b of solidRects)if(Math.abs(x-b.x)<=b.hw&&Math.abs(z-b.z)<=b.hd)return true;for(const c of solidCircles){const dx=x-c.x,dz=z-c.z;if(dx*dx+dz*dz<=c.r*c.r)return true;}return false;}
  function loadTexture(url,onReady){
    const owner=scene,finish=tex=>{if(scene!==owner||!root){if(tex.image&&tex.image.close)tex.image.close();tex.dispose();return;}tex.colorSpace=THREE.SRGBColorSpace;tex.needsUpdate=true;disposables.push(tex);onReady(tex);};
    if(typeof fetch==='function'&&typeof createImageBitmap==='function')fetch(url,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.blob();}).then(createImageBitmap).then(bm=>finish(new THREE.Texture(bm))).catch(()=>new THREE.TextureLoader().load(url,finish,undefined,()=>{}));
    else new THREE.TextureLoader().load(url,finish,undefined,()=>{});
  }
  function listen(el,type,fn,opt){el.addEventListener(type,fn,opt);listeners.push(()=>el.removeEventListener(type,fn,opt));}
  function routeFor(start,kind){const p=STORE_POS[kind]||STORE_POS.food;return [{x:start.x,z:start.z},{x:0,z:-55},{x:p.x,z:-55},{x:p.x,z:p.z+8}];}
  function rebuildRoute(){
    if(routeLine){scene.remove(routeLine);routeLine.geometry.dispose();}
    const pts=routeFor(car,target).map(p=>new THREE.Vector3(p.x,.34,p.z));
    const g=new THREE.BufferGeometry().setFromPoints(pts),m=new THREE.LineBasicMaterial({color:0x4fd5ff,transparent:true,opacity:.9});
    routeLine=new THREE.Line(g,m);scene.add(routeLine);disposables.push(g,m);
  }
  function addRoad(){
    const road=mat(C.road),walk=mat(C.walk),line=mat(0xffe8a8),grass=mat(0x9bcf8e);
    box(0,-.18,-55,WORLD_HALF*2,.3,WORLD_HALF*2,grass);box(0,.01,-55,30,.18,WORLD_HALF*2,road);box(0,.02,-55,WORLD_HALF*2,.19,26,road);
    box(-18,.05,-55,6,.2,WORLD_HALF*2,walk);box(18,.05,-55,6,.2,WORLD_HALF*2,walk);box(0,.12,-55,.35,.05,WORLD_HALF*2,line);
    for(let z=WORLD_HALF-55;z>-WORLD_HALF-55;z-=14){box(-7,.13,z,.35,.04,7,line);box(7,.13,z,.35,.04,7,line);}
    for(let x=-WORLD_HALF;x<=WORLD_HALF;x+=14)box(x,.13,-55,7,.04,.32,line);
  }
  function addTree(x,z){const trunk=mat(0x9b6b42),leaf=mat(0x70b87b);box(x,1.4,z,.7,2.8,.7,trunk);mesh(new THREE.SphereGeometry(2.3,9,7),leaf,x,4,z);solidCircle(x,z,1.15);}
  function facadeTexture(kind){
    loadTexture(`img/pet-shopping/${kind}_window.webp`,tex=>{const m=new THREE.MeshBasicMaterial({map:tex});disposables.push(m);const p=STORE_POS[kind];box(p.x,5.7,p.z+6.18,14,7.3,.12,m);});
  }
  function addShop(kind){
    const p=STORE_POS[kind],accent=mat(C[kind]),stone=mat(kind==='food'?0xf6efdd:0xffeef3),gold=mat(0xc9a45c,{metalness:.55,roughness:.3}),glass=mat(0xbce7ed,{transparent:true,opacity:.32,roughness:.1}),dark=mat(0x3e4b4c),wood=mat(0xa87955);
    const group=new THREE.Group();group.position.set(p.x,0,p.z);group.rotation.y=Math.PI;scene.add(group); // หัน façade เข้าหาถนน/จุดเริ่ม
    solidRect(p.x,p.z,25,18,1.25);
    box(0,.25,0,25,.5,18,stone,group);box(0,5,-6,25,10,1,stone,group);box(-12,5,0,1,10,12,stone,group);box(12,5,0,1,10,12,stone,group);box(0,10,0,26,.7,18,accent,group);
    box(0,10.8,-5.9,27,1.2,1.3,gold,group);box(0,9.7,-5.8,26,.35,1.1,dark,group);
    [-11,-7.3,7.3,11].forEach(x=>{box(x,5,-6.7,.8,9,.8,gold,group);box(x,9.5,-6.7,1.35,.5,1.35,stone,group);});
    [-8.9,-4.4,4.4,8.9].forEach(x=>box(x,5.4,-6.45,3.7,6.8,.22,glass,group));
    box(0,4.3,-6.6,4.2,7.6,.25,glass,group);box(0,8.6,-7.1,9,.35,3,accent,group);
    box(0,3.5,-1.5,3.8,1.3,1.6,wood,group); // checkout
    for(const x of [-8,8])for(let y=1.2;y<6;y+=1.5)box(x,y,-1,1.1,.25,8,wood,group); // wall shelves
    for(const x of [-4,4])box(x,1.1,2,2.8,2.2,6,wood,group); // gondola / fashion islands
    if(kind==='fashion')[-5,5].forEach(x=>{box(x,3.4,3,.18,4,.18,gold,group);box(x,5.3,3,3.4,.18,.18,gold,group);});
    const sign=document.createElement('canvas');sign.width=512;sign.height=128;const c=sign.getContext('2d');c.fillStyle=kind==='food'?'#3d7a67':'#8d507e';c.fillRect(0,0,512,128);c.fillStyle='#fff5d1';c.textAlign='center';c.font='bold 42px sans-serif';c.fillText(kind==='food'?'PAWS & PANTRY':'MAISON DE PAWS',256,78);const tx=new THREE.CanvasTexture(sign);const sm=new THREE.MeshBasicMaterial({map:tx});disposables.push(tx,sm);box(0,10.6,-6.7,13,2.7,.12,sm,group);
    facadeTexture(kind);
  }
  function decorateTown(rows){
    loadTexture('img/pet-shopping/cute_town_mural_v2.webp',tex=>{tex.anisotropy=Math.min(4,renderer&&renderer.capabilities?renderer.capabilities.getMaxAnisotropy():1);const mural=new THREE.MeshBasicMaterial({map:tex}),frame=mat(0xffefd0),awnings=[mat(0xff8f78),mat(0x55c9bd),mat(0xf3c957),mat(0xb69adc)];disposables.push(mural);rows.forEach(({x,z,h},i)=>{const fy=Math.min(h-2.5,5),awning=awnings[i%awnings.length];[-1,1].forEach(face=>{const fz=z+face*6.07;box(x,fy,fz,8,4.2,.13,mural);box(x,fy+2.25,fz,8.5,.28,.22,frame);box(x,fy-2.25,fz,8.5,.28,.22,frame);box(x,fy+2.45,z+face*6.45,9,.35,1.05,awning);});});Object.values(STORE_POS).forEach(p=>[-8.2,8.2].forEach(dx=>{box(p.x+dx,5.1,p.z+6.22,5.6,6.7,.16,mural);box(p.x+dx,8.58,p.z+6.25,6.1,.3,.24,frame);box(p.x+dx,1.62,p.z+6.25,6.1,.3,.24,frame);}));});
  }
  function addTown(){
    const colors=[0xf0c8ae,0xa7cfd4,0xd8c2e5,0xf0dda9],roof=mat(0x6f6564),rows=[];
    for(let i=0;i<54;i++){const side=i%2?-1:1,x=side*(35+(i%3)*12),z=250-Math.floor(i/2)*29;if(Math.abs(z+82)<18)continue;const h=8+(i%4)*2,wall=mat(colors[i%colors.length]);box(x,h/2,z,13,h,12,wall);box(x,h+.4,z,14,.8,13,roof);solidRect(x,z,13,12);rows.push({x,z,side,h});for(let y=3;y<h;y+=3)for(const dx of [-3,3])box(x+dx,y,z-side*6.05,2,1.5,.15,mat(0xfff1b8));}
    for(let z=245;z>-540;z-=20){if(Math.abs(z+82)>16){addTree(-23,z);addTree(23,z);}}
    decorateTown(rows);addShop('food');addShop('fashion');
  }
  function buildScene(){
    solidRects=[];solidCircles=[];
    scene=new THREE.Scene();scene.background=new THREE.Color(0xbfe5ef);scene.fog=new THREE.Fog(0xbfe5ef,85,220);
    camera=new THREE.PerspectiveCamera(66,innerWidth/innerHeight,.1,300);scene.add(new THREE.HemisphereLight(0xfff5df,0x55745c,1.05));const sun=new THREE.DirectionalLight(0xffe7bd,1.25);sun.position.set(-30,50,20);scene.add(sun);
    renderer=new THREE.WebGLRenderer({antialias:false,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;root.prepend(renderer.domElement);
    addRoad();addTown();rebuildRoute();
  }
  /* 🚗🏙️ Cockpit/controls below are direct adapters of KPP drive functions:
     loadCarDash/loadCarWheel, drawCarGauges, radio, mirrors, start/belt and turn signal. */
  function tryImage(sources,onDone){let i=0;const next=()=>{if(i>=sources.length)return onDone(null);const im=new Image();im.onload=()=>onDone(im);im.onerror=next;im.src=sources[i++];};next();}
  function loadCarCockpit(){
    const num=carId.replace('car_','');
    tryImage([`img/3d_car/3d_dash_${carId}.png`,`img/car/dash_${carId}.png`,'img/car/dash.png'],im=>{if(!dashEl)return;dashEl.innerHTML='';if(im){dashEl.appendChild(im);dashImgEl=im;}else{dashEl.innerHTML='<div class="ps3-dash-css"></div>';dashImgEl=null;}radioLayout();});
    tryImage([`img/3d_car/3d_wheel_${num}.png`,'img/car/wheel.png'],im=>{if(!wheelEl)return;wheelEl.innerHTML='';if(im)wheelEl.appendChild(im);else wheelEl.innerHTML='<div class="ps3-wheel-css"></div>';});
  }
  function carDial(c,cx,cy,r,frac,max,step,redFrom){const a0=Math.PI*.75,sweep=Math.PI*1.5;c.save();c.translate(cx,cy);c.fillStyle='rgba(9,12,17,.86)';c.beginPath();c.arc(0,0,r*1.05,0,7);c.fill();c.lineWidth=Math.max(2,r*.06);c.strokeStyle='rgba(150,160,176,.85)';c.stroke();c.fillStyle='#e5e9ef';c.strokeStyle='#edf1f6';c.font=`700 ${Math.max(7,r*.17)}px sans-serif`;c.textAlign='center';c.textBaseline='middle';const n=Math.round(max/step);for(let i=0;i<=n;i++){const a=a0+sweep*i/n,co=Math.cos(a),si=Math.sin(a);c.beginPath();c.moveTo(co*r*.88,si*r*.88);c.lineTo(co*r*.74,si*r*.74);c.stroke();c.fillText(String(i*step),co*r*.56,si*r*.56);}if(redFrom!=null){c.strokeStyle='#ff4038';c.lineWidth=Math.max(2,r*.055);c.beginPath();c.arc(0,0,r*.81,a0+sweep*(redFrom/max),a0+sweep);c.stroke();}const a=a0+sweep*Math.max(0,Math.min(1,frac));c.rotate(a);c.fillStyle='#ff4433';c.beginPath();c.moveTo(-r*.17,0);c.lineTo(0,-r*.04);c.lineTo(r*.8,0);c.lineTo(0,r*.04);c.closePath();c.fill();c.rotate(-a);c.fillStyle='#14171c';c.beginPath();c.arc(0,0,r*.12,0,7);c.fill();c.restore();}
  function drawCarGauges(){if(!gaugeCtx||cam3||!wheelEl)return;const w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio||1,2);if(gaugeEl.width!==Math.round(w*dpr)||gaugeEl.height!==Math.round(h*dpr)){gaugeEl.width=Math.round(w*dpr);gaugeEl.height=Math.round(h*dpr);}const c=gaugeCtx;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const r0=wheelEl.getBoundingClientRect(),r=Math.max(22,r0.height*.105),cx=r0.left+r0.width/2,cy=Math.min(r0.top+r0.height*.285,h-r*1.2);carDial(c,cx-r*1.3,cy,r,Math.abs(dSpeed)*3.6/240,240,40,CAR_LEGAL_KMH);carDial(c,cx+r*1.3,cy,r,.1+(CarSnd.rpm||0)*.75,8,1,6.5);}
  function radioRect(){return CAR_RADIO_RECT[carId]||RADIO_RECT;}
  function radioLayout(){if(!radioEl)return;if(cam3||!dashImgEl||!dashImgEl.parentNode){radioEl.style.display='none';return;}const box=dashImgEl.getBoundingClientRect();if(!box.width)return;const s=box.width/1536,offY=Math.max(0,1024*s-box.height)*DASH_CROP_Y,[x0,y0,x1,y1]=radioRect(),L=box.left+x0*s,T=box.top+y0*s-offY,W=(x1-x0)*s,H=(y1-y0)*s;radioEl.style.display='block';Object.assign(radioEl.style,{left:L+'px',top:T+'px',width:W+'px',height:H+'px'});const dpr=Math.min(devicePixelRatio||1,2);radioVizEl.width=Math.round(W*dpr);radioVizEl.height=Math.round(H*dpr);if(radioListEl){const lw=Math.max(W*2.6,250),ll=Math.max(6,Math.min(L+W/2-lw/2,innerWidth-lw-6));radioListEl.style.left=ll+'px';radioListEl.style.width=lw+'px';radioListEl.style.bottom=(innerHeight-T+8)+'px';}radioState();}
  function radioState(){const on=typeof Music!=='undefined'&&Music.isCarOn();if(!radioEl)return;radioEl.classList.toggle('on',on);radioEl.setAttribute('aria-pressed',String(on));const music=root&&root.querySelector('.ps3-music');if(music){music.classList.toggle('active',on);music.setAttribute('aria-pressed',String(on));}const hint=radioEl.querySelector('.ps3-radio-hint');if(hint)hint.innerHTML=on?'':'<b>♪ MUSIC</b><span>แตะเพื่อเปิดเพลงในรถ</span>';}
  function renderRadioList(){if(!radioListEl||typeof Music==='undefined')return;const tracks=Music.carTracks(),cur=Music.curCar(),m=Music.mode(),lbl={all:['REPEAT ALL','เล่นซ้ำทั้งหมด'],one:['REPEAT ONE','เล่นซ้ำเพลง'],shuffle:['SHUFFLE','สุ่มเล่น']};radioListEl.innerHTML=`<div class="rl-head"><span>🎵 CAR RADIO · เพลงในรถ</span><button class="rl-x" type="button">✕</button></div><div class="rl-tracks">${tracks.map((t,i)=>`<button class="rl-track${i===cur?' on':''}" data-i="${i}" type="button"><span>${i===cur?'▶':'♪'}</span>Track ${i+1}</button>`).join('')}</div><div class="rl-modes">${['all','one','shuffle'].map(k=>`<button class="rl-mode${m===k?' on':''}" data-m="${k}" type="button">${lbl[k][0]}<small>${lbl[k][1]}</small></button>`).join('')}</div><button class="rl-power" type="button">⏻ TURN OFF · ปิดเพลง</button>`;}
  function radioToggle(){if(!radioListEl)return;if(radioListEl.style.display==='block'){radioListEl.style.display='none';return;}renderRadioList();radioLayout();radioListEl.style.display='block';}
  function drawRadioViz(){if(!radioVizCtx||!radioEl||radioEl.style.display==='none')return;const c=radioVizCtx,W=radioVizEl.width,H=radioVizEl.height,g=c.createLinearGradient(0,0,0,H);g.addColorStop(0,'#0a1c34');g.addColorStop(1,'#030a18');c.fillStyle=g;c.fillRect(0,0,W,H);if(typeof Music==='undefined'||!Music.isCarOn())return;const data=Music.vizData(),n=radioBars.length,bw=W/n;for(let i=0;i<n;i++){const v=data?data[i]/255:0;radioBars[i]=v>radioBars[i]?v:radioBars[i]*.85+v*.15;const bh=Math.max(H*.05,radioBars[i]*H*.92),y=H-bh;c.fillStyle=i%3?'#4fc3f7':'#b6f2ff';c.fillRect(i*bw+bw*.16,y,bw*.68,bh);}}
  function turnSet(v){turnSig=v;turnAt=performance.now();turnYawOn=car.yaw;turnReturnAt=0;turnClickPhase=-1;if(turnEl){turnEl.classList.toggle('sig',!!v);turnDotEl.style.top=(v===1?17:v===2?83:50)+'%';}root&&root.classList.toggle('turn-left',v===1);root&&root.classList.toggle('turn-right',v===2);}
  function turnTick(now){if(!turnSig)return;const ph=Math.floor(now/400)%2;if(ph!==turnClickPhase){turnClickPhase=ph;CarSnd.tlClick(ph===0);}let dy=car.yaw-turnYawOn;dy=((dy+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;if(Math.abs(dy)>.87&&Math.abs(dSteer)<.07&&!turnReturnAt)turnReturnAt=now+900;if((turnReturnAt&&now>turnReturnAt)||now-turnAt>20000)turnSet(0);}
  function updateSwitch(btn,on){btn.classList.toggle('on',on);const tx=btn.querySelector('b');if(tx)tx.textContent=on?'เปิด':'ปิด';}
  function showLaw(warn,done){if(!lawEl){done&&done();return;}lawEl.innerHTML=`<h3>🛡️ SAFETY BRIEFING · กฎหมายจราจร</h3>${warn?'<div class="li-warn">⚠️ ยังไม่คาดเข็มขัด ออกรถได้แต่จะถูกปรับเมื่อรถวิ่ง</div>':''}<div class="li-grid"><div>🔒 <b>เข็มขัดนิรภัย · ม.123</b><br><small>ในเกม: ไม่คาดแล้วขับ = ปรับ 🪙${CAR_FINE_BELT}</small></div><div>🚨 <b>ความเร็ว · ม.67</b><br><small>เกิน ${CAR_LEGAL_KMH} กม./ชม. = ใบสั่งครั้งละ 🪙${CAR_FINE_SPEED}</small></div><div>🔧 <b>ขับชนแรง</b><br><small>ค่าซ่อมครั้งละ 🪙${CAR_REPAIR_FEE}</small></div></div><button type="button">🫡 รับทราบ</button>`;lawEl.style.display='block';lawEl.querySelector('button').onclick=()=>{lawEl.style.display='none';done&&done();};}
  function makeDriverCar(){const g=new THREE.Group(),body=mat(0x45a0c9,{metalness:.25}),dark=mat(0x20262b),glass=mat(0xbfe3ff,{transparent:true,opacity:.7}),lamp=mat(0xfff59d);box(0,.75,0,1.9,.6,4.1,body,g);const shield=box(0,1.28,-.62,1.7,.5,.09,glass,g);shield.rotation.x=-.2;[-.6,.6].forEach(x=>box(x,.86,-2.06,.24,.18,.07,lamp,g));g.userData.wheels=[];[[-1,-1.35],[1,-1.35],[-1,1.35],[1,1.35]].forEach(([sx,z])=>{const hold=new THREE.Group();hold.position.set(sx*.97,.5,z);const wh=mesh(new THREE.CylinderGeometry(.5,.5,.32,12),dark,0,0,0,hold);wh.rotation.z=Math.PI/2;g.add(hold);g.userData.wheels.push(wh);});g.visible=false;scene.add(g);return g;}
  function mirrorPass(el,cam,yawOff){if(!el||cam3)return;const r=el.getBoundingClientRect(),dpr=renderer.getPixelRatio(),x=Math.round(r.left*dpr),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr),y=Math.round((innerHeight-r.bottom)*dpr);if(w<2||h<2)return;cam.position.copy(camera.position);cam.rotation.copy(camera.rotation);cam.rotateY(yawOff);cam.aspect=w/h;cam.updateProjectionMatrix();renderer.setViewport(x,y,w,h);renderer.setScissor(x,y,w,h);renderer.render(scene,cam);}
  function drawMirrors(){if(cam3)return;if(!mirrorRearCam){mirrorRearCam=new THREE.PerspectiveCamera(58,1,.4,500);mirrorLCam=mirrorRearCam.clone();mirrorRCam=mirrorRearCam.clone();}renderer.setScissorTest(true);mirrorPass(mirrorRearEl,mirrorRearCam,Math.PI);mirrorPass(mirrorLEl,mirrorLCam,Math.PI*.72);mirrorPass(mirrorREl,mirrorRCam,-Math.PI*.72);renderer.setScissorTest(false);renderer.setViewport(0,0,renderer.domElement.width,renderer.domElement.height);}
  function petVisual(){const p=(typeof activePet==='function')?activePet():null;let src='';try{src=p&&typeof currentPetImg==='function'?currentPetImg(p):'';}catch(e){}return src?`<img src="${src}" alt="${p?escapeHTML(p.name):'น้อง'}">`:`<span>${p&&PETS[p.type]?PETS[p.type].adult:'🐶'}</span>`;}
  function buildHUD(rental){
    const carNo=Number(String(carId).match(/\d+/)?.[0]||1),hue=(188+carNo*17)%360;
    root.style.setProperty('--ps3-accent',`hsl(${hue} 72% 56%)`);
    root.insertAdjacentHTML('beforeend',`
      <div class="ps3-hud"><div class="ps3-gps"><span class="ps3-gps-icon">◆</span><div><b>GPS · ${target==='food'?'ร้านอาหารสัตว์':'ร้านแฟชั่นสัตว์เลี้ยง'}</b><span>ตรงไปตามเส้นนำทาง</span></div></div><div class="ps3-actions"><button data-dest="food" class="${target==='food'?'active':''}" aria-label="นำทางไปร้านอาหารสัตว์">🥫</button><button data-dest="fashion" class="${target==='fashion'?'active':''}" aria-label="นำทางไปร้านแฟชั่น">🎀</button><button class="ps3-music" aria-label="เปิดหรือปิดเพลงในรถ">🎵</button><button data-exit="1" class="ps3-exit" aria-label="ออกจากโลก">✕ <span>ออก</span></button></div></div>
      <div class="ps3-windshield" aria-hidden="true"><div class="ps3-visor"></div><div class="ps3-wiper"></div><i class="ps3-turn-glow left"></i><i class="ps3-turn-glow right"></i></div>
      <div class="ps3-mirror ps3-mirror-l"></div><div class="ps3-mirror ps3-mirror-rear"></div><div class="ps3-mirror ps3-mirror-r"></div>
      <div class="ps3-cardash"></div><canvas class="ps3-cargauge"></canvas><div class="ps3-carwheel"></div>
      <button class="ps3-radio-screen" type="button" aria-pressed="true"><canvas></canvas><span class="ps3-radio-hint"></span></button><div class="ps3-radio-list"></div>
      <div class="ps3-pet">${petVisual()}<small>น้องนั่งด้วย 🐾</small></div>
      <div class="ps3-tools"><button class="ps3-cam" type="button">👁️ <span>มุมกล้อง</span></button><button class="ps3-seat" type="button">🎚️ <span>มุมนั่ง</span></button><button class="ps3-wiper-btn" type="button">🌧️ <span>ที่ปัดน้ำฝน</span></button><button class="ps3-visor-btn" type="button">🕶️ <span>ม่านบังแดด</span></button></div>
      <div class="ps3-steerpad" aria-label="พวงมาลัย ลากซ้ายขวา"><span>◀</span><i></i><span>▶</span></div>
      <button class="ps3-gaspad" type="button"><span>▲</span><small>เร่ง</small></button><button class="ps3-brakepad" type="button"><span>■</span><small>เบรก</small></button>
      <button class="ps3-geard" type="button">D<small>เดินหน้า</small></button><button class="ps3-gearr" type="button">R<small>ถอยหลัง</small></button>
      <div class="ps3-turnpad"><span>⬅️</span><i></i><span>➡️</span></div><button class="ps3-horn" type="button">📯</button>
      <div class="ps3-warning"></div><button class="ps3-store">เข้าร้าน</button><div class="ps3-help">W เร่ง · Space เบรก · A/D เลี้ยว · R เกียร์ · Z/C ไฟเลี้ยว · V กล้อง · H แตร · M เพลง${rental?' · รถเช่ารอบนี้':''}</div>
      <div class="ps3-carstart"><h3>🚗 เตรียมออกรถ</h3><div class="cs-row"><span>🔑 <b>สตาร์ทเครื่องยนต์</b><small>เครื่องไม่ติด รถออกไม่ได้นะ</small></span><button class="cs-engine" type="button"><i></i><b>ปิด</b></button></div><div class="cs-row"><span>🔒 <b>คาดเข็มขัดนิรภัย</b><small>ปลอดภัย + ไม่โดนใบสั่ง ม.123</small></span><button class="cs-belt" type="button"><i></i><b>ปิด</b></button></div><button class="cs-go" type="button" disabled>🚗 ออกรถ!</button></div>
      <div class="ps3-law"></div>`);
    gpsEl=root.querySelector('.ps3-gps span:not(.ps3-gps-icon)');storeBtn=root.querySelector('.ps3-store');dashEl=root.querySelector('.ps3-cardash');wheelEl=root.querySelector('.ps3-carwheel');gaugeEl=root.querySelector('.ps3-cargauge');gaugeCtx=gaugeEl.getContext('2d');petEl=root.querySelector('.ps3-pet');speedEl=null;radioEl=root.querySelector('.ps3-radio-screen');radioVizEl=radioEl.querySelector('canvas');radioVizCtx=radioVizEl.getContext('2d');radioListEl=root.querySelector('.ps3-radio-list');steerHitEl=root.querySelector('.ps3-steerpad');steerKnobEl=steerHitEl.querySelector('i');throttleEl=root.querySelector('.ps3-gaspad');brakeEl=root.querySelector('.ps3-brakepad');gearDEl=root.querySelector('.ps3-geard');gearREl=root.querySelector('.ps3-gearr');hornEl=root.querySelector('.ps3-horn');turnEl=root.querySelector('.ps3-turnpad');turnDotEl=turnEl.querySelector('i');mirrorLEl=root.querySelector('.ps3-mirror-l');mirrorRearEl=root.querySelector('.ps3-mirror-rear');mirrorREl=root.querySelector('.ps3-mirror-r');engineEl=root.querySelector('.cs-engine');beltEl=root.querySelector('.cs-belt');goEl=root.querySelector('.cs-go');startEl=root.querySelector('.ps3-carstart');lawEl=root.querySelector('.ps3-law');camEl=root.querySelector('.ps3-cam');seatEl=root.querySelector('.ps3-seat');wiperEl=root.querySelector('.ps3-wiper-btn');visorEl=root.querySelector('.ps3-visor-btn');warningEl=root.querySelector('.ps3-warning');syncGearUi();loadCarCockpit();radioState();
  }
  function bind(){
    listen(root,'scroll',()=>{if(root.scrollTop||root.scrollLeft){root.scrollTop=0;root.scrollLeft=0;}},{passive:true});
    [engineEl,beltEl,goEl].forEach(btn=>listen(btn,'pointerdown',e=>e.preventDefault()));
    const pinView=()=>{const reset=()=>{if(!root)return;const a=document.activeElement;if(a&&a.blur)a.blur();root.scrollTop=root.scrollLeft=0;window.scrollTo(0,0);};reset();requestAnimationFrame(reset);setTimeout(reset,60);};
    listen(window,'keydown',e=>{if(!keys[e.code]){if(e.code==='KeyM'&&typeof Music!=='undefined'){Music.toggleCar();radioState();}if(e.code==='KeyH'){sndKick();CarSnd.horn();}if(e.code==='KeyR')setGear(!gearR);if(e.code==='KeyV')toggleCamera();if(e.code==='KeyZ')turnSet(turnSig===1?0:1);if(e.code==='KeyC')turnSet(turnSig===2?0:2);}keys[e.code]=true;if(e.code==='Escape')exit();if(e.code==='ArrowDown'||e.code==='KeyS')kBack=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();});listen(window,'keyup',e=>{keys[e.code]=false;if(e.code==='ArrowDown'||e.code==='KeyS')kBack=false;});listen(window,'resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);radioLayout();});
    root.querySelectorAll('[data-dest]').forEach(b=>listen(b,'click',()=>{target=b.dataset.dest;rebuildRoute();root.querySelector('.ps3-gps b').textContent=`GPS · ${target==='food'?'ร้านอาหารสัตว์':'ร้านแฟชั่นสัตว์เลี้ยง'}`;root.querySelectorAll('[data-dest]').forEach(x=>x.classList.toggle('active',x===b));}));
    listen(root.querySelector('.ps3-music'),'click',()=>{if(typeof Music==='undefined'||!Music.ready()){toast('🎵 ยังไม่มีไฟล์เพลงในรถ');return;}Music.toggleCar();if(!Music.isCarOn())radioListEl.style.display='none';radioState();});
    listen(radioEl,'click',()=>{if(typeof Music==='undefined'||!Music.ready()){toast('🎵 ยังไม่มีไฟล์เพลงในรถ');return;}if(!Music.isCarOn()){Music.carRadio(true);radioState();}else radioToggle();});listen(radioListEl,'click',e=>{const tr=e.target.closest('.rl-track');if(tr){Music.playCar(+tr.dataset.i);renderRadioList();return;}const md=e.target.closest('.rl-mode');if(md){Music.setMode(md.dataset.m);renderRadioList();return;}if(e.target.closest('.rl-power')){Music.carRadio(false);radioListEl.style.display='none';radioState();return;}if(e.target.closest('.rl-x'))radioListEl.style.display='none';});
    listen(root.querySelector('[data-exit]'),'click',exit);listen(storeBtn,'click',openShop);
    const thrOn=e=>{e.preventDefault();padThr=true;throttleEl.classList.add('on');sndKick();},thrOff=()=>{padThr=false;throttleEl.classList.remove('on');};listen(throttleEl,'pointerdown',thrOn);['pointerup','pointercancel','pointerleave'].forEach(x=>listen(throttleEl,x,thrOff));
    const brOn=e=>{e.preventDefault();padBr=true;brakeEl.classList.add('on');sndKick();},brOff=()=>{padBr=false;brakeEl.classList.remove('on');};listen(brakeEl,'pointerdown',brOn);['pointerup','pointercancel','pointerleave'].forEach(x=>listen(brakeEl,x,brOff));listen(gearDEl,'click',e=>{e.preventDefault();setGear(false);});listen(gearREl,'click',e=>{e.preventDefault();setGear(true);});listen(hornEl,'pointerdown',e=>{e.preventDefault();sndKick();CarSnd.horn();});
    let sliding=false;const setSteer=e=>{const r=steerHitEl.getBoundingClientRect();steerCtl=Math.max(-1,Math.min(1,(((e.clientX-r.left)/r.width)*2-1)*1.25));steerKnobEl.style.left=(50+steerCtl*36)+'%';};listen(steerHitEl,'pointerdown',e=>{e.preventDefault();sliding=true;steerHitEl.classList.add('on');try{steerHitEl.setPointerCapture(e.pointerId);}catch(err){}setSteer(e);});listen(steerHitEl,'pointermove',e=>{if(sliding)setSteer(e);});const steerEnd=()=>{sliding=false;steerCtl=0;steerHitEl.classList.remove('on');steerKnobEl.style.left='50%';};listen(steerHitEl,'pointerup',steerEnd);listen(steerHitEl,'pointercancel',steerEnd);
    let turning=false,turnV=0;const turnFrom=e=>{const r=turnEl.getBoundingClientRect();turnV=Math.max(-1,Math.min(1,(((e.clientY-r.top)/r.height)*2-1)*1.25));turnDotEl.style.top=(50+turnV*33)+'%';};listen(turnEl,'pointerdown',e=>{e.preventDefault();turning=true;turnEl.classList.add('on');turnFrom(e);try{turnEl.setPointerCapture(e.pointerId);}catch(err){}});listen(turnEl,'pointermove',e=>{if(turning)turnFrom(e);});const turnEnd=()=>{if(!turning)return;turning=false;turnEl.classList.remove('on');turnSet(turnV<-.35?1:turnV>.35?2:0);};listen(turnEl,'pointerup',turnEnd);listen(turnEl,'pointercancel',turnEnd);
    listen(engineEl,'click',()=>{carEngineOn=!carEngineOn;updateSwitch(engineEl,carEngineOn);if(carEngineOn)CarSnd.ignite();else CarSnd.stop();goEl.disabled=!carEngineOn;pinView();});listen(beltEl,'click',()=>{carBelted=!carBelted;updateSwitch(beltEl,carBelted);if(carBelted)CarSnd.beltClick();pinView();});listen(goEl,'click',()=>{if(!carEngineOn)return;const go=()=>{carStartOpen=false;startEl.style.display='none';pinView();};if(carBelted)go();else showLaw(true,go);});
    listen(camEl,'click',toggleCamera);listen(seatEl,'click',()=>{seatLevel=(seatLevel+1)%3;seatEl.classList.toggle('on',seatLevel!==0);seatEl.querySelector('span').textContent=['มุมนั่ง','นั่งสูง','นั่งต่ำ'][seatLevel];});listen(wiperEl,'click',()=>{wiperOn=!wiperOn;root.classList.toggle('wiper-on',wiperOn);wiperEl.classList.toggle('on',wiperOn);});listen(visorEl,'click',()=>{visorOn=!visorOn;root.classList.toggle('visor-on',visorOn);visorEl.classList.toggle('on',visorOn);});
  }
  function toggleCamera(){cam3=!cam3;root.classList.toggle('cam3',cam3);camEl&&camEl.classList.toggle('on',cam3);if(carMesh)carMesh.visible=cam3;radioLayout();}
  function openShop(){if(paused)return;const p=STORE_POS[target],d=Math.hypot(car.x-p.x,car.z-p.z);if(d>27)return;paused=true;car.speed=dSpeed=dVelX=dVelZ=0;PetPantry.openStore(target,{onClose(){paused=false;}});}
  function navText(dist){if(dist<27)return 'ถึงร้านแล้ว · จอดรถแล้วกด “เข้าร้าน”';const p=STORE_POS[target],dx=p.x-car.x,dz=p.z-car.z;const ang=Math.atan2(dx,dz)-car.yaw,turn=Math.sin(ang)>0?'เลี้ยวซ้าย':'เลี้ยวขวา';return dist>55?`ตรงไป ${Math.round(dist-25)} ม. แล้ว${turn}`:`อีก ${Math.round(dist)} ม. · เตรียม${turn}`;}
  function carDrive(dt,now){
    let sd=steerCtl;if(!!(keys.ArrowLeft||keys.KeyA)!==!!(keys.ArrowRight||keys.KeyD))sd=(keys.ArrowRight||keys.KeyD)?1:-1;let th=0;if(padThr||keys.ArrowUp||keys.KeyW)th=gearR?-1:1;if(kBack)th=-1;if(padBr||keys.Space)th=0;
    if(!carEngineOn||carStartOpen)th=0;
    if(carEngineOn&&!carStartOpen&&(gearR||dSpeed<-.5)&&now-carRevBeepAt>600){carRevBeepAt=now;CarSnd.revBeep();}const road=onRoad(car.x,car.z),vmax=road?CAR_VMAX:CAR_VMAX_OFF;if(th>0)dSpeed+=CAR_ACCEL*(road?1:.55)*th*dt;else if(th<0){if(dSpeed>.3)dSpeed=Math.max(0,dSpeed-CAR_BRAKE*dt);else dSpeed=Math.max(-CAR_VREV,dSpeed+CAR_ACCEL*.7*th*dt);}if(padBr||keys.Space)dSpeed=dSpeed>0?Math.max(0,dSpeed-CAR_BRAKE*1.2*dt):Math.min(0,dSpeed+CAR_BRAKE*1.2*dt);dSpeed*=Math.max(0,1-(road?.16:1.15)*dt);if(dSpeed>vmax)dSpeed=Math.max(vmax,dSpeed-CAR_BRAKE*.8*dt);
    const tgt=sd*CAR_STEER_MAX/(1+Math.abs(dSpeed)*.045),ramp=Math.abs(tgt)>Math.abs(dSteer)?3.8:6;dSteer+=(tgt-dSteer)*Math.min(1,dt*ramp);const yawRate=(dSpeed/CAR_WB)*Math.tan(dSteer),maxYaw=1.9/(1+Math.abs(dSpeed)*.06),yrApplied=Math.max(-maxYaw,Math.min(maxYaw,yawRate));car.yaw-=yrApplied*dt;const sin=Math.sin(car.yaw),cos=Math.cos(car.yaw),grip=Math.min(1,dt*(6.5-Math.min(3.8,Math.abs(dSteer)*Math.abs(dSpeed)*.38)));dVelX+=(sin*dSpeed-dVelX)*grip;dVelZ+=(cos*dSpeed-dVelZ)*grip;const prevX=car.x,prevZ=car.z,hitSpd=Math.hypot(dVelX,dVelZ);car.x+=dVelX*dt;car.z+=dVelZ*dt;car.x=Math.max(-DRIVE_LIMIT,Math.min(DRIVE_LIMIT,car.x));car.z=Math.max(-DRIVE_LIMIT-55,Math.min(DRIVE_LIMIT-55,car.z));if(hitsSolid(car.x,car.z)){car.x=prevX;car.z=prevZ;dVelX*=.12;dVelZ*=.12;dSpeed*=.12;if(now-collisionAt>900){collisionAt=now;CarSnd.thud();if(hitSpd>7&&carFines.filter(f=>f.t==='crash').length<3){carFines.push({t:'crash',fine:CAR_REPAIR_FEE});warningEl.innerHTML=`🔧 รถชนแรง! ค่าซ่อม 🪙${CAR_REPAIR_FEE}`;warningEl.classList.add('show');setTimeout(()=>warningEl&&warningEl.classList.remove('show'),2200);}if((typeof state==='undefined'||state.haptic!==false)&&navigator.vibrate)navigator.vibrate(35);}}const vlen=Math.hypot(dVelX,dVelZ),slip=(vlen>.6&&road)?Math.abs(dVelX*cos-dVelZ*sin):0;CarSnd.setSkid(Math.max(0,Math.min(1,(slip-1.6)/6)));const latA=yrApplied*dSpeed,sdt=Math.min(dt,.05),rollTgt=Math.max(-CAR_ROLL_MAX,Math.min(CAR_ROLL_MAX,latA*CAR_ROLL_GAIN));dRollV+=((rollTgt-dRoll)*CAR_ROLL_SPRING-dRollV*CAR_ROLL_DAMP)*sdt;dRoll+=dRollV*sdt;car.speed=Math.abs(dSpeed);car.steer=sd;if(wheelEl)wheelEl.style.transform=`translateX(-50%) rotate(${(dSteer*440).toFixed(1)}deg)`;turnTick(now);CarSnd.update(th,car.speed,dt);
    const kmh=Math.abs(dSpeed)*3.6;if(kmh>CAR_LEGAL_KMH){if(!carOverSpeed&&carFines.filter(f=>f.t==='speed').length<5)carFines.push({t:'speed',fine:CAR_FINE_SPEED});carOverSpeed=true;warningEl.innerHTML=`🚨 เร็วเกิน ${CAR_LEGAL_KMH} กม./ชม. · ใบสั่ง ${carFines.filter(f=>f.t==='speed').length} ใบ`;warningEl.classList.add('show');}else if(kmh<CAR_LEGAL_KMH-5){carOverSpeed=false;if(!warningEl.textContent.includes('รถชน'))warningEl.classList.remove('show');}
    if(!carBelted&&!carBeltFined&&kmh>10&&carEngineOn&&!carStartOpen){carBeltFined=true;carFines.push({t:'belt',fine:CAR_FINE_BELT});if(typeof state!=='undefined'){state.coins=Math.max(0,(state.coins||0)-CAR_FINE_BELT);if(typeof saveState==='function')saveState();}showLaw(true);}
  }
  function tick(t){if(!running)return;raf=requestAnimationFrame(tick);const dt=Math.min(.04,(t-last)/1000||.016);last=t;if(!paused)carDrive(dt,t);dCamYaw+=(car.yaw-dCamYaw)*Math.min(1,dt*6.5);
    const seatY=[0,.18,-.12][seatLevel]||0;if(cam3){if(carMesh){carMesh.position.set(car.x,0,car.z);carMesh.rotation.y=car.yaw;carMesh.rotation.z=dRoll;(carMesh.userData.wheels||[]).forEach(w=>w.rotation.x-=dSpeed*dt/.5);}camera.position.set(car.x-Math.sin(dCamYaw)*7.4,3.15,car.z-Math.cos(dCamYaw)*7.4);camera.lookAt(car.x,1.65,car.z);}else{camera.position.set(car.x,CAR_EYE+seatY+Math.sin(t/110)*Math.min(.009,Math.abs(dSpeed)*.00045),car.z);camera.rotation.set(-.008,dCamYaw-Math.PI,-dRoll*.65,'YXZ');}const p=STORE_POS[target],dist=Math.hypot(car.x-p.x,car.z-p.z);gpsEl.textContent=navText(dist);storeBtn.classList.toggle('show',dist<27);renderer.render(scene,camera);drawCarGauges();drawRadioViz();drawMirrors();
  }
  function start(opt={}){if(running||!window.THREE||!document.body)return false;target=opt.target==='fashion'?'fashion':'food';carId=/^car_\d+$/.test(opt.carId||'')?opt.carId:'car_01';car={x:0,z:18,yaw:Math.PI,speed:0,steer:0};keys={};steerCtl=0;padThr=padBr=gearR=kBack=false;dSpeed=dSteer=dVelX=dVelZ=dRoll=dRollV=0;dCamYaw=car.yaw;carRevBeepAt=collisionAt=0;carEngineOn=carBelted=carBeltFined=carOverSpeed=false;carStartOpen=true;carFines=[];turnSet(0);cam3=false;seatLevel=0;root=document.createElement('div');root.className='ps3-root';document.body.appendChild(root);try{buildScene();carMesh=makeDriverCar();buildHUD(!!opt.rental);bind();if(typeof Music!=='undefined'){Music.suspendBg();Music.carRadio(true);radioState();}running=true;last=performance.now();raf=requestAnimationFrame(tick);return true;}catch(e){console.error(e);cleanup();return false;}}
  function settleFines(){const due=carFines.filter(f=>f.t!=='belt').reduce((s,f)=>s+f.fine,0);if(due&&typeof state!=='undefined'){state.coins=Math.max(0,(state.coins||0)-due);if(typeof saveState==='function')saveState();if(typeof toast==='function')setTimeout(()=>toast(`🚔 สรุปใบสั่ง/ค่าซ่อมรอบนี้ 🪙${due}`),180);}carFines=[];}
  function cleanup(){cancelAnimationFrame(raf);listeners.splice(0).forEach(fn=>fn());CarSnd.stop();if(typeof Music!=='undefined'){Music.carRadio(false);Music.resumeBg();}if(scene)scene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){const a=Array.isArray(o.material)?o.material:[o.material];a.forEach(m=>m.dispose&&m.dispose());}});disposables.splice(0).forEach(x=>x&&x.dispose&&x.dispose());if(renderer){renderer.dispose();renderer.forceContextLoss&&renderer.forceContextLoss();}if(root)root.remove();root=scene=camera=renderer=routeLine=null;storeBtn=gpsEl=wheelEl=petEl=speedEl=radioEl=steerHitEl=steerKnobEl=throttleEl=brakeEl=gearDEl=gearREl=hornEl=turnEl=turnDotEl=dashEl=dashImgEl=gaugeEl=gaugeCtx=radioListEl=radioVizEl=radioVizCtx=mirrorRearEl=mirrorLEl=mirrorREl=engineEl=beltEl=goEl=startEl=lawEl=camEl=seatEl=wiperEl=visorEl=warningEl=carMesh=null;mirrorRearCam=mirrorLCam=mirrorRCam=null;running=paused=false;keys={};padThr=padBr=kBack=false;}
  function exit(){if(!running)return;settleFines();cleanup();if(typeof renderDashboard==='function')renderDashboard();}
  return {start,exit,isRunning:()=>running,_t:{routeFor,STORE_POS,WORLD_HALF,DRIVE_LIMIT,hitsSolid,setPose(x,z,yaw=car.yaw){car.x=x;car.z=z;car.yaw=yaw;dSpeed=dVelX=dVelZ=0;},setSafety(engine,belt){carEngineOn=!!engine;carBelted=!!belt;carStartOpen=!engine;},get solids(){return {rects:solidRects.length,circles:solidCircles.length};},get driveState(){return {x:car.x,z:car.z,speed:dSpeed,steer:dSteer,gearR,engine:carEngineOn,belt:carBelted,cam3,turnSig};},get cleanupState(){return {running,paused,listeners:listeners.length};}}};
})();
