"use strict";
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('js/frontline1944.js','utf8');
const css=fs.readFileSync('css/frontline1944.css','utf8');
const html=fs.readFileSync('index_classic.html','utf8');
const f1=fs.readFileSync('js/data/f1_vocab.js','utf8');
assert(html.includes('id="btn-rail-frontline1944"')&&html.includes('hidden')&&html.includes('ADMIN PREVIEW'),'Frontline lobby entry is hidden-by-default admin preview');
assert(html.includes("link.href='css/frontline1944.css'")&&html.includes("s.src='js/frontline1944.js'")&&html.includes("if(loaded||!allowed())return"),'Frontline assets are admin-gated and lazy-fetched');
assert(!html.includes('<link rel="stylesheet" href="css/frontline1944.css"')&&!html.includes('<script src="js/frontline1944.js"'),'public lobby does not statically fetch Frontline assets');
assert(code.includes("const fns=['adminAllowed','isAdmin','canAccessAdmin']")&&code.includes('return false; // fail closed'),'access guard fails closed and reuses existing admin symbols instead of profile/email inference');
assert(!/email\s*[=!]=|@gmail|ADMIN_EMAIL/i.test(code),'Frontline does not create a parallel email allowlist');
assert(code.includes("typeof f1VocabForStudent==='function'")&&code.includes("typeof vocabForStudent==='function'"),'shared vocabulary adapters are reused');
assert(!code.includes('APPLE')&&!code.includes('BANANA'),'no sample vocabulary is hard-coded into the game');
assert(code.includes('letterCoins:1,wordBonus:50'),'reward values are centralized and conservative');
assert(code.includes("claim(id,CFG.letterCoins)")&&code.includes("claim(bid,CFG.wordBonus)"),'letter and word payouts go through duplicate-safe claims');
assert(code.includes("typeof addCoins==='function'")&&code.includes("typeof saveState==='function'")&&code.includes("typeof authPushSave==='function'"),'existing economy/save/cloud path is reused');
assert(code.includes('renderOrder=6')&&code.includes('userData.occluder=true')&&code.includes('renderOrder=5'),'foreground canopy and actor layers have explicit depth ownership');
assert(code.includes('new THREE.OrthographicCamera')&&code.includes('FogExp2'),'elevated orthographic 2.5D camera and atmospheric depth exist');
assert(code.includes('activateNextFortress()')&&code.includes("state:'dormant'")&&code.includes("state='boss'")&&code.includes("state='core'")&&code.includes("state='destroyed'"),'fortress loop includes defenders, boss, vulnerable core and endless next objective');
assert(code.includes('enemyCap:10')&&code.includes('projectileCap:48')&&code.includes('fxCap:72'),'mobile active-object caps are explicit');
assert(code.includes('renderer.setPixelRatio(Math.min(devicePixelRatio||1,CFG.dpr))'),'mobile DPR is capped');
assert(css.includes('@media (max-height:460px)')&&css.includes('touch-action:none'),'short landscape and touch control styling exist');
const sb={console,state:{student:{grade:'ป.1'}}};sb.window=sb;vm.createContext(sb);vm.runInContext(f1,sb);
assert.strictEqual(typeof sb.f1VocabForStudent,'function','authoritative shooter vocabulary provider exists');
const grades=['ป.1','ป.2','ป.3','ป.4','ป.5','ป.6'],counts={};
for(const grade of grades){sb.state.student.grade=grade;const raw=sb.f1VocabForStudent()||[];const words=raw.map(x=>Array.isArray(x)?x[0]:x&&(x.en||x.word||x.eng||x.english)).filter(Boolean).map(x=>String(x).trim().toUpperCase());counts[grade]={count:words.length,unique:new Set(words).size};assert(words.length>0,grade+' vocabulary source must not be empty');assert.strictEqual(counts[grade].count,counts[grade].unique,grade+' vocabulary must not duplicate English targets in the shooter pool');}
console.log('Frontline vocabulary audit P.1-P.6:',JSON.stringify(counts));
console.log('PASS Frontline 1944: admin fail-closed, shared vocab, economy reuse, layered 2.5D occlusion, boss fortress loop, endless continuation and mobile caps');
