'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),vm=require('vm');
const repo=path.resolve(__dirname,'..'),root=path.resolve(process.env.VW_ARENA_SOURCE||repo),out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-elements');fs.mkdirSync(out,{recursive:true});
const deps=process.env.VW_NODE_DEPS||path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'),{chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp')),THREE=require(path.join(repo,'js/vendor/three.min.js'));
const checks=[],ok=(name,v)=>{assert.ok(v,name);checks.push(name);};
const context={window:{},performance,THREE};vm.runInNewContext(fs.readFileSync(path.join(root,'js/arena-elements.js'),'utf8'),context);const E=context.window.ArenaElements;
function system(){const b={group:{position:new THREE.Vector3(0,0,3)},hp:10000,boss:false,slow:0,dead:false};let damage=0,heal=0,guard=0;const fx={element:()=>({move(){}}),burst(){}};const engine=E.create({enemies:()=>[b],fx,hit:(b,n)=>{damage+=n;b.hp-=n;},heal:(h,s)=>{heal+=h;guard+=s;},storm:()=>false});return {b,engine,get damage(){return damage},get heal(){return heal},get guard(){return guard}};}
for(const kind of ['fire','wind','ice','meteor','earth','gravity','water','light']){const s=system(),origin=new THREE.Vector3(),direction=new THREE.Vector3(0,0,1);s.engine.cast(kind,origin,direction,s.b,1);for(let i=0;i<50;i++)s.engine.tick(.1);if(kind==='light')ok('light heals 30 and guards 20',s.heal===30&&s.guard===20);else ok(kind+' causes actual damage',s.damage>0);if(kind==='fire')ok('fire six periodic hits',s.damage===90);if(kind==='meteor')ok('all three meteors hit',s.damage===144);if(kind==='water')ok('water hits each enemy once',s.damage===48);if(kind==='ice')ok('ice applies slow',s.b.slow>performance.now());if(kind==='gravity')ok('gravity ends with collapse',s.damage===110);ok(kind+' expires gameplay zone',s.engine.stats().active===0);}
const cap=system();for(let i=0;i<30;i++)cap.engine.cast('fire',new THREE.Vector3(),new THREE.Vector3(0,0,1),cap.b,1);ok('gameplay zones bounded at 12',cap.engine.stats().active===12);cap.engine.clear();ok('clear removes elemental zones',cap.engine.stats().active===0);ok('loadout sanitizer prevents duplicates',new Set(E.normalizeSlots(['fire','fire'])).size===2);
const harness=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"></head><body><script>window.state=JSON.parse(localStorage.getItem('elementTest')||'null')||{profileName:'admin',coins:1000,arenaIntro:true,arenaHomeIntro:true,arenaItems:{},sound:false};window.isAdmin=()=>true;window.saveState=()=>localStorage.setItem('elementTest',JSON.stringify(state));window.addCoins=n=>state.coins+=n;window.vocabForStudent=()=>[['cat','แมว']];window.activePet=()=>null;window.toast=()=>{};</script><script src="/js/vendor/three.min.js"></script><script src="/js/arena-field-visuals.js"></script><script src="/js/arena-elements.js"></script><script src="/js/arena-heroes.js"></script><script src="/js/arena3d.js"></script></body></html>`;
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/test'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(harness);}const file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:812,height:375},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(`http://127.0.0.1:${server.address().port}/test`);await page.evaluate(()=>{VocabArena3D.start();const t=VocabArena3D._t;t.player().pos.set(0,0,0);t.bots.forEach((b,i)=>{b.group.position.set((i%3-1)*3,0,-4-Math.floor(i/3)*2);b.hp=b.maxHp=10000;b.attackAt=performance.now()+60000;});});await page.waitForTimeout(1000);
 ok('HP above self and eight enemies',await page.locator('.va-vital').count()===9);
 await page.evaluate(()=>{VocabArena3D._t.damage(13);VocabArena3D._t.frame(16);});await page.waitForFunction(()=>document.querySelector('.va-vital.self b').textContent==='87 / 100');ok('player hit updates overhead numeric HP',await page.locator('.va-vital.self b').innerText()==='87 / 100');const number=page.locator('.va-damage-number').filter({hasText:'−13'}).first();const before=await number.evaluate(el=>({y:el.getBoundingClientRect().y,opacity:Number(el.style.opacity)}));await page.waitForTimeout(600);const after=await number.evaluate(el=>({y:el.getBoundingClientRect().y,opacity:Number(el.style.opacity)}));ok('damage rises and evaporates',after.y<before.y&&after.opacity<before.opacity);await page.waitForTimeout(650);ok('expired damage number removed',await number.count()===0);
 for(const [w,h] of [[812,375],[667,320],[1366,768]]){await page.setViewportSize({width:w,height:h});await page.locator('#va-spells-open').tap();ok('all ten spell choices '+w,await page.locator('[data-equip-spell]').count()===10);ok('library fits without scrolling '+w,await page.evaluate(()=>{const e=document.querySelector('.va-spell-panel'),r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&e.scrollHeight<=e.clientHeight&&[...e.querySelectorAll('button')].every(b=>b.scrollWidth<=b.clientWidth+1);}));const n=await page.evaluate(()=>VocabArena3D._t.elementStats().active);await page.keyboard.press('Digit1');ok('picker blocks combat '+w,await page.evaluate(n=>VocabArena3D._t.elementStats().active===n,n));if(w===812)await sharp(await page.screenshot()).webp({quality:93}).toFile(path.join(out,'elements-library.webp'));await page.locator('#va-spells-close').tap();}
 await page.setViewportSize({width:812,height:375});await page.evaluate(()=>{const t=VocabArena3D._t;t.equip(0,'fire');t.equip(1,'wind');t.cast('fire');});const cd=await page.evaluate(()=>VocabArena3D._t.cooldowns.fire);await page.evaluate(()=>{const t=VocabArena3D._t;t.equip(0,'ice');t.equip(0,'fire');t.cast('fire');});ok('switching cannot reset fire cooldown',await page.evaluate(cd=>VocabArena3D._t.cooldowns.fire===cd,cd));
 await page.evaluate(()=>{VocabArena3D._t.equip(1,'gravity');VocabArena3D.stop();});await page.reload();await page.evaluate(()=>VocabArena3D.start());ok('equipped elements survive reload',await page.evaluate(()=>VocabArena3D._t.slots.join(',')==='fire,gravity'));
 const costs={};for(const kind of ['fire','wind','ice','meteor','earth','gravity','water','light']){
  await page.evaluate(kind=>{VocabArena3D.stop();VocabArena3D.start();const t=VocabArena3D._t;t.player().pos.set(0,0,0);t.bots.forEach((b,i)=>{b.group.position.set((i%3-1)*3,0,-4-Math.floor(i/3)*2);b.hp=b.maxHp=80;b.group.position.x*=1.6;b.attackAt=performance.now()+60000;});t.equip(0,kind);},kind);await page.waitForTimeout(250);await page.keyboard.press('Digit1');await page.waitForTimeout(kind==='meteor'?280:kind==='wind'||kind==='fire'?900:380);ok(kind+' fires from equipped hotkey',await page.evaluate(kind=>VocabArena3D._t.cooldowns[kind]>performance.now(),kind));costs[kind]=await page.evaluate(()=>VocabArena3D._t.stats());await sharp(await page.screenshot()).webp({quality:93}).toFile(path.join(out,'element-'+kind+'.webp'));
 }
 await page.evaluate(()=>{const t=VocabArena3D._t;for(const kind of ['fire','wind','ice','meteor','earth','gravity','water'])t.cast(kind);});await page.waitForTimeout(500);ok('combined spells retain FX budget',await page.evaluate(()=>{const t=VocabArena3D._t;return t.stats().fx.active<=640&&t.stats().fx.meshes===48&&t.elementStats().active<=12;}));await page.evaluate(()=>{VocabArena3D.stop();VocabArena3D.start();});ok('reentry clears zones',await page.evaluate(()=>VocabArena3D._t.elementStats().active===0));await page.evaluate(()=>{VocabArena3D.stop();localStorage.removeItem('elementTest');});ok('zero runtime errors',errors.length===0);
 fs.writeFileSync(path.join(out,'elements-report.json'),JSON.stringify({checks,costs,errors},null,2));console.log(JSON.stringify({passed:checks.length,costs,errors,out},null,2));
}catch(e){console.error(e);console.error(errors);await sharp(await page.screenshot()).webp({quality:93}).toFile(path.join(out,'failure.webp'));process.exitCode=1;}finally{await browser.close();server.close();}})();
