'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(process.env.VW_ARENA_SOURCE||path.join(__dirname,'..')),repo=path.resolve(__dirname,'..'),out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-race');fs.mkdirSync(out,{recursive:true});
const deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'),{chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
const {createService,ROOT,HOMES}=require(path.join(repo,'functions/arena-race')),{memoryDatabase}=require(path.join(repo,'functions/test_frontline'));
const db=memoryDatabase(),service=createService(db,{newWord:round=>({round,target:round%2?'BOOK':'APPLE',translation:round%2?'หนังสือ':'แอปเปิล',completedAt:0,winnerId:''})}),roomPath=ROOT+'/rooms/r21';
const files=['vendor/three.min','arena-field-visuals','arena-elements','arena-spell-catalog','arena-strip','arena-grimoire','arena-relics','arena-heroes','arena-maps','arena-race','arena-nav','arena3d'];
const harness=id=>`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"></head><body><script>
window.state={profileName:'${id}',coins:1000,arenaHomeIntro:true,arenaItems:{},arenaHome:{letters:{Z:2},cargo:['A','B','C']},arenaHero:'fire',arenaMap:'sky',sound:false,haptic:false};window.isAdmin=()=>true;window.saveState=()=>localStorage.setItem('race-test-${id}',JSON.stringify(state));window.addCoins=n=>state.coins+=n;window.activePet=()=>null;window.vocabForStudent=()=>[['apple','แอปเปิล']];window.toast=()=>{};window.Online={ready:true,db:{}};window.onlineKey=()=>'${id}';window.firebase={auth:()=>({currentUser:{uid:'${id}',getIdToken:async()=>'${id}'}})};
window.NetRoom={create:opt=>{let joined=false;return {room:21,roomLabel:'1',get online(){return joined},get joined(){return joined},join(){joined=true;opt.push();},leave(){joined=false},send(p){return __presence(p);},tick(){},openFriends(){}}}};window.authPushSaveAwait=async()=>{await __save(JSON.stringify(state));return true;};
</script>${files.map(f=>'<script src="/js/'+f+'.js"></script>').join('')}</body></html>`;
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/test'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(harness(u.searchParams.get('id')||'p0'));}const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.avif')?'image/avif':f.endsWith('.webp')?'image/webp':'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge',args:['--disable-background-timer-throttling','--disable-renderer-backgrounding']}),pages=[],errors=[],checks=[];const ok=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS '+name);};
try{
 for(let i=0;i<2;i++){const id='p'+i,page=await browser.newPage({viewport:{width:812,height:375},hasTouch:true});pages.push(page);page.on('pageerror',e=>errors.push(id+':'+e.message));
  await page.exposeFunction('__presence',async p=>{db.values.set('wroom/adv/r21/'+id,{x:p.x,z:p.z,m:p.m});db.values.set('winfo/adv/r21/'+id,{h:p.hp,n:p.n,t:Date.now()});await Promise.all(pages.filter(q=>q!==page&&!q.isClosed()).map(q=>q.evaluate(([id,p])=>{if(window.VocabArena3D?._t.running)VocabArena3D._t.peer(id,p);},[id,p]).catch(()=>{})));});
  await page.exposeFunction('__save',async data=>{const old=db.values.get('users/'+id+'/save');if(!old)db.values.set('users/'+id+'/save',{data});else{const previous=JSON.parse(old.data),s=JSON.parse(data),receipts=s.arenaRaceReceipts||{};let delta=0;for(const [k,v]of Object.entries(previous.arenaRaceReceipts||{}))if(v>(receipts[k]||0)){delta+=v-(receipts[k]||0);receipts[k]=v;}s.coins+=delta;s.arenaRaceReceipts=receipts;db.values.set('users/'+id+'/save',{data:JSON.stringify(s)});}});
  await page.route('https://asia-southeast1-english-pet-game.cloudfunctions.net/arenaRaceV1',async route=>{try{const result=await service(route.request().postDataJSON().data,id);await route.fulfill({json:{result}});}catch(e){await route.fulfill({status:503,json:{error:{message:e.message}}});}});
  await page.goto(`http://127.0.0.1:${server.address().port}/test?id=${id}`);await page.evaluate(async()=>{await ArenaMaps.prepare('sky');VocabArena3D.start();});await page.waitForFunction(()=>VocabArena3D._t.race()?.ready);await page.evaluate(()=>{VocabArena3D._t.bots.forEach(b=>{b.attackAt=performance.now()+1e8;b.group.position.set(0,0,0);});});
 }
 const [a,b]=pages;
 await a.waitForFunction(()=>Object.keys(VocabArena3D._t.race().snapshot.bases).length===2);
 ok('two browsers receive same shared word',await a.locator('#va-word-en').innerText()===await b.locator('#va-word-en').innerText());
 ok('legacy solo inventory preserved but excluded from race',await a.evaluate(()=>state.arenaHome.cargo.join('')==='ABC'&&state.arenaHome.letters.Z===2&&Object.keys(VocabArena3D._t.bag).length===0));
 ok('26 shared A-Z items rendered',await a.evaluate(()=>VocabArena3D._t.drops.length===26));
 await a.evaluate(()=>{const t=VocabArena3D._t;t.player().pos.set(18,0,-18);t.resize();t.frame(16);});
 ok('needed letters use large HUD cards only',await a.evaluate(()=>{const t=VocabArena3D._t,left=ArenaNav.remain(t.target.en,t.bag,t.cargo);return Object.keys(left).length>0&&t.drops.every(d=>!d.spr||!d.spr.visible)&&document.querySelectorAll('.va-letter.needed').length>0;}));
 ok('edge arrows point at remaining letters and own home',await a.evaluate(()=>{const n=VocabArena3D._t.nav();return n.hints>=1&&n.home&&document.querySelector('.va-hint.home b').textContent==='บ้าน';}));
 async function position(page,x,z){await page.evaluate(([x,z])=>{VocabArena3D._t.player().pos.set(x,0,z);},[x,z]);await page.waitForTimeout(240);}
 async function pick(page,ch){const item=await page.evaluate(ch=>Object.entries(VocabArena3D._t.race().snapshot.items).find(([,x])=>x.ch===ch),ch);await position(page,item[1].x,item[1].z);await page.waitForFunction(ch=>VocabArena3D._t.cargo[0]===ch,ch);}
 async function bank(page){const pos=await page.evaluate(()=>{const p=VocabArena3D._t.home().position;return [p.x,p.z];});await position(page,...pos);await page.waitForFunction(()=>VocabArena3D._t.cargo.length===0);}
 await pick(a,'A');ok('cargo limit one even for admin relics',await a.evaluate(()=>VocabArena3D._t.relics().cargoMax===1&&VocabArena3D._t.cargo.length===1));
 const extra=await a.evaluate(()=>Object.values(VocabArena3D._t.race().snapshot.items).find(x=>x.ch==='P'));await position(a,extra.x,extra.z);
 await a.waitForFunction(()=>document.querySelector('#va-pop.on strong')?.textContent.includes('1 ตัว'));
 ok('full cargo explains one-letter limit',await a.evaluate(()=>VocabArena3D._t.cargo[0]==='A'&&[...document.querySelectorAll('.va-feed-line.bad')].some(n=>n.textContent.includes('เก็บได้ทีละ 1 ตัวอักษรเท่านั้น'))));
 await a.evaluate(()=>{const t=VocabArena3D._t;t.player().pos.set(18,0,-18);t.resize();t.frame(16);});
 ok('carrying shows only the home arrow',await a.evaluate(()=>{const n=VocabArena3D._t.nav();return VocabArena3D._t.cargo[0]==='A'&&n.hints===0&&n.home&&![...document.querySelectorAll('.va-hint:not(.home)')].some(el=>!el.hidden);}));
 await bank(a);
 for(const ch of ['P','P','L','E']){await pick(a,ch);await bank(a);}
 await a.waitForFunction(()=>state.coins===2000);ok('actual collect-bank loop pays exactly 1000',await a.evaluate(()=>state.coins===2000&&VocabArena3D._t.sessionCoins===1000));ok('other player receives no winner coins',await b.evaluate(()=>state.coins===1000));
 await a.waitForFunction(()=>VocabArena3D._t.target.en==='BOOK');await b.waitForFunction(()=>VocabArena3D._t.target.en==='BOOK');ok('both browsers advance to next shared word',true);
 await pick(b,'Z');await bank(b);const victim=db.values.get(roomPath).players.p1;victim.hp=250;victim.baseRevision++;
 await a.waitForFunction(()=>VocabArena3D._t.race().snapshot.bases.p1.hp===250);
 const spot=HOMES[victim.slot];await position(a,spot[0]-7,spot[1]);await a.evaluate(()=>{VocabArena3D._t.bots.forEach(b=>b.group.position.set(-26,0,-2));});await a.locator('[data-skill="basic"]').tap();await a.waitForFunction(()=>VocabArena3D._t.race().snapshot.bases.p1.hp===0);await b.waitForFunction(()=>VocabArena3D._t.race().snapshot.self.hp===0);
 ok('real attack breaks house and both screens show 0 HP',await b.locator('.va-vital.peer b').allTextContents().then(v=>v.includes('0 / 5000')));
 await position(a,...spot);await a.waitForFunction(()=>VocabArena3D._t.cargo[0]==='Z');await b.waitForFunction(()=>!VocabArena3D._t.bag.Z);ok('walk into ruined house steals one banked letter',true);
 await a.locator('#va-drop-letter').tap();await a.waitForFunction(()=>!VocabArena3D._t.cargo.length);ok('touch DROP releases letter',true);
 const metrics=await a.evaluate(()=>VocabArena3D._t.stats());
 for(const [width,height]of [[812,375],[667,320],[1366,768]]){await a.setViewportSize({width,height});await a.waitForTimeout(120);const fit=await a.evaluate(()=>['.va-word-card','.va-coins','#va-drop-letter','#va-home-nav','.va-skills'].map(s=>{const e=document.querySelector(s),r=e.getBoundingClientRect();return {s,fit:r.left>=0&&r.top>=0&&r.right<=innerWidth+.5&&r.bottom<=innerHeight+.5};}));ok('controls fit '+width+'x'+height,fit.every(x=>x.fit));ok('DROP does not overlap home '+width,await a.evaluate(()=>{const d=document.querySelector('#va-drop-letter').getBoundingClientRect(),h=document.querySelector('#va-home-nav').getBoundingClientRect();return d.bottom<=h.top||d.right<=h.left||d.left>=h.right;}));await sharp(await a.screenshot()).webp({quality:90}).toFile(path.join(out,'arena-race-'+width+'.webp'));}
 const before=await a.evaluate(()=>state.coins);await a.evaluate(()=>{VocabArena3D.stop();VocabArena3D.start();});await a.waitForFunction(()=>VocabArena3D._t.race()?.ready);await a.waitForTimeout(600);ok('re-entry keeps wallet and starts earned counter at zero',await a.evaluate(n=>state.coins===n&&VocabArena3D._t.sessionCoins===0,before));
 await Promise.all(pages.map(p=>p.evaluate(()=>VocabArena3D.stop())));ok('no browser errors',errors.length===0);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(JSON.stringify({passed:checks.length,metrics,out}));
}catch(e){console.error(e);console.error(errors);for(let i=0;i<pages.length;i++)await sharp(await pages[i].screenshot()).webp({quality:90}).toFile(path.join(out,'failure-'+i+'.webp'));process.exitCode=1;}finally{await browser.close();server.close();}})();
