/* รอบ 1235 — structural regression for additive Vocab Sky Playground Phase 5. */
"use strict";
const fs=require('fs'),path=require('path'),vm=require('vm'),root=path.resolve(__dirname,'..');
const sky=fs.readFileSync(path.join(root,'js/skyplay3d.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'js/ui.js'),'utf8');
const net=fs.readFileSync(path.join(root,'js/netroom.js'),'utf8');
const rules=fs.readFileSync(path.join(root,'handoff/RULES.md'),'utf8');
const html=fs.readFileSync(path.join(root,'index_classic.html'),'utf8');
const css=fs.readFileSync(path.join(root,'css/skyplay3d.css'),'utf8');
function ok(cond,msg){if(!cond)throw new Error(msg);console.log('PASS',msg);}
ok(/window\.SkyPlayground3D=\{start,stop,_t:/.test(sky),'engine exposes lifecycle and test hooks');
ok(/map:'sky',roomMax:ROOM_MAX/.test(sky)&&/const TAU=.*ROOM_MAX=6/.test(sky),'NetRoom instance is isolated and capped at 6');
const petBuild=sky.slice(sky.indexOf('function buildPet'),sky.indexOf('function bindInput'));
ok(/activePet/.test(sky)&&/petStage/.test(sky)&&/model=makePetChibi\(p\.type\)/.test(petBuild),'pet reuses active Lobby pet identity and growth stage in the procedural model');
ok(/function makePetChibi/.test(sky)&&/petStyle='soft-cuboid-chibi-3d'/.test(sky)&&!/new THREE\.Sprite/.test(petBuild),'dog, cat and dragon use procedural Soft Cuboid Chibi 3D instead of a billboard');
ok(/dog-curled-fluffy/.test(sky)&&/dog-tail-puff/.test(sky)&&/cat-upright-s-curve/.test(sky)&&/dragon-tapered-fin/.test(sky),'dog, cat and dragon have visibly species-specific curved tail silhouettes instead of one straight rod');
ok(/function addCurvedTail/.test(sky)&&/thickness=Math\.max\(\.085,\.2-i\*\.022\)/.test(sky)&&!/tailMesh=meshSoft\(\.18,\.18,\.6/.test(sky)&&/dragon-tail-fin-/.test(sky),'all tails are segmented, tapered and posed away from anatomy-like straight cylinders');
const humanBuild=sky.slice(sky.indexOf('function configurePlayerTexture'),sky.indexOf('function makePetChibi'));
const localPlayerBuild=sky.slice(sky.indexOf('function buildPlayer'),sky.indexOf('function buildPet')),peerPlayerBuild=sky.slice(sky.indexOf('function buildPeer'),sky.indexOf('function removePeer'));
const characterIds=['hoodie-red','explorer','captain','schoolgirl','witch','pajamas'];
const characterAssets=['sky_soft_cuboid_chibi_8dir.webp',...characterIds.slice(1).map(id=>`sky_soft_cuboid_chibi_${id}_8dir.webp`)];
const animationAssets=['sky_soft_cuboid_chibi_anim.webp',...characterIds.slice(1).map(id=>`sky_soft_cuboid_chibi_${id}_anim.webp`)];
const thumbnailAssets=['sky_soft_cuboid_chibi_thumb.webp',...characterIds.slice(1).map(id=>`sky_soft_cuboid_chibi_${id}_thumb.webp`)];
const atlases=characterAssets.map(file=>fs.readFileSync(path.join(root,'img/characters',file)));
const animations=animationAssets.map(file=>fs.readFileSync(path.join(root,'img/characters',file)));
const thumbnails=thumbnailAssets.map(file=>fs.readFileSync(path.join(root,'img/characters',file)));
ok(atlases.length===6&&atlases.every(atlas=>atlas.length>350000&&atlas.slice(0,4).toString()==='RIFF'&&atlas.slice(8,12).toString()==='WEBP'),'all six production 8-direction chibi atlases exist as substantial WebP assets');
ok(animations.length===6&&animations.every(atlas=>atlas.length>1000000&&atlas.slice(0,4).toString()==='RIFF'&&atlas.slice(8,12).toString()==='WEBP'),'all six separate idle/walk 8-direction animation atlases exist as substantial WebP assets');
ok(thumbnails.length===6&&thumbnails.every(thumb=>thumb.length>=5000&&thumb.length<=20000&&thumb.slice(0,4).toString()==='RIFF'&&thumb.slice(8,12).toString()==='WEBP')&&thumbnails.reduce((n,thumb)=>n+thumb.length,0)<100000,'all six picker thumbnails stay valid WebP and below the 100KB total budget');
ok(/const PLAYER_CHARACTERS=\[/.test(sky)&&characterIds.every(id=>sky.includes(`id:'${id}'`))&&thumbnailAssets.every(file=>sky.includes(`thumb:'img/characters/${file}'`)),'Sky exposes the locked six-character catalog with lightweight thumbnails');
ok(/new THREE\.Sprite\(new THREE\.SpriteMaterial/.test(humanBuild)&&/texLoader\.load\(character\.atlas\)/.test(humanBuild)&&/new THREE\.CanvasTexture\(cv\)/.test(humanBuild)&&/cv\.width=cv\.height=192/.test(humanBuild)&&/alphaTest:\.04/.test(humanBuild),'player shows the proven static atlas first, then uses a small transparent CanvasTexture for animation');
ok(/img\.onerror=.*renderMode='static-fallback'/.test(humanBuild)&&/img\.naturalWidth!==1536\|\|img\.naturalHeight!==1536/.test(humanBuild),'decode and atlas-size failures keep a visible static-character fallback');
ok(/sky-soft-cuboid-chibi-8dir-anim-canvas-v4/.test(humanBuild)&&/styleStandard='docs\/PLAYER_CHARACTER_STYLE\.md'/.test(humanBuild),'animated render assets declare the mandatory Soft Cuboid Chibi standard');
ok(/moving\?4\+Math\.floor\(t\*\.008\)%4:Math\.floor\(t\*\.004\)%4/.test(humanBuild)&&/drawImage\(img,animationFrame\*192,direction\*192,192,192,0,0,192,192\)/.test(humanBuild),'renderer crops 4-frame idle at 4 fps and 4-frame walk at 8 fps across all eight directions');
ok(/animate=!\(state&&state\.noAnim\)/.test(humanBuild)&&/animationFrame=animate\?/.test(humanBuild),'the existing no-animation setting freezes the baked atlas without a new preference');
const madeTextures=[],drawCalls=[];
function mockTexture(src){return {src,repeat:{set(x,y){this.x=x;this.y=y;}},offset:{set(x,y){this.x=x;this.y=y;}},dispose(){this.disposed=true;}};}
class MockCanvasTexture{constructor(canvas){Object.assign(this,mockTexture('canvas'));this.canvas=canvas;madeTextures.push(this);}}
class MockImage{set src(value){this.value=value;this.naturalWidth=MockImage.bad?100:1536;this.naturalHeight=MockImage.bad?100:1536;this.onload();}}
const loadCtx={Math,Image:MockImage,THREE:{ClampToEdgeWrapping:1,LinearFilter:2,SRGBColorSpace:3,CanvasTexture:MockCanvasTexture},document:{createElement:()=>({getContext:()=>({clearRect(){},drawImage(...args){drawCalls.push(args);}})})},texLoader:{load:mockTexture},playerCharacter:id=>({id,atlas:`${id}-static`,anim:`${id}-anim`})};
vm.runInNewContext(humanBuild+';this.setCharacter=setPlayerSpriteCharacter;',loadCtx);
const loadedSprite={material:{map:null,needsUpdate:false},userData:{}};loadCtx.setCharacter(loadedSprite,'hoodie-red');
ok(loadedSprite.userData.animationReady&&loadedSprite.userData.renderMode==='canvas-animation'&&loadedSprite.material.map.src==='canvas','valid animation decode replaces the visible static texture with a 192px CanvasTexture');
ok(drawCalls.length===1&&drawCalls[0][1]===0&&drawCalls[0][2]===0&&drawCalls[0][3]===192&&drawCalls[0][4]===192,'first canvas frame is drawn from the expected atlas cell with true-alpha clearing');
MockImage.bad=true;const fallbackSprite={material:{map:null,needsUpdate:false},userData:{}};loadCtx.setCharacter(fallbackSprite,'witch');
ok(fallbackSprite.material.map.src==='witch-static'&&fallbackSprite.userData.animationError&&fallbackSprite.userData.renderMode==='static-fallback','invalid animation decode leaves the original eight-direction character visible');
MockImage.bad=false;
ok(/fig=makePlayerSprite\(selectedCharacter\(\)\)/.test(localPlayerBuild)&&/fig=makePlayerSprite\(d\.sc\)/.test(peerPlayerBuild),'local player and every spawned online peer use the selected character renderer');
ok(/sc:selectedCharacter\(\)/.test(sky)&&/setPlayerSpriteCharacter\(a\.fig,d\.sc\)/.test(sky),'network payload sends the local choice and updates existing peers when their choice changes');
ok(/state\.skyCharacter=selectedCharacter\(\)/.test(sky)&&/state\.skyCharacter=character\.id/.test(sky)&&/authPushSave\(false\)/.test(sky),'character choice is sanitized, saved and cloud-synced');
ok(/id="sp-character-picker"/.test(sky)&&/data-character="\$\{c\.id\}"/.test(sky)&&/function openCharacterPicker/.test(sky)&&/function closeCharacterPicker/.test(sky),'six-character picker has explicit open, choose and close paths');
ok(!/makeDeprecatedPrimitiveChibi\(/.test(localPlayerBuild+peerPlayerBuild)&&!/makeChibi\(/.test(localPlayerBuild+peerPlayerBuild),'rejected primitive-human generator cannot be selected by local or peer spawn paths');
const directionSource=sky.slice(sky.indexOf('function playerDirectionFrame'),sky.indexOf('function updatePlayerSprite'));
const directionCtx={Math,camYaw:0};vm.runInNewContext(directionSource+';this.frame=playerDirectionFrame;',directionCtx);
const expected=[0,1,2,3,4,5,6,7],yaws=[Math.PI,3*Math.PI/4,Math.PI/2,Math.PI/4,0,-Math.PI/4,-Math.PI/2,-3*Math.PI/4];
ok(yaws.map(y=>directionCtx.frame(y)).every((frame,index)=>frame===expected[index]),'camera-relative yaw selects all eight atlas directions in canonical order');
const animationSource=sky.slice(sky.indexOf('function playerDirectionFrame'),sky.indexOf('function renderCharacterPicker'));
const animationCtx={Math,camYaw:0,state:{noAnim:false}};animationCtx.drawPlayerSpriteFrame=(sprite,direction,frame)=>{sprite.userData.drawn=[direction,frame];return true;};vm.runInNewContext(animationSource+';this.update=updatePlayerSprite;',animationCtx);
const spriteMock={material:{map:{offset:{set(x,y){this.x=x;this.y=y;}}},rotation:0},position:{y:0},userData:{direction:-1,animationFrame:-1,animationReady:false,animationError:false}};
animationCtx.update(spriteMock,Math.PI,0,false,false);
ok(spriteMock.userData.direction===0&&spriteMock.userData.animationFrame===0&&spriteMock.material.map.offset.x===0&&spriteMock.material.map.offset.y===.5,'static fallback selects front idle frame 0 from the proven 4x2 source atlas');
animationCtx.update(spriteMock,Math.PI/2,625,true,false);
ok(spriteMock.userData.direction===2&&spriteMock.userData.animationFrame===5&&spriteMock.material.map.offset.x===.5&&spriteMock.material.map.offset.y===.5,'static fallback follows all eight directions while animation decoding is pending');
spriteMock.userData.animationReady=true;animationCtx.update(spriteMock,Math.PI/4,750,true,false);
ok(spriteMock.userData.direction===3&&spriteMock.userData.animationFrame===6&&spriteMock.userData.drawn[0]===3&&spriteMock.userData.drawn[1]===6,'decoded CanvasTexture receives the expected direction and walk frame');
animationCtx.state.noAnim=true;animationCtx.update(spriteMock,0,9999,true,true);
ok(spriteMock.userData.animationFrame===0&&spriteMock.material.rotation===0,'runtime renderer freezes on idle frame 0 when the existing no-animation setting is enabled');
ok(/updatePlayerSprite\(player\.fig,player\.yaw/.test(sky)&&/updatePlayerSprite\(a\.fig,a\.yaw/.test(sky),'local and online players update atlas direction and lightweight movement motion every frame');
ok(/PLAYER_RADIUS=\.46, PLAYER_HEIGHT=2\.02/.test(sky)&&/radius=PLAYER_RADIUS.*head=feet\+PLAYER_HEIGHT/.test(sky),'movement capsule remains independent from the visual renderer and matches the child-size silhouette');
ok(/function bindInput/.test(sky)&&/const j=ui\.joy,placeJoy=/.test(sky)&&/e\.pointerType!=='mouse'&&e\.clientX<=rr\.left\+rr\.width\*\.5/.test(sky)&&/addListener\(root,'pointerdown'.*true\)/.test(sky)&&/document\.hidden.*joy\.id=null/.test(sky),'touching free space anywhere in the left half starts a floating joystick and visibility loss releases it');
ok(/goal\.clone\(\)\.sub\(petComp\.group\.position\)/.test(sky),'pet follow teleports to the absolute goal without per-frame particle leaks');
ok(/playerStyle='soft-cuboid-chibi-3d'/.test(sky),'visible players use Soft Cuboid Chibi 3D');
ok(/speakWord/.test(sky)&&/vocabForStudent/.test(sky)&&/questEvent\('word3d'/.test(sky),'vocabulary reuses data, pronunciation and shared quest event');
ok(/addCoins\(20\)/.test(sky)&&/first\?100:20/.test(sky),'stars and route completion use main coins');
ok(/kind:'bounce'/.test(sky)&&/rotators\.forEach\(r=>/.test(sky)&&/kind==='disappear'/.test(sky),'sample Obby includes bounce, rotating, moving and disappearing obstacles');
const collisionCode=sky.slice(sky.indexOf('function localXZ'),sky.indexOf('function blockedGate'));
const collisionCtx={Math,PLAYER_RADIUS:.46,PLAYER_HEIGHT:2.02,solids:[{x:0,z:0,w:2,d:2,minY:.4,maxY:2,enabled:true}],player:{pos:{y:.45},vel:{x:3,z:4}}};vm.runInNewContext(collisionCode+';this.hit=resolveSolids;this.toLocal=localXZ;',collisionCtx);
const boxHit=collisionCtx.hit(0,0),rotated=collisionCtx.toLocal(1,0,{x:0,z:0,yaw:Math.PI/2});
collisionCtx.solids[0]={x:0,z:0,r:2,minY:.4,maxY:2,enabled:true};collisionCtx.player.vel={x:3,z:4};const circleHit=collisionCtx.hit(0,0);
ok(Math.max(Math.abs(boxHit.x),Math.abs(boxHit.z))>=1.379&&collisionCtx.player.vel.x*collisionCtx.player.vel.z===0,'solid collider pushes the player capsule outside visible material');
ok(Math.hypot(circleHit.x,circleHit.z)>=2.379&&Math.abs(rotated.x)<1e-9&&Math.abs(rotated.z+1)<1e-9,'circle and rotated-box colliders cover round and angled material');
const requiredSolids=['book','pencil','fountain','tree-trunk','tower-core','tower-crown','letter-block-','floating-island-'];
ok(requiredSolids.every(name=>sky.includes("'"+name))&&/new THREE\.Box3\(\)\.setFromObject\(obj\)/.test(sky)&&/solids\.push\(s\)/.test(sky),'every solid scenery category registers from its real mesh bounds');
ok(/\(!s\.w&&!s\.r\)/.test(sky)&&/get solids\(\)\{return solids\}/.test(sky),'round floating supports and collider inventory remain testable');
ok(/data-activity="letter"/.test(sky)&&/data-activity="race"/.test(sky)&&/data-activity="obby"/.test(sky)&&/data-activity="tower"/.test(sky),'Phase 3 exposes all four Sky activities');
ok(/PHASE 2 SHARED ACTIVITIES/.test(sky)&&/activityRows\(\)/.test(sky)&&/S3:\$\{activityCode\(\)\}/.test(sky),'all activities publish shared progress and live standings through NetRoom');
ok(/function tickActivity/.test(sky)&&/function setupRaceQuestion/.test(sky)&&/completeActivity\('obby',false\)/.test(sky),'three activities have interactive gameplay and completion paths');
ok(/TOWER_FLOORS=6/.test(sky)&&/activityRound\.progress%2===0/.test(sky)&&/function answerTower/.test(sky),'Vocabulary Tower has 6 rising-difficulty floors and checkpoints every 2 floors');
ok(/ยังไม่ใช่ครับ — ลองใหม่ได้ทันที ไม่ลดชั้น ไม่หักเหรียญ/.test(sky),'wrong Tower answers allow immediate retry without coin or floor loss');
ok(/makeDailyMissions/.test(sky)&&/ACTIVITY_KINDS\.slice\(shift\)/.test(sky)&&/slice\(0,3\)/.test(sky),'Daily Sky Missions rotate three of four activities by date');
ok(/claimOnce\('daily_first',40\)/.test(sky)&&/run_\$\{activityRound\.runId\}/.test(sky)&&/state\.skyDaily\.claims/.test(sky),'daily and per-run reward claims prevent reconnect/reload duplicates');
ok(/unlockBadge\('speed'\)/.test(sky)&&/unlockBadge\('accuracy'\)/.test(sky)&&/unlockBadge\('coop'\)/.test(sky),'speed, accuracy and co-op badges persist in the existing save');
ok(/restoreActiveRun/.test(sky)&&/considerJoinOffer/.test(sky)&&/joinLiveActivity/.test(sky),'reconnect resume and join-in-progress paths are present');
ok(/PHASE 4: CLASSROOM SKY EVENTS/.test(sky)&&/CLASS_MIN_WORDS=3,CLASS_MAX_WORDS=5/.test(sky),'Phase 4 adds bounded Classroom Sky Events');
ok(/classroomPool\(\).*baseWordPool\(\)/s.test(sky)&&!/const CLASS_WORD/.test(sky),'teacher word picker reuses the existing vocabulary pool without a duplicate database');
ok(/CLASS_TIMES=\[30,60,90\]/.test(sky)&&/meaning:\{code:'M'/.test(sky)&&/listen:\{code:'L'/.test(sky)&&/spell:\{code:'S'/.test(sky),'teacher can choose time and all three classroom modes');
ok(/makeClassWire/.test(sky)&&/parseClassWire/.test(sky)&&/\['C4','C5'\]/.test(sky)&&/S4:\$\{activityRound\.role===/.test(sky),'Phase 4 C4/S4 compatibility remains while the parser accepts Phase 5');
ok(/classWire\.length>60/.test(sky)&&/Math\.min\(99999/.test(sky),'classroom wire data stays inside existing Firebase field limits');
ok(/function classRows/.test(sky)&&/function classResultHtml/.test(sky)&&/ผลสรุปชั้นเรียน/.test(sky),'teacher gets a live and final class summary');
ok(/function rememberClassPeer/.test(sky)&&/classRoster\[uid\]/.test(sky)&&/id="sp-class-finish"/.test(sky),'summary keeps disconnected results and teacher can finish early');
ok(!/addCoins\([^)]*\)/.test(sky.slice(sky.indexOf('PHASE 4: CLASSROOM'),sky.indexOf('PHASE 2 SHARED'))),'classroom events add no currency path or reward');
ok(/PHASE 5: LOCAL TEACHER DATA/.test(sky)&&/vocabSkyTeacher_v1/.test(sky)&&/localStorage\.setItem\(TEACHER_STORE_KEY/.test(sky),'lesson packs, reconnect state and reports persist locally on the device');
ok(/data-class-mode/.test(sky)&&/Lesson playlist/.test(sky)&&/list\.map\(k=>CLASS_MODES\[k\]\.code\)/.test(sky),'teacher can save a sequential multi-activity lesson playlist');
ok(/phase:'ready'/.test(sky)&&/function markClassReady/.test(sky)&&/function startLessonRun/.test(sky)&&/sp-student-ready/.test(sky),'ready check gates the playlist before the teacher starts');
ok(/S5:H:\$\{phaseNumber/.test(sky)&&/S5:\$\{mode\}/.test(sky)&&/function syncClassHost/.test(sky),'S5 reuses NetRoom hp for host phase, reconnect and late-join synchronization');
ok(/function reportCsv/.test(sky)&&/function downloadClassReport/.test(sky)&&/function printClassReport/.test(sky)&&/Classroom Reports/.test(sky),'teacher reports support per-person/per-word views, CSV and print');
ok(/R5\|\$\{activityRound\.eventId\}/.test(sky)&&/slice\(-48\)/.test(sky)&&/cw=studentReportWire\(\)/.test(sky)&&/parseStudentReport/.test(sky),'authorized compact per-word telemetry stays inside the existing cw field and reaches the teacher roster');
const netCtx={console,performance:{now:()=>Date.now()},setTimeout,clearTimeout,document:{getElementById:()=>null}};netCtx.window=netCtx;vm.runInNewContext(net,netCtx,{filename:'js/netroom.js'});const reportWire='R5|abcde|'+'1'.repeat(48),split=netCtx.NetRoom._split({n:'student',x:0,z:0,cw:reportWire}),merged=netCtx.NetRoom._merge(split.hot,split.cold);ok(reportWire.length<=60&&split.cold.q===reportWire&&merged.cw===reportWire,'maximum R5 answer telemetry survives the real NetRoom split/merge within cw limit');
ok(/function saveStudentResume/.test(sky)&&/teacherData\.active/.test(sky)&&/o\.phase==='run'/.test(sky),'student progress can resume locally and late join starts at the current activity');
ok(/function saveHostResume/.test(sky)&&/function restoreHostLesson/.test(sky)&&/restoreHostLesson\(\)&&!restoreActiveRun/.test(sky),'teacher ready/run roster resumes locally after reload');
ok(!/\.ref\(|authWriteCloud|Online\.db/.test(sky.slice(sky.indexOf('PHASE 5: LOCAL TEACHER DATA'),sky.indexOf('function createDom'))),'Phase 5 local teacher store adds no Firebase write path');
ok(/activityReward\(kind/.test(sky)&&/addCoins\(reward\)/.test(sky),'Phase 3 rewards use main coins and durable daily progress');
ok(/\.sp-activity-grid\{display:grid;grid-template-columns:repeat\(4,1fr\)/.test(css)&&/\.sp-daily\{/.test(css)&&/\.sp-tower\{/.test(css)&&/@media \(max-height:460px\)/.test(css),'Tower, missions and four-activity picker are landscape-first');
ok(/\.sky-hint\{[^}]*top:65px/.test(css)&&/\.sky-exit/.test(css)&&/\.sky-word/.test(css)&&!/\.sp-(?:hint|exit|word)(?=[,{.:#\\s])/.test(css),'Sky hint, exit and word popup use a collision-free namespace');
ok(/\.sp-classroom\{/.test(css)&&/\.sp-class-results\{/.test(css)&&/\.sp-class-options\{/.test(css)&&/grid-template-columns:auto minmax\(120px,1fr\) auto auto auto/.test(css),'Classroom setup, quiz and summary fit landscape mobile');
ok(/\.sp-character-picker\{/.test(css)&&/\.sp-character-grid\{display:grid;grid-template-columns:repeat\(6,minmax\(0,1fr\)\)/.test(css)&&/\.sp-character-card\{[^}]*max-height:92vh/.test(css)&&/@media \(max-height:460px\)\{\.sp-top\{grid-template-columns:[^}]*auto auto auto auto/.test(css),'six-character picker and top bar fit the locked 812x375 landscape viewport');
ok(/function skyEntryCatalog\(\)/.test(ui)&&/SkyPlayground3D/.test(ui)&&/data-sky-entry-character/.test(ui)&&/loadSkyPlayground3d\(\)\.then/.test(ui),'Sky entry dialog loads the existing six-character catalog before entering the 3D world');
ok(/state\.skyCharacter = character\.id/.test(ui)&&/saveState\(\)/.test(ui)&&/authPushSave\(false\)/.test(ui)&&/จ่ายแล้วเข้าเป็น/.test(ui),'pre-entry character choice is visible, saved and cloud-synced before payment');
ok(/--sp-character-thumb:url\('\$\{c\.thumb\}'\)/.test(sky)&&/c\.thumb\|\|c\.atlas/.test(ui)&&/background-image:var\(--sp-character-thumb\).*background-size:contain/.test(css)&&/background-image:var\(--sky-entry-thumb\).*background-size:contain/.test(css),'both character pickers use proportional lightweight thumbnails instead of loading six full atlases');
ok(/\.sky-entry-box\{[^}]*max-height:calc\(100vh - 12px\);overflow:hidden/.test(css)&&/\.sky-entry-character-grid\{display:grid;grid-template-columns:repeat\(6,minmax\(0,1fr\)\)/.test(css)&&/\.sky-entry-actions\{display:grid;grid-template-columns:1fr 1\.35fr auto/.test(css),'pre-entry picker and actions fit the locked 812x375 viewport without scrolling');
ok(/\.sp-packbar\{/.test(css)&&/\.sp-class-playlist\{/.test(css)&&/\.sp-ready-grid\{/.test(css)&&/\.sp-report-cols\{/.test(css),'Phase 5 lesson packs, ready check and reports have isolated responsive styles');
ok((sky.match(/authPushSave\(true\)/g)||[]).length>=2,'completion and exit request cloud sync');
ok(/mode:'sky'.*enter:enterSkyPlayground3D/.test(ui),'WORLD3D registry owns the entrance');
ok(/css\/skyplay3d\.css/.test(html),'classic shell loads isolated world CSS');
ok(/\['adv','sky','haunt'/.test(net),'friend-location scan includes sky map');
ok((rules.match(/\$map === 'sky'/g)||[]).length===3&&/newData\.val\(\) === 'sky'/.test(rules),'Rules allow sky only in world/wroom/winfo/tinv enums');
ok(!/Adventure3D\.|InvasionWorld\./.test(sky),'new engine does not mutate protected worlds');
console.log('Vocab Sky Playground Phase 5 additive structural regression passed');
