'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8');
const assert=(x,m)=>{if(!x)throw new Error(m)};
const ctx={window:{}};vm.createContext(ctx);
vm.runInContext(read('js/data/pets.js')+'\nwindow.__feedData={PETS,FOODS,FOOD_SPRITE_URL,foodSpriteHTML};',ctx);
const {PETS,FOODS,FOOD_SPRITE_URL}=ctx.window.__feedData;
const favorites=Object.values(PETS).map(p=>p.favFood),all=[...favorites,...FOODS];
assert(Object.keys(PETS).length===9,'expected all 9 pet types');
assert(all.length===18&&all.every(f=>Array.isArray(f.art)&&f.art.length===2),'all 18 foods need sprite coordinates');
assert(new Set(all.map(f=>f.art.join(','))).size===18,'food sprite coordinates must be unique');
assert(FOOD_SPRITE_URL==='img/pet-food/food-sprite.webp','sprite runtime path changed');
const chicken=FOODS.find(f=>f.id==='chicken');
assert(chicken&&/Boneless/.test(chicken.en)&&/ไร้กระดูก/.test(chicken.name),'bone-in chicken must not remain');
assert(chicken.safeNote.includes('กระดูกไก่อาจทิ่มลำไส้สัตว์ได้'),'correct chicken-bone safety wording missing');
assert(read('handoff/GAME_RULES.md').includes('อกไก่ต้มสุกไร้กระดูกเท่านั้น')&&read('handoff/GAME_RULES.md').includes('กระดูกไก่อาจทิ่มลำไส้สัตว์ได้'),'food safety source-of-truth missing');
assert(!read('js/data/pets.js').includes("name:'น่องไก่'"),'old bone-in drumstick menu remains');
const ui=read('js/ui.js'),css=read('css/style.css'),pantry=read('js/petpantry.js'),build=read('tools/build_web.mjs');
assert(ui.includes('ให้อาหารสัตว์ทุกตัวที่เลี้ยงอยู่'),'all-pets button copy missing');
assert(ui.includes('feed-all-pets')&&ui.includes('feed-all-foods')&&ui.includes('feed-all-confirm'),'bulk planner DOM missing');
assert(ui.includes("PetPantry.takeMany(rows.map"),'bulk feed must debit stock atomically');
assert(ui.includes('applyFoodToPet(row.p,row.food')&&ui.includes('function applyFoodToPet'),'single rule path for bulk mutation missing');
assert(pantry.includes('function takeMany')&&pantry.includes('ids.some'),'atomic stock guard missing');
assert(css.includes("url('../img/pet-food/food-sprite.webp')")&&css.includes('background-size:600% 300%'),'sprite CSS missing');
assert(css.includes('grid-template-columns:repeat(5,minmax(0,1fr))')&&css.includes('@media(max-height:430px)'),'5x2/no-scroll responsive layout missing');
assert(css.includes('.feed-all-box')&&css.includes('overflow:hidden'),'bulk dialog must not scroll');
assert(build.includes("'img/pet-food/food-sprite.webp'"),'untracked first-build allowlist missing');
const asset=fs.readFileSync(path.join(root,FOOD_SPRITE_URL));
assert(asset.subarray(0,4).toString()==='RIFF'&&asset.subarray(8,12).toString()==='WEBP','runtime asset is not encoded WebP');
const vp8x=asset.indexOf(Buffer.from('VP8X'));assert(vp8x>=0,'WebP extended header missing');
assert((asset[vp8x+8]&0x10)!==0,'WebP alpha flag missing');
const u24=i=>asset[i]|asset[i+1]<<8|asset[i+2]<<16;
assert(u24(vp8x+12)+1===1080&&u24(vp8x+15)+1===540,'WebP dimensions must be 1080x540');
assert(asset.length<220000,`food sprite too heavy: ${asset.length} bytes`);
console.log(`PASS bulk feeding: 9 pets, 18 WebP foods, boneless chicken, atomic stock, 5x2 compact panel (${asset.length} bytes)`);
