'use strict';
const assert=require('assert'),BR=require('../js/wordskirmish-br.js');let n=0;
function check(name,fn){fn();console.log('PASS '+name);n++;}
check('weapon magazines, finite reload and healing interruption state',()=>{const i=BR.inventory();i.ammo[0]=3;i.reserve[0]=8;assert(BR.reload(i,1));assert.equal(BR.finishAction(i,45,2),45);BR.finishAction(i,45,3);assert.equal(i.ammo[0],11);assert.equal(i.reserve[0],0);assert(BR.heal(i,20,4));assert.equal(BR.finishAction(i,20,7),85);assert.equal(i.medkits,1);});
check('armor absorbs only available points, with actual headshot damage',()=>{assert.deepEqual(BR.damage(100,50,20),{hp:92,armor:38});assert.deepEqual(BR.damage(100,10,60),{hp:50,armor:0});assert.equal(BR.damage(100,50,180).hp,0);});
check('zone waits, shrinks continuously, reaches zero and increases damage',()=>{assert.equal(BR.zone(39).radius,52);assert(BR.zone(100).radius<BR.zone(50).radius);assert.equal(BR.zone(200).radius,0);assert(BR.zone(200).damage>BR.zone(80).damage);assert(BR.outside(40,40,BR.zone(0)));});
check('eight-player metadata stays inside existing 60-character field',()=>{const r={phase:'A',winner:'',mask:127,roster:Array.from({length:8},(_,i)=>BR.token('person-'+i)),start:123456};const s=BR.encode(r);assert(s.length<=60);assert.deepEqual(BR.decode(s,r.start),r);assert.equal(BR.decode('BAinvalid',123),null);});
function pair(){const ids=['alice','bob'].sort((a,b)=>BR.token(a).localeCompare(BR.token(b)));return {ids,cs:ids.map(BR.controller),hp:[100,100],now:100000};}
function exchange(t,ms=100){t.now+=ms;for(let j=0;j<3;j++)t.cs.forEach((c,i)=>{const peers={};t.cs.forEach((p,k)=>{if(k!==i)peers[t.ids[k]]={...p.packet(),hp:'K|'+t.hp[k]+'|-|0'};});c.sync(t.now,peers,t.hp[i]>0,0);});}
check('two clients share warm-up, human-only round, victory and next round',()=>{const t=pair();t.cs.forEach(c=>c.request(t.now));for(let i=0;i<20;i++)exchange(t);assert(t.cs[0].round.start>0);assert.deepEqual(t.cs[0].round,t.cs[1].round);assert.equal(t.cs[0].round.mask,0);exchange(t,10000);assert.equal(t.cs[0].round.phase,'A');exchange(t,2000);t.hp[1]=0;exchange(t);assert.equal(t.cs[0].round.phase,'F');assert.equal(t.cs[0].round.winner,BR.token(t.ids[0]));const old=t.cs[0].round.start;exchange(t,8100);assert(t.cs[0].round.start>old);assert.deepEqual(t.cs[0].round,t.cs[1].round);});
check('late arrival waits for next round and cannot seize authority',()=>{const t=pair();t.cs.forEach(c=>c.request(t.now));exchange(t,1700);exchange(t,12000);const late=BR.controller('late');late.request(t.now);const peers={};t.cs.forEach((c,i)=>peers[t.ids[i]]={...c.packet(),hp:'K|100|-|0'});const r=late.sync(t.now,peers,true,127);assert(!r.admitted);assert.equal(r.phase,'A');assert(!r.roster.includes(BR.token('late')));});
check('authority failover preserves round and awards remaining player',()=>{const t=pair();t.cs.forEach(c=>c.request(t.now));exchange(t,1700);exchange(t,12000);const before=t.cs[1].round.start,r=t.cs[1].sync(t.now+2000,{},true,0);assert.equal(r.start,before);assert.equal(r.phase,'F');assert.equal(r.winner,BR.token(t.ids[1]));});
check('solo bots are counted; no instant victory on entering arena',()=>{const c=BR.controller('solo');c.request(1000);let r=c.sync(2600,{},true,127);r=c.sync(r.start+2000,{},true,127);assert.equal(r.phase,'A');r=c.sync(r.start+3000,{},true,0);assert.equal(r.phase,'F');assert.equal(r.winner,BR.token('solo'));});
check('simultaneous proposals converge during warm-up',()=>{const a=BR.controller('a'),b=BR.controller('b');a.request(1000);b.request(1000);a.sync(2600,{},true,127);b.sync(2700,{},true,127);for(let i=0;i<4;i++){a.sync(2800,{b:{...b.packet(),hp:'K|100|-|0'}},true,127);b.sync(2800,{a:{...a.packet(),hp:'K|100|-|0'}},true,127);}assert.deepEqual(a.round,b.round);assert.equal(a.round.mask,0);});
(async()=>{
 const fs=require('fs'),path=require('path'),vm=require('vm'),root=process.env.SKM_ROOT||path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'js/ui.js'),'utf8');
 const start=source.indexOf('async function openWordSkirmish(){'),end=source.indexOf('\nfunction bindSkirmishRail',start),calls=[];
 assert(start>=0&&end>start);const context={skirmishAdminAllowed:()=>true,closePanel(){},toast(){},console,loadStylesheetOnce:async()=>calls.push('css')};
 context.loadScriptOnce=async file=>{calls.push(file);if(file==='js/wordskirmish.js')context.WordSkirmish={open:()=>calls.push('open')};};vm.createContext(context);
 const open=vm.runInContext('('+source.slice(start,end)+')',context);await open();assert.deepEqual(calls,['css','js/wordskirmish-br.js','js/wordskirmish-field.js','js/wordskirmish.js','open']);
 calls.length=0;await open();assert.deepEqual(calls,['css','open']);calls.length=0;context.skirmishAdminAllowed=()=>false;context.SKIRMISH_LOCK_MSG='locked';await open();assert.equal(calls.length,0);
 console.log('PASS actual UI lazy loader preserves dependency order, reuse and admin gate');n++;console.log('wordskirmish BR rules/loader ok '+n);
})().catch(e=>{console.error(e);process.exitCode=1});
