'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),root=path.resolve(process.env.VW_ARENA_SOURCE||repo),out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-bgm');
const {chromium}=require(path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const checks=[],ok=(n,v)=>{assert.ok(v,n);checks.push(n);};
const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><button id="enter">Arena</button><script>window.state={sound:true,musicOff:false};const BaseAudio=window.Audio;window.media=[];window.Audio=function(...args){const el=new BaseAudio(...args);media.push(el);return el;};</script><script src="/js/arena-audio.js"></script><script>ArenaAudio.start(document.body);</script>`;
const gameHtml=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"><script>window.state={profileName:'test',coins:1000,arenaIntro:true,arenaHomeIntro:true,arenaItems:{},arenaHero:'fire',arenaMap:'crystal',sound:true,haptic:false};window.isAdmin=()=>true;window.saveState=()=>{};window.addCoins=n=>state.coins+=n;window.vocabForStudent=()=>[['cat','cat']];window.activePet=()=>null;window.toast=()=>{};</script>`+['vendor/three.min','arena-audio','arena-field-visuals','arena-elements','arena-spell-catalog','arena-grimoire','arena-relics','arena-heroes','arena-maps','arena3d'].map(n=>`<script src="/js/${n}.js"></script>`).join('');
const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://localhost').pathname;if(p==='/game'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(gameHtml);}if(p==='/test'){res.setHeader('Content-Type','text/html');return res.end(html);}const file=path.resolve(root,'.'+p);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.ogg')?'audio/ogg':'audio/mpeg');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
 for(const mobile of [false,true]){
  const context=await browser.newContext({viewport:mobile?{width:812,height:375}:{width:1366,height:768},isMobile:mobile,hasTouch:mobile});const page=await context.newPage(),requests=[],errors=[];
  page.on('request',r=>{if(r.url().includes('bgmusic-'))requests.push(r.url());});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/test');await page.waitForTimeout(650);
  ok('no music bytes or player before gesture',requests.length===0&&await page.evaluate(()=>media.length===0));
  if(mobile)await page.locator('#enter').tap();else await page.locator('#enter').click();
  await page.waitForFunction(()=>ArenaAudio.stats().music.playing&&media[0].currentTime>.1);
  ok('single supported Opus download and quiet looping player',requests.length===1&&requests[0].endsWith('.ogg')&&await page.evaluate(()=>media.length===1&&media[0].loop&&media[0].volume===.16));
  await page.evaluate(()=>media[0].currentTime=media[0].duration-.2);await page.waitForTimeout(800);
  ok('natural track ending loops without another download',requests.length===1&&await page.evaluate(()=>media[0].currentTime<2&&!media[0].paused));
  await page.evaluate(()=>state.musicOff=true);await page.waitForFunction(()=>media[0].paused);ok('music setting pauses music',true);
  await page.evaluate(()=>state.musicOff=false);await page.waitForFunction(()=>!media[0].paused);await page.evaluate(()=>state.sound=false);await page.waitForFunction(()=>media[0].paused);ok('global sound setting pauses music',true);
  await page.evaluate(()=>state.sound=true);await page.waitForFunction(()=>!media[0].paused);
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});ok('background silences immediately',await page.evaluate(()=>media[0].paused));
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForFunction(()=>!media[0].paused);
  await page.evaluate(()=>ArenaAudio.exit());ok('exit stops looping music immediately',await page.evaluate(()=>media[0].paused&&!media[0].getAttribute('src')));await page.waitForTimeout(200);
  await page.evaluate(()=>ArenaAudio.start(document.body));await page.locator('#enter').click();await page.waitForFunction(()=>ArenaAudio.stats().music.playing);ok('re-entry reuses compressed song without network',requests.length===1);
  await page.evaluate(()=>ArenaAudio.stop());await page.route('**/*bgmusic-*',route=>route.abort());await page.reload();await page.locator('#enter').click();await page.waitForFunction(()=>ArenaAudio.stats().music.playing);
  ok('page reload plays from persistent cache with music network unavailable',requests.length===1&&await page.evaluate(()=>ArenaAudio.stats().music.downloads===0));
  await page.evaluate(()=>ArenaAudio.stop());ok('no JS errors',errors.length===0);await context.close();
 }
 const fallback=await browser.newContext();await fallback.addInitScript(()=>{const native=HTMLMediaElement.prototype.canPlayType;HTMLMediaElement.prototype.canPlayType=function(type){return /ogg/.test(type)?'':native.call(this,type);};});const p=await fallback.newPage(),urls=[];p.on('request',r=>{if(r.url().includes('bgmusic-'))urls.push(r.url());});await p.goto('http://127.0.0.1:'+server.address().port+'/test');await p.locator('#enter').click();await p.waitForFunction(()=>ArenaAudio.stats().music.playing);ok('unsupported Opus selects MP3 only',urls.length===1&&urls[0].endsWith('.mp3'));await p.evaluate(()=>ArenaAudio.stop());await fallback.close();
 const missing=await browser.newContext();const m=await missing.newPage(),bad=[],failures=[];m.on('pageerror',e=>failures.push(e.message));await m.route('**/*bgmusic-*',r=>{bad.push(r.request().url());return r.fulfill({status:404,body:''});});await m.goto('http://127.0.0.1:'+server.address().port+'/test');await m.locator('#enter').click();await m.waitForTimeout(1800);ok('missing music remains silent without crashes or request spam',bad.length===1&&failures.length===0&&!await m.evaluate(()=>ArenaAudio.stats().music.playing));await m.evaluate(()=>ArenaAudio.stop());await missing.close();
 const game=await browser.newPage({viewport:{width:812,height:375},isMobile:true,hasTouch:true}),gameAudio=[],gameErrors=[];game.on('request',r=>{if(r.url().includes('/sound/arena/'))gameAudio.push(r.url());});game.on('pageerror',e=>gameErrors.push(e.message));
 await game.goto('http://127.0.0.1:'+server.address().port+'/game');await game.evaluate(()=>VocabArena3D.start());await game.waitForTimeout(300);ok('real Arena has no initial SFX or music download',gameAudio.length===0);
 await game.locator('#va-home-nav').tap();await game.waitForFunction(()=>ArenaAudio.stats().music.playing);
 await game.evaluate(()=>{const t=VocabArena3D._t;t.player().pos.set(0,0,0);t.bots[0].group.position.set(5,0,0);t.cast('basic');t.kill(1);for(let i=0;i<5;i++)t.collect(t.drops.indexOf(t.crystalNodes[i].drop));t.cast('ult');t.cast('light');t.complete();});await game.waitForTimeout(600);
 ok('shooting, kills, crystals, MEGA, shield and reward request no sound effects',gameAudio.length===1&&gameAudio[0].includes('bgmusic-')&&await game.evaluate(()=>ArenaAudio.stats().music.playing));
 await game.locator('#va-exit').tap();ok('real Arena exit stops music',!await game.evaluate(()=>ArenaAudio.stats().music.playing));ok('real Arena no JS errors',gameErrors.length===0);await game.close();
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'music-tests.json'),JSON.stringify({passed:checks.length,checks},null,2));console.log(JSON.stringify({passed:checks.length,checks}));
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
