'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..'),read=r=>fs.readFileSync(path.join(root,r),'utf8');const assert=(x,m)=>{if(!x)throw new Error(m)};
const js=read('js/petshopping3d.js'),css=read('css/petshopping3d.css'),ui=read('js/ui.js');
const sandbox={window:{},console};vm.runInNewContext(js,sandbox);const testApi=sandbox.window.PetShopping3D._t,testRoute=testApi.routeFor({x:0,z:18},'fashion');
assert(testRoute.every(p=>testApi.onRoad(p.x,p.z)),'GPS route must end on the drivable road');testApi.setPose(40,10,0);assert(!testApi.onRoad(40,10),'off-road fixture invalid');testApi.keepCarOnRoad();assert(testApi.onRoad(testApi.driveState.x,testApi.driveState.z),'off-road car was not projected back onto the road');
testApi.setPose(0,18,Math.PI);testApi.setSafety(true,true);testApi.setControls(true,false);const driveStartZ=testApi.driveState.z;for(let i=0;i<120;i++)testApi.stepDrive(1/60,1000+i*1000/60);testApi.setControls(false,false);assert(testApi.driveState.z<driveStartZ-5&&testApi.driveState.speed>1,'holding D/throttle must move the car forward continuously');
assert(js.includes('window.PetShopping3D')&&js.includes('start,exit,isRunning'), 'world public API missing');
assert(js.includes('antialias:false')&&js.includes('Math.min(devicePixelRatio||1,1.5)')&&js.includes('shadowMap.enabled=false'),'mobile renderer budget missing');
assert(js.includes('routeFor')&&js.includes('LineBasicMaterial')&&js.includes('navText'),'GPS route/navigation missing');
['foundation','facade bays','pilasters','cornice'].forEach(()=>{});assert(js.includes('checkout')&&js.includes('wall shelves')&&js.includes('gondola')&&js.includes('addShop(\'food\')')&&js.includes('addShop(\'fashion\')'),'structured shop components missing');
assert(js.includes("img/pet-shopping/${kind}_window.webp"),'generated shop-art mapping missing');
assert(js.includes('PetPantry.openStore(target,{onClose')&&js.includes('currentPetImg')&&css.includes('@keyframes ps3Bob'),'shop checkout or pet passenger missing');
assert(js.includes('radioState')&&js.includes('renderRadioList')&&js.includes('drawRadioViz')&&js.includes('Music.toggleCar()')&&css.includes('.ps3-radio-list'),'KPP car-radio/equalizer port missing');
assert(js.includes('img/3d_car/3d_dash_${carId}.png')&&js.includes('img/3d_car/3d_wheel_${num}.png')&&css.includes('clip-path:polygon'),'premium seamless cockpit art/crop missing');
assert(js.includes('Source of truth: js/adventure3d.js')&&js.includes('function carDrive')&&js.includes('CAR_EYE=1.55')&&js.includes('CAR_WB=2.6')&&js.includes('dVelX+=(sin*dSpeed-dVelX)*grip'),'Kamphaeng Phet bicycle-model driving source port missing');
assert(js.includes('ps3-steerpad')&&js.includes('ps3-gaspad')&&js.includes('ps3-brakepad')&&js.includes('ps3-geard')&&js.includes('ps3-gearr')&&js.includes('ps3-horn'),'KPP steering/throttle/brake/D/R/horn controls missing');
assert(js.includes('setGear(!gearR)')&&js.includes('CarSnd.horn()')&&js.includes('CarSnd.revBeep()')&&js.includes('CarSnd.tlClick'),'KPP gear/horn/reverse/turn-signal feedback missing');
assert(js.includes('ps3-carstart')&&js.includes('cs-engine')&&js.includes('cs-belt')&&js.includes('CAR_FINE_BELT=300'),'KPP engine-start/seatbelt system missing');
assert(js.includes('toggleCamera')&&!js.includes('drawMirrors')&&!js.includes('mirrorPass')&&!js.includes('ps3-mirror'),'three mirror windows must be fully removed');
assert(!js.includes('ps3-windshield')&&!js.includes('ps3-wiper')&&!js.includes('ps3-visor')&&css.includes('.ps3-turn-effects'),'front windshield overlay and obsolete controls must be removed while turn glow remains');
assert(js.includes('turnTick')&&js.includes('turnReturnAt=now+900')&&js.includes('ps3-turnpad'),'KPP self-cancelling turn signal missing');
assert(js.includes('CAR_REPAIR_FEE=100')&&!js.includes('CAR_REPAIR_FEE=1000'),'collision repair fee must be 100 coins');
assert(js.includes('keepCarOnRoad()')&&js.includes('STORE_STOP_Z=-60')&&js.includes('ROAD_HALF_X=13')&&js.includes('ROAD_HALF_Z=11'),'road containment or safe store stop missing');
assert(js.includes('addRoadBarriers()')&&js.includes('new THREE.InstancedMesh')&&js.includes('ROAD CLOSED')&&js.includes('ห้ามผ่าน'),'visible guardrails and four road-closed end signs missing');
assert(js.includes('gearDriveOn')&&js.includes('setPointerCapture')&&js.includes("'lostpointercapture'"),'hold D/R must drive immediately and release safely');
assert(js.includes('pitchTgt')&&js.includes('dHeaveV')&&js.includes('groundShadow'),'grounded suspension weight or car contact shadow missing');
assert(js.includes("listen(window,'blur'")&&js.includes("listen(document,'visibilitychange'"),'stuck steering/throttle release guards missing');
assert(js.includes('radioPeaks')&&js.includes('PREMIUM SPECTRUM')&&js.includes('Math.pow(p,1.55)')&&js.includes('20k Hz'),'premium log-spectrum equalizer missing');
assert(css.includes('#ff8a00')&&css.includes('width:28px;height:28px')&&css.includes('overflow:hidden'),'contained orange/amber turn signal styling missing');
assert(js.includes('WORLD_HALF=700')&&js.includes('DRIVE_LIMIT=480')&&js.includes('WORLD_HALF*2'),'world floor/road must extend beyond every drivable boundary');
assert(css.includes('min-width:50px;height:50px')&&css.includes('.ps3-actions{gap:10px}'),'adult-friendly top action targets/gaps missing');
assert(js.includes('solidRect')&&js.includes('solidCircle')&&js.includes('hitsSolid(car.x,car.z)')&&js.includes('car.x=prevX;car.z=prevZ'),'building/tree collision response missing');
assert(js.includes('cute_town_mural_v2.webp')&&js.includes('decorateTown(rows)'),'generated cute building mural decoration missing');
assert(js.includes("fetch(url,{cache:'force-cache'})")&&js.includes('createImageBitmap')&&js.includes('TextureLoader().load(url,finish'),'reliable texture loader/fallback missing');
assert(js.includes('Music.suspendBg()')&&js.includes('Music.carRadio(true)')&&js.includes('Music.resumeBg()'),'car music lifecycle missing');
assert(ui.includes('ps3Css')&&ui.includes("petshopping3d.css?v=1166")&&ui.includes("petshopping3d.js?v=1166"),'Pet Shopping runtime cache refresh missing');
assert(js.includes('cancelAnimationFrame')&&js.includes('forceContextLoss')&&js.includes('listeners.splice'),'world cleanup missing');
assert(css.includes('@media(max-height:430px)')&&css.includes('overflow:hidden'),'812x375/no-scroll world CSS missing');
console.log('PASS Pet Shopping 3D: hold-to-drive, grounded suspension, barriers, all glass overlays removed, premium cockpit and cleanup');
