'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),root=path.resolve(process.env.VW_ARENA_SOURCE||repo),out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-heroes');fs.mkdirSync(out,{recursive:true});
const deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'),{chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
const checks=[],ok=(n,v)=>{assert.ok(v,n);checks.push(n);};
const ui=fs.readFileSync(path.join(root,'js/ui.js'),'utf8'),entry=ui.slice(ui.indexOf('async function enterAdventure3D(){'),ui.indexOf('/* 🗺️ กล่องเลือกแผนที่',ui.indexOf('async function enterAdventure3D(){')));
const harness=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"><link id="arena-heroes-css" rel="stylesheet" href="/css/arena-heroes.css"></head><body><button id="open">เปิดเกม</button><script>window.state={profileName:'admin',coins:1000,advTicket:true,arenaIntro:true,arenaHomeIntro:true,arenaItems:{},sound:false};window.allowed=true;window.isAdmin=()=>allowed;window.saveState=()=>localStorage.setItem('heroTest',JSON.stringify(state));window.addCoins=n=>state.coins+=n;window.vocabForStudent=()=>[['cat','แมว']];window.activePet=()=>null;window.toast=()=>{};let advLoading=false;window.pickAdvMap=async()=>'field';window.worldEntryStopped=m=>({stopped:m});window.worldEntryStarted=()=>({started:true});window.advBusyMsg=()=>{};window.scripts=[];window.loadScriptOnce=async src=>{scripts.push(src);};window.loadVocabArena3d=async()=>{scripts.push('arena');};${entry}document.querySelector('#open').onclick=()=>{window.entry=enterAdventure3D();};</script><script src="/js/vendor/three.min.js"></script><script src="/js/arena-field-visuals.js"></script><script src="/js/arena-elements.js"></script><script src="/js/arena-portrait.js"></script><script src="/js/arena-heroes.js"></script><script src="/js/arena3d.js"></script></body></html>`;
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/test'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(harness);}const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.webp')?'image/webp':'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(`http://127.0.0.1:${server.address().port}/test`);await page.evaluate(()=>{allowed=false;});await page.click('#open');ok('non-admin blocked before picker',await page.locator('#ah-picker').count()===0);await page.evaluate(()=>{allowed=true;});await page.click('#open');await page.waitForFunction(()=>ArenaHeroes._t.stats()?.ready);await page.waitForFunction(()=>!document.querySelector('#ah-play').disabled);
 ok('entry opens eight choices before game starts',await page.evaluate(()=>document.querySelectorAll('[data-hero]').length===8&&!VocabArena3D._t.running));ok('four male four female',await page.evaluate(()=>ArenaHeroes.roster.filter(h=>h.gender==='ชาย').length===4&&ArenaHeroes.roster.filter(h=>h.gender==='หญิง').length===4));ok('preloads arena while selecting',await page.evaluate(()=>scripts.includes('arena')));
 for(const id of ['fire','wind','ice','light','earth','meteor','gravity','water']){await page.click('[data-hero="'+id+'"]');await page.waitForFunction(()=>ArenaHeroes._t.stats()?.ready);ok(id+' full image decoded',await page.locator('.ah-portrait-still').evaluate(e=>e.naturalWidth===768&&e.naturalHeight===1152));await page.waitForTimeout(100);await sharp(await page.screenshot()).webp({quality:90}).toFile(path.join(out,'hero-'+id+'.webp'));}
 for(const [w,h] of [[1366,768],[812,375],[667,320],[390,844]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(80);const layout=await page.evaluate(()=>({fits:[...document.querySelectorAll('#ah-picker button,.ah-details,.ah-footer,.ah-portrait')].every(e=>{const r=e.getBoundingClientRect();return r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1&&e.scrollHeight<=e.clientHeight+2&&e.scrollWidth<=e.clientWidth+2;}),image:document.querySelector('.ah-portrait').getBoundingClientRect().height}));ok('picker fits '+w+'x'+h,layout.fits);ok('large full-body image '+w,layout.image>h*.32);await sharp(await page.screenshot()).webp({quality:92}).toFile(path.join(out,'picker-'+w+'.webp'));}
 await page.setViewportSize({width:812,height:375});await page.click('[data-hero="fire"]');await page.waitForFunction(()=>ArenaHeroes._t.stats()?.ready);await page.waitForTimeout(120);const before=await page.locator('.ah-portrait-motion').screenshot();await page.waitForTimeout(500);const after=await page.locator('.ah-portrait-motion').screenshot();const a=await sharp(before).ensureAlpha().raw().toBuffer({resolveWithObject:true}),b=await sharp(after).ensureAlpha().raw().toBuffer();function diff(cx,cy,rx,ry){let sum=0,count=0;for(let y=Math.floor((cy-ry)*a.info.height);y<Math.floor((cy+ry)*a.info.height);y++)for(let x=Math.floor((cx-rx)*a.info.width);x<Math.floor((cx+rx)*a.info.width);x++)for(let c=0;c<3;c++){const i=(y*a.info.width+x)*4+c;sum+=Math.abs(a.data[i]-b[i]);count++;}return sum/count;}const motion={hair:diff(.52,.12,.14,.05),face:diff(.54,.28,.10,.04),cape:diff(.85,.48,.07,.08),boots:diff(.55,.92,.16,.02),fire:diff(.16,.72,.07,.07)};ok('hair cape fire move while face and boots remain anchored',motion.hair>.2&&motion.cape>.2&&motion.fire>.2&&motion.face<.1&&motion.boots<.1);
 if(process.env.VW_ARENA_CAPTURE){const capture=path.join(out,'frames');fs.mkdirSync(capture,{recursive:true});for(let i=0;i<24;i++){await sharp(await page.screenshot()).resize(812,375).webp({quality:90}).toFile(path.join(capture,String(i).padStart(3,'0')+'.webp'));await page.waitForTimeout(60);}}
 await page.click('#ah-motion');const frozen=await page.evaluate(()=>ArenaHeroes._t.stats().frames);await page.waitForTimeout(150);ok('animation toggle stops frames',await page.evaluate(n=>ArenaHeroes._t.stats().frames===n,frozen));await page.click('#ah-motion');await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(50);ok('reduced motion stops frames',await page.evaluate(()=>!ArenaHeroes._t.stats().running));await page.emulateMedia({reducedMotion:'no-preference'});
 await page.click('[data-hero="gravity"]');await page.click('#ah-play');await page.waitForFunction(()=>VocabArena3D._t.running);ok('selected hero and powers applied',await page.evaluate(()=>state.arenaHero==='gravity'&&VocabArena3D._t.hero()==='gravity'&&VocabArena3D._t.slots.join(',')==='gravity,nova'));ok('signature cooldown is 20 percent shorter',await page.evaluate(()=>Math.abs(VocabArena3D._t.skillSeconds('gravity')-9.6)<.0001&&VocabArena3D._t.skillSeconds('fire')===6));ok('selection resources disposed on entry',await page.evaluate(()=>!ArenaHeroes._t.stats()&&!document.querySelector('#ah-picker')));ok('hero selection saved',await page.evaluate(()=>JSON.parse(localStorage.getItem('heroTest')).arenaHero==='gravity'));await page.evaluate(()=>VocabArena3D.stop());
 await page.click('#open');await page.click('[data-hero="water"]');await page.keyboard.press('Escape');ok('cancel does not mutate chosen hero or start game',await page.evaluate(()=>state.arenaHero==='gravity'&&!VocabArena3D._t.running&&!ArenaHeroes._t.stats()));
 await page.evaluate(()=>{window.attempts=0;window.result=ArenaHeroes.choose(()=>{if(++attempts===1)return Promise.reject(Error('offline'));});});await page.waitForFunction(()=>document.querySelector('#ah-play').textContent==='ลองโหลดอีกครั้ง');await page.click('#ah-play');await page.waitForFunction(()=>document.querySelector('#ah-play').textContent.includes('เข้าสู่'));ok('preload failure retry works',await page.evaluate(()=>attempts===2));await page.click('#ah-back');
 await page.evaluate(()=>{window.release=null;window.result=ArenaHeroes.choose(()=>new Promise(r=>release=r));});await page.click('#ah-back');await page.evaluate(()=>release());await page.waitForTimeout(20);ok('late preload after cancel cannot reopen or enter',await page.evaluate(()=>!ArenaHeroes._t.stats()&&!VocabArena3D._t.running));ok('zero browser errors',errors.length===0);
 fs.writeFileSync(path.join(out,'heroes-report.json'),JSON.stringify({checks,motion,errors},null,2));console.log(JSON.stringify({passed:checks.length,motion,errors,out}));
 }catch(e){console.error(e);console.error(errors);await sharp(await page.screenshot()).webp({quality:92}).toFile(path.join(out,'failure.webp'));process.exitCode=1;}finally{await browser.close();server.close();}})();
