'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),root=path.resolve(process.env.VW_ARENA_SOURCE||repo),out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-music-entry');
const deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'),{chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
const checks=[],ok=(name,value)=>{assert.ok(value,name);checks.push(name);};
const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"><button id="enter">Enter Arena</button><script>window.state={profileName:'test',coins:1000,arenaIntro:true,arenaHomeIntro:true,arenaItems:{},arenaHero:'fire',arenaMap:'crystal',sound:true,musicOff:location.search.includes('off'),haptic:false};window.isAdmin=()=>true;window.saves=0;window.saveState=()=>saves++;window.addCoins=n=>state.coins+=n;window.vocabForStudent=()=>[['cat','cat']];window.activePet=()=>null;window.toast=()=>{};</script>`+['vendor/three.min','arena-audio','arena-field-visuals','arena-elements','arena-spell-catalog','arena-grimoire','arena-relics','arena-heroes','arena-maps','arena3d'].map(n=>`<script src="/js/${n}.js"></script>`).join('')+`<script>document.querySelector('#enter').onclick=()=>setTimeout(()=>VocabArena3D.start(),70);</script>`;
const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;if(p==='/entry'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(html);}const file=path.resolve(root,'.'+p);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.ogg')?'audio/ogg':'audio/mpeg');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});const base='http://127.0.0.1:'+server.address().port;try{
 for(const mobile of [false,true]){
  const context=await browser.newContext({viewport:mobile?{width:812,height:375}:{width:1366,height:768},isMobile:mobile,hasTouch:mobile});
  const p=await context.newPage(),urls=[],errors=[];p.on('request',r=>{if(r.url().includes('bgmusic-'))urls.push(r.url());});p.on('pageerror',e=>errors.push(e.message));
  await p.goto(base+'/entry');await p.waitForTimeout(200);ok('entry screen downloads no music before gesture',urls.length===0);
  await p.locator('#enter')[mobile?'tap':'click']();await p.waitForFunction(()=>ArenaAudio.stats().music.status==='playing');
  ok('delayed Arena start inherits entry activation without a second tap',urls.length===1&&await p.evaluate(()=>ArenaAudio.stats().unlocked));
  ok('music control shows playing state',await p.locator('#va-music-toggle').getAttribute('data-state')==='playing');
  const layout=await p.evaluate(()=>{const b=document.querySelector('#va-music-toggle'),r=b.getBoundingClientRect(),overlaps=[...document.querySelectorAll('.va-top,.va-bag,.va-stick,.va-hp,.va-home-nav,.va-skills')].filter(el=>{const q=el.getBoundingClientRect();return r.left<q.right&&r.right>q.left&&r.top<q.bottom&&r.bottom>q.top;}).map(el=>el.className);return {inside:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight,hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===b,overlaps};});
  ok('music control stays visible and separate from game controls',layout.inside&&layout.hit&&layout.overlaps.length===0);
  await sharp(await p.screenshot()).webp({quality:90}).toFile(path.join(out,mobile?'music-mobile.webp':'music-desktop.webp'));
  await p.locator('#va-music-toggle')[mobile?'tap':'click']();await p.waitForFunction(()=>ArenaAudio.stats().music.status==='music-off');ok('one tap pauses and saves music preference',await p.evaluate(()=>state.musicOff&&saves>0&&!ArenaAudio.stats().music.playing));
  await p.locator('#va-music-toggle')[mobile?'tap':'click']();await p.waitForFunction(()=>ArenaAudio.stats().music.status==='playing');ok('one tap resumes cached music without downloading again',urls.length===1);
  await p.evaluate(()=>VocabArena3D.stop());await p.goto(base+'/entry?off');await p.locator('#enter')[mobile?'tap':'click']();await p.waitForFunction(()=>ArenaAudio.stats().music.status==='music-off');
  await p.locator('#va-home-nav')[mobile?'tap':'click']();await p.evaluate(()=>ArenaAudio.playElement());await p.waitForFunction(()=>ArenaAudio.stats().element.played>0);
  ok('saved music mute is visible while approved effects still play',await p.locator('#va-music-toggle').getAttribute('data-state')==='music-off'&&await p.evaluate(()=>!ArenaAudio.stats().music.playing));
  await p.locator('#va-music-toggle')[mobile?'tap':'click']();await p.waitForFunction(()=>ArenaAudio.stats().music.status==='playing');ok('Arena button recovers music from saved lobby mute',await p.evaluate(()=>!state.musicOff&&saves>0));
  await p.evaluate(()=>state.sound=false);await p.waitForFunction(()=>ArenaAudio.stats().music.status==='sound-off');await p.waitForTimeout(550);await p.locator('#va-music-toggle')[mobile?'tap':'click']();await p.waitForFunction(()=>ArenaAudio.stats().music.status==='playing');ok('explicit enable button recovers global mute',await p.evaluate(()=>state.sound&&!state.musicOff));
  await p.evaluate(()=>VocabArena3D.stop());ok('entry and music controls have no runtime errors',errors.length===0);await context.close();
 }
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{const original=HTMLMediaElement.prototype.play;let once=true;HTMLMediaElement.prototype.play=function(){if(this.loop&&once){once=false;return Promise.reject(new DOMException('Gesture required','NotAllowedError'));}return original.call(this);};});const b=await blocked.newPage();await b.goto(base+'/entry');await b.click('#enter');await b.waitForFunction(()=>ArenaAudio.stats().music.status==='blocked');ok('autoplay rejection shows actionable tap state',await b.locator('#va-music-toggle').getAttribute('data-state')==='blocked');const start=Date.now();await b.click('#va-music-toggle');await b.waitForFunction(()=>ArenaAudio.stats().music.status==='playing',{},{timeout:3000});ok('gesture retry bypasses the old ten-second backoff',Date.now()-start<3000&&await b.evaluate(()=>ArenaAudio.stats().music.downloads===1));await b.evaluate(()=>VocabArena3D.stop());await blocked.close();
 const missing=await browser.newContext(),m=await missing.newPage();await m.route('**/*bgmusic-*',r=>r.fulfill({status:404,body:''}));await m.goto(base+'/entry');await m.click('#enter');await m.waitForFunction(()=>ArenaAudio.stats().music.status==='load');ok('download failure is visible instead of silent',await m.locator('#va-music-toggle').getAttribute('data-state')==='load');await m.unroute('**/*bgmusic-*');await m.click('#va-music-toggle');await m.waitForFunction(()=>ArenaAudio.stats().music.status==='playing',{},{timeout:3000});ok('retry control recovers download failure immediately',await m.evaluate(()=>ArenaAudio.stats().music.downloads===2));await m.evaluate(()=>VocabArena3D.stop());await missing.close();
 fs.writeFileSync(path.join(out,'entry-tests.json'),JSON.stringify({passed:checks.length,checks},null,2));console.log(JSON.stringify({passed:checks.length,checks}));
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
