'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const repo=path.resolve(process.env.SKM_ROOT||path.join(__dirname,'..')),deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const {chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
const out=process.env.SKM_OUT||path.join(require('os').tmpdir(),'wordskirmish-battle');fs.mkdirSync(out,{recursive:true});
const fixture=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/wordskirmish.css"><style>body{margin:0}</style><body><script>window.state={sound:false,coins:100,profileName:'Preview'};window.isAdmin=()=>true;window.vocabForStudent=()=>[['cat','แมว']];window.addCoins=()=>{};window.saveState=()=>{};window.Music={suspendBg(){},resumeBg(){}};window.onlineKey=()=>new URLSearchParams(location.search).get('uid')||'offline-test';window.wire={peers:{},sent:null};window.NetRoom={create:()=>({peers:wire.peers,send(p){wire.sent=p},join(){},leave(){},tick(){},statusText(){return 'ห้องทดสอบ'}})};</script><script src="/js/vendor/three.min.js"></script><script src="/js/wordskirmish-br.js"></script><script src="/js/wordskirmish-field.js"></script><script src="/js/wordskirmish.js"></script><script>WordSkirmish.open()</script>`;
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local');if(url.pathname==='/favicon.ico')return res.writeHead(204).end();if(url.pathname==='/preview')return res.writeHead(200,{'content-type':'text/html;charset=utf-8'}).end(fixture);const file=path.resolve(repo,'.'+url.pathname);if(!file.startsWith(repo+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'content-type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream'});res.end(e?'missing':b)});});
let checks=0;function ok(name,v){assert(v,name);console.log('PASS '+name);checks++;}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});const errors=[];
async function create(uid){const p=await browser.newPage({viewport:{width:812,height:375}});p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://127.0.0.1:${server.address().port}/preview?uid=${uid}`);await p.waitForFunction(()=>window.WordSkirmish?._t.playerMesh);if(uid==='solo'){for(const width of [812,667]){await p.setViewportSize({width,height:width===812?375:320});await p.waitForTimeout(70);const dialog=await p.evaluate(()=>{const c=document.querySelector('.skm-card'),r=c.getBoundingClientRect(),b=document.querySelector('#skm-training').getBoundingClientRect();return {fits:c.scrollHeight<=c.clientHeight&&r.top>=0&&r.bottom<=innerHeight&&b.bottom<=r.bottom,scroll:c.scrollHeight,client:c.clientHeight};});console.log('intro',width,dialog);ok('intro and both mode buttons fit without scrolling '+width,dialog.fits);}await p.setViewportSize({width:812,height:375});await p.waitForTimeout(70);}await p.evaluate(()=>WordSkirmish._t.setRunning(false));await p.waitForTimeout(70);await p.evaluate(()=>{window.testTime=200000;Date.now=()=>testTime;WordSkirmish._t.setRunning(true);});await p.locator('#skm-intro-ok').click();await p.evaluate(()=>{window.advance=ms=>{for(let i=0;i<ms;i+=50){testTime+=50;WordSkirmish._t.step(.05);}WordSkirmish._t.renderHud();WordSkirmish._t.renderer.render(WordSkirmish._t.scene,WordSkirmish._t.camera);};advance(1800);});return p;}
try{
 const p=await create('solo');await p.evaluate(()=>advance(10500));
 ok('solo round starts with seven living competitors',await p.evaluate(()=>{const t=WordSkirmish._t;return t.roundState.phase==='A'&&t.player.alive&&t.bots.filter(b=>b.alive).length===7;}));
 for(const size of [{width:1367,height:617},{width:812,height:375},{width:667,height:320}]){
  await p.setViewportSize(size);await p.waitForTimeout(100);await p.evaluate(()=>{WordSkirmish._t.step(.11);WordSkirmish._t.renderHud();WordSkirmish._t.renderer.render(WordSkirmish._t.scene,WordSkirmish._t.camera)});
  const layout=await p.evaluate(()=>{const b=[...document.querySelectorAll('.skm-float,.skm-joy')].filter(e=>getComputedStyle(e).display!=='none').map(e=>({id:e.id,r:e.getBoundingClientRect()}));const overlaps=[];for(let i=0;i<b.length;i++)for(let j=i+1;j<b.length;j++){const a=b[i].r,c=b[j].r;if(a.left<c.right&&a.right>c.left&&a.top<c.bottom&&a.bottom>c.top)overlaps.push([b[i].id,b[j].id]);}return {inside:b.every(({r})=>r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight),overlaps,draws:WordSkirmish._t.renderer.info.render.calls,triangles:WordSkirmish._t.renderer.info.render.triangles};});console.log(JSON.stringify({size,layout}));ok('all controls stay separate and on screen '+size.width,layout.inside&&!layout.overlaps.length);await sharp(await p.screenshot()).webp({quality:88}).toFile(path.join(out,'battle-'+size.width+'.webp'));
 }
 await p.setViewportSize({width:812,height:375});await p.waitForTimeout(100);

 const rigs=await p.evaluate(()=>{const t=WordSkirmish._t,failures=[];const old={x:t.player.x,z:t.player.z,yaw:t.player.yaw};for(const pose of ['stand','crouch','kneel','prone'])for(let i=0;i<8;i++){const m=t.playerMesh;m.position.set(0,0,0);m.rotation.set(0,i*Math.PI/4,0);t.poseChibi(m,{pose,alive:true,dodge:.8});m.updateMatrixWorld(true);let floor=Infinity;for(const part of m.userData.rig.support){const b=new THREE.Box3().setFromObject(part);floor=Math.min(floor,b.min.y);}if(floor<-.001||floor>.08)failures.push({pose,i,floor});}const spawns=Array.from({length:8},(_,i)=>{const a=i/8*Math.PI*2+Math.PI/8;return !t.homeBlocked(Math.sin(a)*37,Math.cos(a)*37)});t.setPlayer(old);t.step(.01);return {failures,spawns};});console.log('battle rigs',rigs);ok('rounded battle rigs remain grounded and all eight spawns are outside cover',!rigs.failures.length&&rigs.spawns.every(Boolean));
 const fire=await p.evaluate(()=>{const t=WordSkirmish._t,button=document.querySelector('#skm-fire'),before=t.inventory.ammo[0],r=button.getBoundingClientRect();window.testNow=performance.now();performance.now=()=>testNow;button.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:91,clientX:r.x+r.width/2,clientY:r.y+r.height/2}));for(let i=0;i<10;i++){testNow+=150;t.step(.05);}button.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:91,clientX:r.x+r.width/2+24,clientY:r.y+r.height/2+4}));button.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:91}));const after=t.inventory.ammo[0],pos=button.getBoundingClientRect(),look=t.setLook();testNow+=200;t.step(.1);return {used:before-after,stopped:after===t.inventory.ammo[0],samePosition:pos.x===r.x&&pos.y===r.y,look:look.lookYaw};});console.log(fire);ok('hold FIRE repeats, release stops, drag aims without moving HUD',fire.used>=9&&fire.stopped&&fire.samePosition);
 const inventory=await p.evaluate(()=>{const t=WordSkirmish._t;t.bots.forEach(b=>b.shotAt=Infinity);t.inventory.ammo[0]=0;t.inventory.reserve[0]=7;testNow+=300;const blocked=!t.fire();t.step(2);const loaded=t.inventory.ammo[0]===7&&t.inventory.reserve[0]===0;t.setPlayer({hp:20});t.healBattle();t.step(1);t.onKey({code:'KeyW'});t.step(.05);t.onKeyUp({code:'KeyW'});const cancelled=!t.inventory.action&&t.inventory.medkits===2;t.healBattle();t.step(3.1);return {blocked,loaded,cancelled,healed:t.player.hp===85&&t.inventory.medkits===1};});console.log(inventory);ok('empty magazine blocks shooting; finite reload and medkit channel work',Object.values(inventory).every(Boolean));
 const movement=await p.evaluate(()=>{const t=WordSkirmish._t;t.setPlayer({x:0,z:0});t.setLook(0,.28);t.onKey({code:'KeyW'});t.step(.1);const walk=-t.player.z;t.setPlayer({x:0,z:0});t.onKey({code:'ShiftLeft'});t.step(.1);const run=-t.player.z;t.onKeyUp({code:'KeyW'});t.onKeyUp({code:'ShiftLeft'});t.jumpBattle();t.step(.12);const height=t.jumpY;t.onKey({code:'KeyC',preventDefault(){}});const crouch=t.stance==='crouch';t.onKey({code:'KeyZ',preventDefault(){}});const prone=t.stance==='prone';for(let i=0;i<20;i++)t.step(.05);return {walk,run,height,landed:t.jumpY===0,crouch,prone};});console.log(movement);ok('sprint, jump/landing and independent crouch/prone controls',movement.run>movement.walk*1.45&&movement.height>0&&movement.landed&&movement.crouch&&movement.prone);
 const supply=await p.evaluate(()=>{const t=WordSkirmish._t,s=t.field.supplies.find(s=>s.id===1);t.setPlayer({x:s.x,z:s.z});t.step(.05);const unlocked=t.inventory.owned[1];t.selectWeapon(1);const ammo=t.inventory.reserve[1];t.step(.05);return unlocked&&t.inventory.weapon===1&&s.taken&&ammo===t.inventory.reserve[1];});ok('personal supply unlocks weapon and can only be collected once per round',supply);
 await p.locator('#skm-edit').click();const edit=await p.evaluate(()=>{const el=document.querySelector('#skm-fire'),r=el.getBoundingClientRect(),ammo=WordSkirmish._t.inventory.ammo[1];el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:92,clientX:r.x+30,clientY:r.y+30}));el.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:92,clientX:r.x+70,clientY:r.y+30}));el.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:92}));return el.getBoundingClientRect().x!==r.x&&ammo===WordSkirmish._t.inventory.ammo[1];});await p.locator('#skm-edit').click();ok('explicit HUD edit moves control without firing',edit);
 const scope=await p.evaluate(()=>{const t=WordSkirmish._t;t.setStance('stand');t.setPlayer({x:0,z:0});t.setLook(0,.28);t.setScope(true);t.cameraTick();t.renderHud();t.renderer.render(t.scene,t.camera);const point=t.resolveShot().target.clone().project(t.camera);return {zoom:Math.tan(t.FOV*Math.PI/360)/Math.tan(t.camera.fov*Math.PI/360),error:Math.hypot(point.x,point.y)};});ok('battle shoulder camera and scope share the exact centre aiming ray',Math.abs(scope.zoom-2.5)<1e-8&&scope.error<1e-7);await sharp(await p.screenshot()).webp({quality:88}).toFile(path.join(out,'battle-scope.webp'));
 const death=await p.evaluate(()=>{const t=WordSkirmish._t;t.battleDamage(1000,'test');const hp=t.player.hp;for(let i=0;i<80;i++)t.step(.05);return hp===0&&!t.player.alive&&!t.scoped&&!t.fire()&&t.player.respawnAt===0;});ok('elimination ends shooting/scope and never respawns inside active round',death);
 const victory=await p.evaluate(()=>{const t=WordSkirmish._t;t.setPlayer({alive:true,hp:100});t.bots.forEach(b=>{b.alive=false;b.mesh.visible=false});advance(2000);const win=t.roundState.phase==='F'&&t.roundState.winner===WordSkirmishBR.token(t.myUid),old=t.roundState.start;advance(8100);return win&&t.roundState.start>old&&t.roundState.phase==='W'&&t.player.hp===100;});ok('last survivor wins and a new round resets inventory/health automatically',victory);
 // Full runtime transport: two browsers exchange exactly the legacy NetRoom fields.
 const a=await create('alice'),b=await create('bob');
 async function exchange(ms){for(const page of [a,b])await page.evaluate(ms=>{testTime+=ms;WordSkirmish._t.step(.05)},ms);for(let i=0;i<4;i++){const packets=await Promise.all([a,b].map(page=>page.evaluate(()=>wire.sent)));await a.evaluate(packet=>{wire.peers.bob=packet;WordSkirmish._t.step(.05)},packets[1]);await b.evaluate(packet=>{wire.peers.alice=packet;WordSkirmish._t.step(.05)},packets[0]);}}
 await exchange(100);await exchange(12000);const rounds=await Promise.all([a,b].map(page=>page.evaluate(()=>({r:WordSkirmish._t.roundState,bots:WordSkirmish._t.bots.filter(b=>b.alive).length,x:WordSkirmish._t.player.x,z:WordSkirmish._t.player.z}))));console.log('network rounds',rounds);ok('two browser clients converge to one human-only active round',rounds[0].r.start===rounds[1].r.start&&rounds.every(v=>v.r.phase==='A'&&v.r.roster.length===2&&v.bots===0));
 ok('warm-up roster assigns different spawn positions',Math.hypot(rounds[0].x-rounds[1].x,rounds[0].z-rounds[1].z)>5);
 const repeated=await b.evaluate(()=>{const t=WordSkirmish._t,r=t.roundState,uid='alice',target=WordSkirmishBR.token(t.myUid),rec={ct:r.start};const event='R'+r.start.toString(36)+'.';t.inventory.armor=0;t.setPlayer({hp:100});t.applyBattleEvent(uid,rec,event+'1|H,'+target+',0,B');t.applyBattleEvent(uid,rec,event+'1|H,'+target+',0,B');const first=t.player.hp;t.applyBattleEvent(uid,rec,event+'2|H,'+target+',0,B;H,'+target+',0,B');const after=t.player.hp;t.applyBattleEvent('stranger',rec,event+'3|H,'+target+',2,H');return {first,after,blocked:t.player.hp===after};});console.log(repeated);ok('sequenced burst packets apply each hit once and reject nonparticipants',repeated.first===80&&repeated.after===40&&repeated.blocked);
 const late=await create('late');const networkTime=await a.evaluate(()=>testTime);await late.evaluate(now=>{testTime=now;WordSkirmish._t.startBattle();advance(1800)},networkTime);const packet=await a.evaluate(()=>wire.sent);const spectator=await late.evaluate(packet=>{wire.peers.alice=packet;for(let i=0;i<3;i++)WordSkirmish._t.step(.05);return {r:WordSkirmish._t.roundState,alive:WordSkirmish._t.player.alive}},packet);console.log('late',spectator);ok('late client adopts active round and waits without becoming a combatant',!spectator.r.admitted&&!spectator.alive&&spectator.r.phase==='A');

 const q=await create('full-solo');await q.evaluate(()=>advance(10500));
 const combat=await q.evaluate(()=>{
  const t=WordSkirmish._t;t.bots.forEach((b,i)=>{b.alive=i===0;b.mesh.visible=b.alive;b.shotAt=Infinity});const bot=t.bots[0];
  const actor=new THREE.Group(),target=new THREE.Mesh(new THREE.SphereGeometry(.16,12,8),new THREE.MeshBasicMaterial());actor.add(target);t.scene.add(actor);const dummy={mesh:actor,alive:true,hp:100,armor:0};actor.userData.skirmish=true;actor.userData.bot=dummy;target.userData.hit='body';t.bots.push(dummy);
  t.setPlayer({x:0,z:0,yaw:0});t.setLook(0,-.15);t.setStance('stand');t.setScope(true);t.cameraTick();t.camera.updateMatrixWorld();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),t.camera);actor.position.copy(ray.ray.at(8,new THREE.Vector3()));t.scene.updateMatrixWorld(true);
  let shotTime=1e9;performance.now=()=>shotTime;const samples=[];
  for(let i=0;i<3;i++){t.inventory.owned[i]=true;t.selectWeapon(i);dummy.hp=300;dummy.armor=0;dummy.alive=true;actor.visible=true;shotTime+=1000;const shot=t.fire();samples.push({i,shot,hp:dummy.hp,part:t.lastShotTrace.hit?.object===target});}
  // A lower eye-line and real solid container: muzzle cannot hit an opponent behind cover.
  t.bots.pop();t.scene.remove(actor);target.geometry.dispose();target.material.dispose();
  t.setPlayer({x:-10,z:-19,yaw:0});t.setLook(0,.28);t.setScope(false);t.setStance('stand');bot.x=-10;bot.z=-32;bot.mesh.position.set(bot.x,0,bot.z);bot.hp=100;bot.alive=true;bot.mesh.visible=true;t.poseChibi(bot.mesh,{alive:true});t.scene.updateMatrixWorld(true);shotTime+=1000;t.fire();const cover=bot.hp===100&&t.lastShotTrace.hit?.object.isInstancedMesh;
  // AI must also respect that container. Seed accuracy to guarantee a hit when unobstructed.
  const random=Math.random;Math.random=()=>0;t.inventory.armor=0;t.setPlayer({hp:100});bot.shotAt=0;t.step(.05);const protectedHp=t.player.hp;
  t.setPlayer({x:0,z:0,hp:100});bot.x=0;bot.z=-8;bot.shotAt=0;t.step(.05);const exposedHp=t.player.hp;Math.random=random;
  // Real zone damage bypasses armor, and an eliminated player stays out while bots finish.
  t.setPlayer({x:45,z:0,hp:100,alive:true});t.inventory.armor=50;bot.shotAt=Infinity;testTime=t.roundState.start+150000;t.step(1.01);const zone={hp:t.player.hp,armor:t.inventory.armor};
  return {samples,cover,protectedHp,exposedHp,zone};
 });console.log('combat geometry',combat);
 ok('all three weapons apply their damage through the actual centre ray',combat.samples.every((s,i)=>s.shot&&s.part&&s.hp===300-[20,14,60][i]));
 ok('solid container blocks player bullets and AI fire; exposed player takes damage',combat.cover&&combat.protectedHp===100&&combat.exposedHp<100);
 ok('outside-zone damage bypasses armor',combat.zone.hp<100&&combat.zone.armor===50);
 // A complete untouched solo match must terminate through AI/zone rules, without forcing a winner.
 const sim=await create('simulation');await sim.evaluate(()=>advance(10500));
 const completed=await sim.evaluate(()=>{const t=WordSkirmish._t,start=testTime,perf=performance.now();let maxDraws=0;for(let i=0;i<4500&&t.roundState.phase!=='F';i++){testTime+=50;t.step(.05);}t.renderHud();t.renderer.render(t.scene,t.camera);return {phase:t.roundState.phase,winner:t.roundState.winner,seconds:(testTime-start)/1000,computeMs:performance.now()-perf,alive:(t.player.alive?1:0)+t.bots.filter(b=>b.alive).length};});console.log('complete match',completed);ok('unassisted solo match finishes with at most one survivor',completed.phase==='F'&&completed.alive<=1&&completed.seconds<225);
 // The elected host may disconnect; the other runtime completes the same round.
 const failover=await a.evaluate(()=>{const t=WordSkirmish._t,old=t.roundState.start;delete wire.peers.bob;testTime+=3000;t.step(.05);return t.roundState.start===old&&t.roundState.phase==='F'&&t.roundState.winner===WordSkirmishBR.token(t.myUid);});ok('runtime host departure resolves surviving player without restarting active match',failover);
 ok('all browser runtime checks have no uncaught errors',errors.length===0);console.log('wordskirmish battle runtime ok '+checks+'; outputs '+out);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
