'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const repo=process.env.VW_ARENA_REPO||path.resolve(__dirname,'..'),root=process.env.VW_ARENA_SOURCE||repo;
const deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const {chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
const out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-swipe');fs.mkdirSync(out,{recursive:true});
const scripts=['vendor/three.min','arena-field-visuals','arena-elements','arena-spell-catalog','arena-strip','arena-grimoire','arena-relics','arena-portrait','arena-heroes','arena-maps','arena3d'];
const harness=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"><link rel="stylesheet" href="/css/arena-heroes.css"><style>body{margin:0}</style><script>window.state={profileName:'swipe-test',coins:1000000,arenaIntro:true,arenaHomeIntro:true,arenaItems:{},arenaHero:'fire',arenaMap:'crystal',sound:false,haptic:false};window.admin=false;window.isAdmin=()=>admin;window.saveState=()=>{};window.addCoins=n=>state.coins+=n;window.vocabForStudent=()=>[['cat','แมว']];window.activePet=()=>null;window.toast=()=>{};</script>${scripts.map(s=>'<script src="/js/'+s+'.js"></script>').join('')}`;
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/test'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(harness);}const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.svg')?'image/svg+xml':'application/octet-stream');fs.createReadStream(f).pipe(res);});
const checks=[],ok=(name,v)=>{assert.ok(v,name);checks.push(name);};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:812,height:375},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));const cdp=await page.context().newCDPSession(page);
async function gesture(sel){const box=await page.locator(sel).boundingBox(),x=box.x+box.width*.78,y=box.y+box.height*.3;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=12;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-i*22,y}]});await page.waitForTimeout(18);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(500);}
async function start(){await page.evaluate(async()=>{await ArenaMaps.prepare('crystal');VocabArena3D.start();});}
try{await page.goto('http://127.0.0.1:'+server.address().port+'/test');await start();await page.click('#va-shop-open');
ok('50 relics are continuous, no page buttons',await page.locator('[data-buy]').count()===50&&await page.locator('[data-relic-page]').count()===0);
const money=await page.evaluate(()=>state.coins);await gesture('#va-store-grid');ok('native touch pans relics without buying',await page.evaluate(n=>document.querySelector('#va-store-grid').scrollLeft>100&&state.coins===n,money));
await page.locator('#va-store-grid').evaluate(e=>e.scrollLeft=0);await page.waitForTimeout(150);const b=await page.locator('#va-store-grid').boundingBox();await page.mouse.move(b.x+b.width*.75,b.y+35);await page.mouse.down();await page.mouse.move(b.x+50,b.y+35,{steps:20});await page.mouse.up();await page.waitForTimeout(150);
ok('mouse drag scrolls without activating a card',await page.evaluate(n=>document.querySelector('#va-store-grid').scrollLeft>100&&state.coins===n,money));
await page.locator('#va-store-grid').focus();await page.keyboard.press('End');await page.waitForTimeout(1500);ok('keyboard End reaches final relic',await page.locator('[data-buy]').last().evaluate(e=>{const a=e.getBoundingClientRect(),s=e.parentElement.getBoundingClientRect();return a.right<=s.right+2&&a.left>=s.left;}));
const before=await page.locator('#va-store-grid').evaluate(e=>e.scrollLeft);await page.locator('[data-buy]').last().click();
ok('relic confirm sits on the open shop',await page.evaluate(()=>document.querySelector('#va-shop').classList.contains('on')&&document.querySelector('#va-buy-confirm').classList.contains('on')&&document.querySelector('#va-buy-title').textContent===ArenaRelics.items.at(-1).name));
await page.click('#va-buy-ok');ok('buying at the end preserves scroll and charges once',await page.evaluate(({before,money})=>{const i=ArenaRelics.items.at(-1);return state.arenaItems[i.id]&&state.coins===money-i.price&&Math.abs(document.querySelector('#va-store-grid').scrollLeft-before)<2;},{before,money}));
await page.fill('[aria-label="ค้นหาพลังอักษร"]','Prism');ok('search resets position and filters',await page.locator('[data-buy]').count()===1&&await page.locator('#va-store-grid').evaluate(e=>e.scrollLeft===0));
await page.fill('[aria-label="ค้นหาพลังอักษร"]','zzzz');ok('empty result remains readable',await page.locator('.va-relic-panel .va-spell-empty').isVisible());await page.fill('[aria-label="ค้นหาพลังอักษร"]','');
await page.evaluate(()=>{admin=true;VocabArena3D._t.refreshRelics();});await page.click('#va-shop-close');await page.click('#va-shop-open');await gesture('#va-store-grid');ok('owned admin cards still allow native touch scrolling',await page.locator('#va-store-grid').evaluate(e=>e.scrollLeft>100));
await page.click('#va-shop-close');await page.evaluate(()=>{admin=false;VocabArena3D._t.spellbook(true);});ok('60 spells are continuous, no page buttons',await page.locator('[data-equip-spell]').count()===60&&await page.locator('[data-page]').count()===0);await gesture('#va-spell-grid');ok('native touch pans spellbook',await page.locator('#va-spell-grid').evaluate(e=>e.scrollLeft>100));
await page.locator('#va-spell-grid').focus();await page.keyboard.press('End');await page.waitForTimeout(1500);ok('last spell can be reached',await page.locator('[data-equip-spell]').last().evaluate(e=>{const a=e.getBoundingClientRect(),s=e.parentElement.getBoundingClientRect();return a.right<=s.right+2&&a.left>=s.left;}));
await page.fill('[aria-label="ค้นหาเวทมนตร์"]','');await page.locator('[aria-label="ค้นหาเวทมนตร์"]').pressSequentially('web');ok('typing game shortcut letters does not close catalogs or route home',await page.locator('#va-spellbook').evaluate(e=>e.classList.contains('on'))&&await page.locator('#va-shop').evaluate(e=>!e.classList.contains('on')));await page.fill('[aria-label="ค้นหาเวทมนตร์"]','');
for(const [w,h] of [[1366,768],[812,375],[667,320],[390,844]]){await page.setViewportSize({width:w,height:h});for(const which of ['spells','relics']){await page.evaluate(which=>{VocabArena3D._t.spellbook(which==='spells');if(which==='relics')document.querySelector('#va-shop-open').click();else document.querySelector('#va-shop-close').click();},which);await page.waitForTimeout(120);const sel=which==='spells'?'.va-spell-panel':'.va-relic-panel';ok(which+' has no vertical overflow '+w+'x'+h,await page.locator(sel).evaluate(p=>{const r=p.getBoundingClientRect(),s=p.querySelector('.va-swipe-strip');return r.top>=0&&r.bottom<=innerHeight+1&&p.scrollHeight<=p.clientHeight+2&&s.scrollHeight<=s.clientHeight+2&&[...s.children].every(e=>e.scrollHeight<=e.clientHeight+2);}));await sharp(await page.screenshot()).webp({quality:90}).toFile(path.join(out,which+'-'+w+'.webp'));}}
await page.evaluate(()=>{VocabArena3D.stop();ArenaHeroes.choose(()=>Promise.resolve());});await page.setViewportSize({width:812,height:375});await page.waitForTimeout(150);await gesture('.ah-roster');ok('native touch pans hero roster without selecting',await page.evaluate(()=>document.querySelector('.ah-roster').scrollLeft>100&&document.querySelector('[aria-pressed="true"][data-hero]').dataset.hero==='fire'));
await page.locator('[data-hero="water"]').click();ok('tap selects hero after swipe',await page.locator('[data-hero="water"]').getAttribute('aria-pressed')==='true');await page.keyboard.press('ArrowLeft');ok('keyboard hero selection remains supported',await page.locator('[data-hero="gravity"]').getAttribute('aria-pressed')==='true');await page.click('#ah-back');ok('cleanup removes picker and game',await page.locator('#ah-picker,#va-root').count()===0);ok('no browser errors',errors.length===0);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors,out}));
}catch(e){console.error(e);await sharp(await page.screenshot()).webp({quality:90}).toFile(path.join(out,'failure.webp'));process.exitCode=1;}finally{await browser.close();server.close();}})();
