'use strict';
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const exists=p=>fs.existsSync(path.join(root,p));
let n=0;
const assert=(ok,msg)=>{ if(!ok){ console.error('FAIL',msg); process.exitCode=1; } else n++; };

const ns=read('minigames/vocab-force/vocab-force-namespace.js');
const manifest=read('minigames/vocab-force/animation/nex-animation-manifest.js');
const progress=read('minigames/vocab-force/vocabulary/letter-progress-controller.js');
const words=read('minigames/vocab-force/vocabulary/word-list.js');
const round=read('minigames/vocab-force/vocabulary/vocabulary-round-controller.js');
const tune=read('minigames/vocab-force/combat/combat-tune.js');
const secondaryTune=read('minigames/vocab-force/combat/secondary-impact-tune.js');
const dashTune=read('minigames/vocab-force/combat/dash-tune.js');
const combat=read('minigames/vocab-force/combat/combat-controller.js');
const runtime=read('minigames/vocab-force/runtime/vocab-force-runtime.js');
const audio=read('minigames/vocab-force/runtime/vocab-force-audio.js');
const secondaryCtrl=read('minigames/vocab-force/effects/secondary-impact-controller.js');
const impactFx=read('minigames/vocab-force/effects/impact-fx-manager.js');
const htmlPreview=read('minigames/vocab-force/index.html');
const css=read('minigames/vocab-force/css/vocab-force.css');
const ui=read('js/ui.js');
const home=read('js/home-v2.js');
const main=read('js/main.js');
const auth=read('js/auth.js');
const lobby=read('css/lobby.css');
const classic=read('index_classic.html');
const build=read('tools/build_web.mjs');

assert(exists('minigames/vocab-force/index.html'),'preview html');
assert(htmlPreview.includes('devPreview: true')||htmlPreview.includes('devPreview = true'),'isolated preview sets devPreview');
assert(!/<script[^>]+minigames\/vocab-force/.test(classic),'game scripts are not in lobby HTML');
assert(/\bid="btn-rail-vocabforce"[^>]*\bhidden\b/.test(classic),'classic rail starts hidden');
assert(classic.includes('Vocab Force'),'classic rail label');
assert(ui.includes('function refreshVocabForceLock')&&ui.includes('b.hidden=!ok'),'rail follows admin login');
assert(ui.includes("loadScriptOnce(base+'vocab-force-namespace.js')"),'lazy load from minigames folder');
assert(ui.includes('async function openVocabForce'),'lobby binder');
assert(main.includes("vocabforce:'#btn-rail-vocabforce'"),'go route');
assert(auth.includes('refreshVocabForceLock'),'auth refreshes lock');
assert(home.includes("'vocabforce'")&&/'vocabforce'/.test((home.match(/const ADMIN_ONLY_WORLD_ACTIONS = new Set\(\[([\s\S]*?)\]\)/)||[])[1]||''),'Home V2 hides card from non-admins');
assert(home.includes("['vocabforce','sparkle','Vocab Force','#btn-rail-vocabforce']"),'Home V2 card');
assert(lobby.includes('#btn-rail-vocabforce[hidden]'),'lobby hides locked rail');
assert(build.includes("'minigames/vocab-force/runtime/vocab-force-runtime.js'"),'production copies JS');
assert(build.includes('combat/dash-tune.js')&&htmlPreview.includes('combat/dash-tune.js')&&ns.includes("'combat/dash-tune.js'"),'dash tune is loaded');
assert(read('minigames/vocab-force/ui/vocab-force-hud.js').includes('data-vf-act="dash"'),'touch DASH');
assert(css.includes('.vf-dash')&&css.includes('env(safe-area-inset-right)'),'DASH button uses safe area');
assert(css.includes('.vf-act-ico')&&css.includes('border-radius:50%')&&css.includes('.vf-joy-chev'),'circular neon action buttons + d-pad stick');
assert(read('minigames/vocab-force/ui/vocab-force-hud.js').includes('vf-act-ico')&&read('minigames/vocab-force/ui/vocab-force-hud.js').includes('<svg'),'HUD uses icon buttons');
assert(css.includes("url('../map/arena-lot.jpg')"),'select screen uses night lot art');
assert(exists('minigames/vocab-force/map/arena-sky.jpg')&&exists('minigames/vocab-force/map/arena-ground.jpg')&&exists('minigames/vocab-force/map/arena-lot.jpg'),'night arena textures on disk');
assert(read('minigames/vocab-force/map/prototype-arena.js').includes('arena-sky.jpg')&&read('minigames/vocab-force/map/prototype-arena.js').includes('VFSky'),'arena loads sky cylinder');
assert(build.includes('map/arena-sky.jpg')&&build.includes('map/arena-ground.jpg')&&build.includes('map/arena-lot.jpg'),'production copies night arena textures');
assert(read('minigames/vocab-force/map/prototype-arena.js').includes('_placeSky')&&read('minigames/vocab-force/map/prototype-arena.js').includes('skyBand'),'sky band uses undistorted aspect');
assert(read('minigames/vocab-force/controls/vocab-force-input.js').includes("e.code === 'KeyE'")&&read('minigames/vocab-force/controls/vocab-force-input.js').includes('k.KeyQ'),'E dashes, Q still blocks');
assert(ns.includes("'combat/combat-tune.js'")&&ns.includes("'effects/motion-trail-manager.js'"),'lazy script order includes tune + trails');
assert(htmlPreview.includes('combat/combat-tune.js')&&htmlPreview.includes('effects/motion-trail-manager.js'),'preview loads tune + trails');
assert(!build.includes('nex_walk.glb')&&!build.includes('characters/next/animations'),'28MB duplicate GLBs are not in the production copy list');
assert(!build.includes('zom_Elderly_Shaky_Walk_in.glb')&&!build.includes('characters/zom/animations'),'zombie 36MB GLBs are not in the production copy list');
assert(build.includes('enemies/zombie-enemy.js')&&ns.includes("'enemies/zombie-enemy.js'")&&htmlPreview.includes('enemies/zombie-enemy.js'),'zombie enemy is loaded');
assert(!ns.includes('demon-enemy.js')&&!htmlPreview.includes('demon-enemy.js')&&!read('minigames/vocab-force/enemies/enemy-manager.js').includes('DemonEnemy'),'old demon is not the active enemy');
assert(css.includes('#vf-game')&&css.includes('env(safe-area-inset-bottom)'),'overlay + safe areas');
assert(css.includes('data-vf-act')||read('minigames/vocab-force/ui/vocab-force-hud.js').includes('data-vf-act="punch"'),'touch ATTACK');
assert(read('minigames/vocab-force/ui/vocab-force-hud.js').includes('data-vf-act="kick"'),'touch KICK');
assert(read('minigames/vocab-force/ui/vocab-force-hud.js').includes('data-vf-act="jump"'),'touch JUMP');
assert(read('minigames/vocab-force/ui/vocab-force-hud.js').includes('data-vf-act="block"'),'touch BLOCK');
assert(runtime.includes('addCoins')||round.includes('addCoins(VF.LETTER_REWARD)'),'central coins');
assert(ns.includes('LETTER_REWARD = 1000'),'1000 coin reward');
assert(manifest.includes('nex_walk.glb')&&manifest.includes('Right_Jab_from_Guard')&&manifest.includes('Step_in_High_Kick')&&manifest.includes('Block1'),'real clip names');
assert(manifest.includes('Walking.001'),'idle uses leftover pose because no idle GLB exists');
assert(read('minigames/vocab-force/character/nex-asset-loader.js').includes('disposeScene'),'clip-only GLBs dispose extra meshes');
assert(read('minigames/vocab-force/animation/nex-animation-controller.js').includes('AnimationMixer'),'one mixer');
assert(!runtime.includes('GTA')&&!css.includes('superman'),'no licensed-game labels');
assert(ns.includes("'combat/secondary-impact-tune.js'")&&ns.includes("'effects/secondary-impact-controller.js'"),'secondary impact scripts in namespace');
assert(ns.includes("'combat/breakable-wall-tune.js'")&&ns.includes("'effects/breakable-wall-controller.js'"),'breakable wall scripts in namespace');
assert(htmlPreview.includes('combat/breakable-wall-tune.js')&&htmlPreview.includes('effects/breakable-wall-controller.js'),'preview loads breakable walls');
assert(build.includes('combat/breakable-wall-tune.js')&&build.includes('effects/breakable-wall-controller.js'),'production copies breakable wall JS');
assert(htmlPreview.includes('combat/secondary-impact-tune.js')&&htmlPreview.includes('effects/secondary-impact-controller.js'),'preview loads secondary impact');
assert(build.includes('combat/secondary-impact-tune.js')&&build.includes('effects/secondary-impact-controller.js'),'production copies secondary impact JS');
assert(impactFx.includes('burstFinisher')&&impactFx.includes("'ichor'")&&impactFx.includes("'chunk'"),'pooled burst fragments');
assert(read('minigames/vocab-force/enemies/zombie-enemy.js').includes('beginBurst')&&read('minigames/vocab-force/enemies/zombie-enemy.js').includes('rewardAt'),'burst hides mesh after locking letter spawn');
assert(runtime.includes('rewardAt')&&runtime.includes('en.letter'),'letter reward uses enemy state, not corpse-in-wall');
assert(!/blood|dismember|splatter/i.test(combat+tune+runtime+audio+impactFx+secondaryTune+secondaryCtrl+read('minigames/vocab-force/combat/rapid-finisher-tune.js')+read('minigames/vocab-force/combat/breakable-wall-tune.js')+read('minigames/vocab-force/effects/breakable-wall-controller.js')+read('minigames/vocab-force/combat/energy-attack-tune.js')+read('minigames/vocab-force/combat/energy-attack-controller.js')+read('minigames/vocab-force/effects/energy-projectile-manager.js')),'no gore language');
assert(audio.includes('punchWhoosh')&&audio.includes('kickImpact')&&audio.includes('enemyLaunch')&&audio.includes('AUDIO_HOOKS'),'replaceable combat sound hooks');
assert(audio.includes('zombieWallImpactExtreme')&&audio.includes('zombieGroundImpactHeavy')&&audio.includes('shockwaveImpact')&&audio.includes('debrisImpact'),'secondary impact sound hooks');
assert(audio.includes('rapidComboHit')&&audio.includes('zombieBurstFinisher')&&audio.includes('zombieBurstFragments'),'rapid burst audio hooks');
assert(ns.includes("'combat/energy-attack-tune.js'")&&ns.includes("'combat/energy-attack-controller.js'")&&ns.includes("'effects/energy-projectile-manager.js'"),'energy attack scripts in namespace');
assert(htmlPreview.includes('combat/energy-attack-tune.js')&&htmlPreview.includes('effects/energy-projectile-manager.js')&&htmlPreview.includes('combat/energy-attack-controller.js'),'preview loads energy attack');
assert(build.includes('combat/energy-attack-tune.js')&&build.includes('effects/energy-projectile-manager.js')&&build.includes('combat/energy-attack-controller.js'),'production copies energy attack JS');
assert(audio.includes('energyCharge')&&audio.includes('energyFire')&&audio.includes('energyHit')&&audio.includes('energyFinalHit')&&audio.includes('energyWallImpact'),'energy attack sound hooks');
assert(runtime.includes('handleAttackPress')&&runtime.includes('EnergyAttackController')&&runtime.includes('punchHeld'),'runtime routes ATTACK through energy when out of melee');
assert(css.includes('.vf-punch.is-armed')&&css.includes('.vf-energy-charge'),'ATTACK button shows ranged-arm pulse and hold charge bar');
assert(!/kamehameha|spirit.?bomb|destructo|dragon.?ball|goku/i.test(read('minigames/vocab-force/combat/energy-attack-tune.js')+read('minigames/vocab-force/combat/energy-attack-controller.js')+read('minigames/vocab-force/effects/energy-projectile-manager.js')),'energy attack uses original naming');
assert(exists('sound/vocab-force/Vocab_force_bgm.mp3'),'Vocab Force BGM file is on disk');
assert(audio.includes("file: 'Vocab_force_bgm.mp3'")&&audio.includes("dir: '/sound/vocab-force/'")&&audio.includes("hash: '005fca63b9391f66'"),'BGM uses content-hash cache key');
assert(audio.includes("caches.open('vw-assets-content-v1')")&&audio.includes('/__vw_asset__')&&audio.includes("preload = 'none'")&&audio.includes('createObjectURL'),'BGM reuses Cache Storage blob playback');
assert(audio.includes('loop = true')&&!/new Audio\([^)]*Vocab_force_bgm/.test(audio),'BGM loops from blob, not a raw mp3 URL player');
assert(runtime.includes('VF.audio.startBgm')&&runtime.includes("classList.add('is-selecting')"),'BGM starts on the select/loading screen');
assert(runtime.includes('VF.audio.stopBgm')&&read('minigames/vocab-force/ui/character-select.js').includes('audio.startBgm'),'BGM stops on exit and retries after a tap');
assert(build.includes("sound/vocab-force/Vocab_force_bgm.mp3"),'production copies the BGM file');
assert(!classic.includes('Vocab_force_bgm')&&!home.includes('Vocab_force_bgm'),'lobby does not preload Vocab Force BGM');
assert(ns.includes("'ui/letter-quest-marker.js'")&&htmlPreview.includes('ui/letter-quest-marker.js')&&build.includes('ui/letter-quest-marker.js'),'quest marker is loaded');
assert(css.includes('.vf-quest-arrow')&&css.includes('.vf-need'),'quest arrow + next-letter HUD styles');
assert(runtime.includes('nearestLetter')&&runtime.includes('hud.quest'),'runtime aims quest arrow at next letter');
assert(read('minigames/vocab-force/ui/vocab-force-hud.js').includes('vf-need'),'HUD highlights the next letter in the word');
assert(read('minigames/vocab-force/ui/vocab-force-hud.js').includes('vf-energy-charge')&&read('minigames/vocab-force/ui/vocab-force-hud.js').includes('setEnergyCharge'),'HUD energy charge bar');
assert(ns.includes("'ui/character-select.js'")&&htmlPreview.includes('ui/character-select.js')&&build.includes('ui/character-select.js'),'character select is loaded');
assert(ns.includes("'character/playable-roster.js'")&&ns.includes("'animation/lyravyn-animation-manifest.js'"),'playable roster + Lyravyn manifest load');
assert(css.includes('.vf-select-card')&&css.includes('.vf-select-start')&&htmlPreview.includes('character-select.js'),'select screen styles');
assert(css.includes('object-fit:contain')&&css.includes('max-height:500px'),'select screen fits short phone viewports');
assert(css.includes('max-width:min(42vw,280px)')&&css.includes('@media(max-height:520px)'),'target-word banner is compact');
assert(css.includes('.vf-word small{display:none}'),'short screens hide TARGET WORD kicker');
assert(css.includes('.vf-sound')&&css.includes('.vf-sound.is-off'),'sound toggle switch styles');
assert(read('minigames/vocab-force/ui/vocab-force-hud.js').includes('role="switch"')&&read('minigames/vocab-force/ui/vocab-force-hud.js').includes('toggleMuted'),'HUD sound switch');
assert(audio.includes("vocabForce.sound")&&audio.includes('toggleMuted')&&audio.includes('bgm.muted'),'VF mute persists locally');
assert(runtime.includes('CharacterSelect')&&runtime.includes('picker.wait')&&runtime.includes('is-selecting'),'game waits for character select');
assert(read('minigames/vocab-force/ui/character-select.js').includes('disabled'),'START stays disabled until a character is chosen');
assert(exists('minigames/vocab-force/ui/portraits/nex.png')&&exists('minigames/vocab-force/ui/portraits/lyravyn.png'),'select portraits copied into Vocab Force');
assert(build.includes('ui/portraits/nex.png')&&build.includes('ui/portraits/lyravyn.png'),'production copies select portraits');
assert(!build.includes('ly_Run.glb')&&!build.includes('characters/Lyravyn/animations'),'Lyravyn 33MB GLBs are not in the production copy list');

const animDir=path.join(root,'minigames/vocab-force/characters/next/animations');
const glbs=fs.readdirSync(animDir).filter(f=>/\.glb$/i.test(f)).sort();
assert(glbs.length>=21,'21+ NEX GLBs on disk');
['nex_walk.glb','nex_Walk_Backward.glb','nex_Standard_Forward_Char.glb','nex_Right_Jab_from_Guard.glb','nex_Step_in_High_Kick.glb','nex_Block1.glb','nex_Vault_and_Land.glb','nex_Hop_with_Arms_Raised.glb'].forEach(f=>{
  assert(glbs.includes(f),'required V1 file '+f);
});
const zomDir=path.join(root,'minigames/vocab-force/characters/zom/animations');
const zomGlbs=fs.readdirSync(zomDir).filter(f=>/\.glb$/i.test(f)).sort();
assert(zomGlbs.length===3,'exactly three zombie GLBs on disk');
['zom_Elderly_Shaky_Walk_in.glb','zom_Scream.glb','zom_Fall3.glb'].forEach(f=>{
  assert(zomGlbs.includes(f),'required zombie file '+f);
});
const lyraDir=path.join(root,'minigames/vocab-force/characters/Lyravyn/animations');
const lyraGlbs=fs.readdirSync(lyraDir).filter(f=>/\.glb$/i.test(f)).sort();
assert(lyraGlbs.length===8,'exactly eight Lyravyn GLBs on disk');
['ly_Backflip_and_Hooks.glb','ly_Confident_Strut.glb','ly_Dive_Down_and_Land_2.glb','ly_Elbow_Strike.glb','ly_Fall2.glb','ly_Power_Spin_Jump.glb','ly_Roundhouse_Kick.glb','ly_Run.glb'].forEach(f=>{
  assert(lyraGlbs.includes(f),'required Lyravyn file '+f);
});

const sandbox={window:{},console,localStorage:{store:{},getItem:function(k){ return Object.prototype.hasOwnProperty.call(this.store,k)?this.store[k]:null; },setItem:function(k,v){ this.store[k]=String(v); }}};
sandbox.window=sandbox;
sandbox.globalThis=sandbox;
vm.createContext(sandbox);
vm.runInContext(ns, sandbox);
vm.runInContext(manifest, sandbox);
vm.runInContext(read('minigames/vocab-force/animation/lyravyn-animation-manifest.js'), sandbox);
vm.runInContext(read('minigames/vocab-force/character/playable-roster.js'), sandbox);
vm.runInContext(read('minigames/vocab-force/enemies/zom-animation-manifest.js'), sandbox);
vm.runInContext(words, sandbox);
vm.runInContext(progress, sandbox);
vm.runInContext(round, sandbox);
vm.runInContext(tune, sandbox);
vm.runInContext(read('minigames/vocab-force/combat/energy-attack-tune.js'), sandbox);
vm.runInContext(secondaryTune, sandbox);
vm.runInContext(read('minigames/vocab-force/combat/breakable-wall-tune.js'), sandbox);
vm.runInContext(dashTune, sandbox);
vm.runInContext(read('minigames/vocab-force/combat/rapid-finisher-tune.js'), sandbox);
vm.runInContext(combat, sandbox);
vm.runInContext(read('minigames/vocab-force/effects/breakable-wall-controller.js'), sandbox);
vm.runInContext(secondaryCtrl, sandbox);
vm.runInContext(read('minigames/vocab-force/map/prototype-arena.js'), sandbox);
vm.runInContext(read('minigames/vocab-force/character/nex-character-controller.js'), sandbox);
vm.runInContext(read('minigames/vocab-force/camera/third-person-camera.js'), sandbox);
vm.runInContext(read('minigames/vocab-force/ui/letter-quest-marker.js'), sandbox);
vm.runInContext(read('minigames/vocab-force/enemies/enemy-manager.js'), sandbox);
const VF=sandbox.window.VocabForce;
assert(VF.adminAllowed()===false,'closed to non-admin by default');
VF.devPreview=true;
assert(VF.adminAllowed()===true,'dev preview opens');
const spec=VF.NexManifest.spec;
assert(spec('walk').file==='nex_walk.glb'&&spec('punch').clip==='Right_Jab_from_Guard','manifest maps real files');
assert(spec('kick').file==='nex_Step_in_High_Kick.glb','kick file');
assert(spec('run').clip==='Standard_Forward_Charge_inplace','run uses charge clip');
assert(spec('dash').file==='nex_Standard_Forward_Char.glb'&&spec('dash').clip==='Standard_Forward_Charge_inplace','dash fallback is charge clip, not a new GLB');
assert(!glbs.some(function(f){ return /dash/i.test(f); }),'no dedicated dash GLB on disk');
assert(spec('idle').clip==='Walking.001','idle mapping');
assert(spec('jump').file==='nex_Hop_with_Arms_Raised.glb','jump uses hop clip');
const lspec=VF.LyraManifest.spec;
assert(lspec('run').file==='ly_Run.glb'&&lspec('run').clip==='Running','Lyravyn run mapping');
assert(lspec('idle').clip==='Running.001','Lyravyn idle uses leftover run pose');
assert(lspec('walk').file==='ly_Run.glb'&&lspec('walk').timeScale<1,'Lyravyn walk falls back to slowed run');
assert(lspec('punch').file==='ly_Elbow_Strike.glb'&&lspec('kick').file==='ly_Roundhouse_Kick.glb','Lyravyn punch/kick mapping');
assert(lspec('jump').clip==='360_Power_Spin_Jump'&&lspec('vault').file==='ly_Dive_Down_and_Land_2.glb','Lyravyn jump/vault mapping');
assert(lspec('victory').file==='ly_Backflip_and_Hooks.glb'&&lspec('fall').file==='ly_Fall2.glb','Lyravyn victory/fall mapping');
assert(!lspec('block'),'Lyravyn has no block GLB');
assert(VF.LyraManifest.boneCount===28&&VF.LyraManifest.files.length===8,'Lyravyn mixamorig 28 bones, eight files');
assert(VF.PlayableRoster.get('nex').displayName==='NEX'&&VF.PlayableRoster.get('lyravyn').displayName==='Lyravyn','roster names');
assert(VF.PlayableRoster.save('lyravyn')&&VF.PlayableRoster.readSaved()==='lyravyn','selection persists in localStorage');
assert(VF.PlayableRoster.get('lyravyn').getManifest()===VF.LyraManifest,'Lyravyn roster uses LyraManifest');
assert(VF.PlayableRoster.get('nex').getManifest()===VF.NexManifest,'NEX roster uses NexManifest');
const zspec=VF.ZomManifest.spec;
assert(zspec('walk').file==='zom_Elderly_Shaky_Walk_in.glb'&&zspec('walk').clip==='Elderly_Shaky_Walk_inplace','zombie walk mapping');
assert(zspec('scream').file==='zom_Scream.glb'&&zspec('scream').clip==='Zombie_Scream','zombie scream mapping');
assert(zspec('fall').file==='zom_Fall3.glb'&&zspec('fall').clip==='Fall3','zombie fall mapping');
assert(zspec('idle').clip==='Elderly_Shaky_Walk_inplace.001','zombie idle uses leftover walk pose');
assert(VF.ZomManifest.boneCount===28&&VF.ZomManifest.skeleton==='mixamorig','shared mixamorig 28 bones');
const fwd=VF.cameraWish(0,0,1), back=VF.cameraWish(0,0,-1), right=VF.cameraWish(0,1,0), left=VF.cameraWish(0,-1,0);
assert(fwd.z>0.9 && Math.abs(fwd.x)<0.01,'W / up stays world forward');
assert(back.z<-0.9 && Math.abs(back.x)<0.01,'S / down is opposite forward, not a reverse clip');
assert(right.x<-0.9 && Math.abs(right.z)<0.01,'D / stick-right follows screen right');
assert(left.x>0.9 && Math.abs(left.z)<0.01,'A / stick-left follows screen left');
assert(!read('minigames/vocab-force/character/nex-character-controller.js').includes("play('walkBack')"),'backward uses walk/run facing down');
const cam=new VF.ThirdPersonCamera();
const startPitch=cam.pitch;
cam.look(0,-80);
assert(cam.pitch<startPitch,'finger up looks up');
cam.pitch=startPitch;
cam.look(0,80);
assert(cam.pitch>startPitch,'finger down looks down');
const p=VF._t.makeProgress('APPLE','แอปเปิล');
assert(p.required()==='A'&&p.display()==='_ _ _ _ _','start progress');
assert(p.collect('P').ok===false&&p.required()==='A','wrong letter does not advance');
assert(p.collect('A').ok===true&&p.display()==='A _ _ _ _','first letter');
assert(p.collect('P').ok===true&&p.collect('P').ok===true,'double P in order');
assert(p.collect('L').ok===true&&p.collect('E').complete===true,'APPLE complete');
assert(p.collect('X').reason==='done','no extra after complete');
const onMark=VF._t.questAnchor(0,0.2,false,800,400,50);
assert(onMark.on===true&&onMark.rot===0,'on-screen arrow points down at the letter');
const offMark=VF._t.questAnchor(1.6,0,false,800,400,50);
assert(offMark.on===false&&offMark.x>=748,'off-screen arrow clamps to the edge');
const backMark=VF._t.questAnchor(0.4,0,true,800,400,50);
assert(backMark.on===false,'behind-camera target stays an edge arrow');
const EM=new VF.EnemyManager();
EM.list=[
  {letter:'B',x:9,z:0,state:'idle'},
  {letter:'A',x:5,z:0,state:'idle'},
  {letter:'A',x:1.2,z:0,state:'idle'},
  {letter:'A',x:0,z:0,state:'gone',_collected:true}
];
assert(EM.nearestLetter('A',0,0).x===1.2,'arrow picks the nearest required letter');
assert(!EM.nearestLetter('Z',0,0),'no arrow for a letter that is not spawned');
const letters=VF.WordList.encounterLetters('APPLE',3);
assert(letters.filter(ch=>ch==='P').length>=2&&letters.length===8,'needed letters plus distractors');
const imp=VF._t.combatImpulse(90,{x:3,z:4});
assert(Math.hypot(imp.x,imp.z)<=VF.CombatTune.VELOCITY_CAP+0.01,'knockback capped');
assert(VF._t.combatImpulse(10,{x:0,z:1}).z===10,'impulse uses force not a tiny default');
const punchTune=VF.CombatTune.attack('punch'), kickTune=VF.CombatTune.attack('kick');
assert(punchTune.hitStop>=0.06 && punchTune.hitStop<=0.09,'punch hit-stop 60-90ms');
assert(kickTune.hitStop>=0.10 && kickTune.hitStop<=0.15,'kick hit-stop 100-150ms');
assert(kickTune.hitStop>punchTune.hitStop,'kick freezes longer than punch');
assert(kickTune.force>=40 && kickTune.lift>=7 && kickTune.cameraShake>punchTune.cameraShake,'kick launches and shakes harder than punch');
assert(VF.CombatTune.level('HEAVY').knockback>VF.CombatTune.level('MEDIUM').knockback,'kick level launches harder');
assert(VF.CombatTune.HIT_STOP_MAX<=0.18,'hit-stop never stays frozen');
const punchDist=VF._t.estimateLaunch('MEDIUM'), kickDist=VF._t.estimateLaunch('HEAVY');
assert(punchDist>=4 && punchDist<=10,'punch travels several meters');
assert(kickDist>punchDist && kickDist>=8 && kickDist<=16,'kick launches farther, still clamped');
assert(VF.RapidFinisher.requiredHits===3&&VF.RapidFinisher.windowSeconds===1,'rapid finisher is 3 hits in 1s');
assert(VF.RapidFinisher.hitStopMs===70&&VF.RapidFinisher.slowMotionMs===110,'finisher hit-stop/slow-mo stay short');
assert(VF.RapidFinisher.fragmentCount===10&&VF.RapidFinisher.ichorCount===14&&VF.RapidFinisher.maxLive===2,'pooled fragment caps');
const zA={}, zB={};
assert(VF._t.noteRapidHit(zA,0,'punch')===false,'first confirmed hit is not a finisher');
assert(VF._t.noteRapidHit(zA,320,'punch')===false,'second hit still charging');
assert(VF._t.noteRapidHit(zB,400,'kick')===false,'hits on another zombie do not share the window');
assert(VF._t.noteRapidHit(zA,780,'kick')===true,'punch+punch+kick inside 1s triggers');
assert(zA.rapidHitCount===3&&zB.rapidHitCount===1,'windows stay per zombie');
const zC={};
VF._t.noteRapidHit(zC,0,'punch');
VF._t.noteRapidHit(zC,650,'punch');
assert(VF._t.noteRapidHit(zC,1200,'kick')===false,'hit after 1.2s slides the oldest punch out');
assert(zC.rapidHitCount===2,'sliding window keeps only hits inside 1s');
zC.burstFinisherTriggered=true;
assert(VF._t.noteRapidHit(zC,1300,'kick')===false,'finisher cannot retrigger on the same zombie');
const side=VF._t.resolveHitDir({x:0,z:1},{x:0,z:0},{x:2,z:0.2},'front');
assert(Math.abs(side.x)>0.3,'side hit flies sideways');
const mockPlayer={
  x:0,y:0,z:0,vx:0,vz:0,
  anim:{isBusy:function(){return false;}},
  playAction:function(){return true;},
  forward:function(){return {x:0,z:1};},
  drive:function(n){ this.vx += n; }
};
let hurt=0, lastInfo=null;
const mockEnemies={hurtInSphere:function(origin,radius,info){
  hurt++; lastInfo=info;
  return [{x:0,y:1,z:1}];
}};
const C=new VF.CombatController();
const atk=C.tryAttack('punch', mockPlayer, 0);
assert(atk && atk.hitAt>0 && hurt===0,'damage waits for impact frame');
assert(mockPlayer.vx>0,'punch drives NEX forward at startup');
const early=C.tick(0.016, 100, mockPlayer, mockEnemies, null, null, null);
assert(early.hits.length===0 && hurt===0,'no hit before punch impact');
const camHit={fov:52, baseFov:52, shake:0, impulse:function(s,f){ this.shake=s; this.fovAdd=f; }};
const late=C.tick(0.016, atk.hitAt, mockPlayer, mockEnemies, null, camHit, null);
assert(late.hits.length===1 && lastInfo.kind==='punch','punch connects on impact frame');
assert(C.hitStop>=0.06 && C.hitStop<=0.09,'punch hit-stop applied');
assert(camHit.shake>0 && camHit.fovAdd>=3 && camHit.fovAdd<=7,'punch camera shake + FOV');
C.tick(0.08, atk.hitAt+80, mockPlayer, mockEnemies, null, camHit, null);
assert(C.hitStop===0,'hit-stop recovers');
hurt=0;
const kickAt=C.tryAttack('kick', mockPlayer, 1000);
C.tick(0.016, kickAt.hitAt, mockPlayer, mockEnemies, null, camHit, null);
assert(lastInfo.kind==='kick' && C.hitStop>=0.10 && C.hitStop<=0.15,'kick impact + longer hit-stop');
assert(camHit.fovAdd>=3 && camHit.fovAdd<=8,'kick FOV punch stays brief');
assert(VF.LETTER_REWARD===1000,'coin reward unchanged');
const ET=VF.EnergyAttackTune;
assert(ET.doubleTapWindowMs===1000&&ET.projectileCount===3&&ET.projectileIntervalMs===85,'energy burst 3 orbs / 1s window');
assert(ET.holdChargeMs===3000&&ET.chargedScale===5&&ET.tapReleaseMaxMs<=250,'hold ATTACK 3s charges 5x orbs');
assert(ET.projectileSpeed===42&&ET.maxRange===32&&ET.pool===9&&ET.maxLive<=6,'energy speed/range/pool');
assert(ET.damagePerProjectile===1&&ET.knockbackPerProjectile===18&&ET.lastProjectileKnockbackMultiplier===1.3,'energy damage/knockback');
assert(Math.abs(VF._t.meleeHurtRadius('punch')-(1.28+1.92*0.15))<0.001,'melee guard uses punch hurt sphere');
assert(VF._t.energyHoldFrac(0,0)===0&&VF._t.energyHoldFrac(0,1500)===0.5&&VF._t.energyHoldFrac(0,3000)===1&&VF._t.energyHoldFrac(0,4000)===1,'charge bar fills over 3s');
assert(VF._t.energyHoldRelease(0,180).tap&&!VF._t.energyHoldRelease(0,180).charged,'short release stays a tap');
assert(VF._t.energyHoldRelease(0,800).charged&&!VF._t.energyHoldRelease(0,800).tap&&Math.abs(VF._t.energyHoldRelease(0,800).frac-800/3000)<0.001,'partial hold fires at current charge');
assert(VF._t.energyHoldRelease(0,3000,true).charged&&!VF._t.energyHoldRelease(0,3000,true).tap,'full charge does not also tap');
assert(Math.abs(VF._t.energyChargeScale(0)-1)<0.001&&Math.abs(VF._t.energyChargeScale(0.5)-3)<0.001&&VF._t.energyChargeScale(1)===5,'orb size scales 1x to 5x with charge');
let tap=VF._t.energyTapResult([],0);
assert(!tap.fire&&tap.taps.length===1,'first tap arms only');
assert(VF._t.energyTapResult(tap.taps,20).bounce,'sub-45ms bounce is ignored');
const fired=VF._t.energyTapResult(tap.taps,400);
assert(fired.fire&&fired.taps.length===0,'second tap inside 1s fires');
const resetTap=VF._t.energyTapResult([0],1100);
assert(!resetTap.fire&&resetTap.taps[0]===1100,'tap after 1s starts a new window');
const nearList={list:[{alive:true,x:0,y:0,z:1.1,radius:0.7}]};
const farList={list:[{alive:true,x:0,y:0,z:12,radius:0.7}]};
assert(VF._t.hasMeleeTarget(mockPlayer,nearList,'punch'),'zombie in punch sphere is melee');
assert(!VF._t.hasMeleeTarget(mockPlayer,farList,'punch'),'distant zombie is not melee');
const energyCalls=[];
const energyMock={noteTap:function(){ energyCalls.push('tap'); return {armed:true}; }, beginHold:function(){ energyCalls.push('hold'); return {holding:true}; }, cancel:function(){ energyCalls.push('cancel'); }};
C.handleAttackPress('punch', mockPlayer, 4000, nearList, null, null, null, energyMock);
assert(energyCalls.indexOf('tap')<0 && energyCalls.indexOf('hold')<0 && energyCalls.indexOf('cancel')>=0,'melee range cancels energy and stays melee');
energyCalls.length=0;
C.handleAttackPress('punch', mockPlayer, 5000, farList, null, null, null, energyMock);
assert(energyCalls[0]==='tap','out of melee mouse ATTACK arms energy');
energyCalls.length=0;
C.handleAttackPress('punch', mockPlayer, 6000, farList, null, null, null, energyMock, null, {hold:true});
assert(energyCalls[0]==='hold','held ATTACK button starts a charge, not a tap');
assert(VF._t.energyPalette({def:{id:'lyravyn'}}).core!==VF._t.energyPalette({def:{id:'nex'}}).core,'NEX and Lyravyn energy colors differ');
assert(read('minigames/vocab-force/effects/energy-projectile-manager.js').includes('applyHit')&&!read('minigames/vocab-force/effects/energy-projectile-manager.js').includes('noteRapidHit'),'energy kills use applyHit, not the 3-hit finisher window');
const ST=VF.SecondaryImpactTune;
assert(ST.SPEED.none===7.5&&ST.SPEED.medium===14&&ST.SPEED.heavy===24&&ST.SPEED.extreme===36,'secondary speed thresholds');
assert(ST.classify(2)===null&&ST.classify(8)==='LIGHT'&&ST.classify(18)==='MEDIUM'&&ST.classify(28)==='HEAVY'&&ST.classify(40)==='EXTREME','classify LIGHT-EXTREME');
assert(ST.kind('wall',40,0)==='EXTREME_IMPACT'&&ST.kind('wall',20,0)==='WALL_IMPACT','wall kinds');
assert(ST.kind('ground',28,26)==='HEAVY_GROUND_SLAM'&&ST.kind('ground',16,4)==='GROUND_IMPACT','ground kinds');
assert(ST.cameraFalloff(0)>0.95&&ST.cameraFalloff(20)<0.08,'camera shake falls off with distance');
assert(ST.spec('LIGHT').shake===0&&ST.spec('EXTREME').shake>ST.spec('HEAVY').shake,'extreme camera exceeds heavy');
assert(ST.spec('EXTREME').hitStop>=0.06&&ST.spec('EXTREME').hitStop<=0.12,'extreme hit-stop 60-120ms class');
assert(ST.spec('EXTREME').slowMo>=0.06&&ST.spec('EXTREME').slowMo<=0.12,'extreme slow-mo 60-120ms');
assert(ST.spec('LIGHT').hitStop===0&&ST.spec('MEDIUM').slowMo===0,'no slow-mo on small hits');
assert(ST.POOL.dust<=40&&ST.POOL.decal===ST.DECAL_MAX&&ST.MAX_LIVE<=72&&ST.DECAL_LIFE<=2,'pooled caps');
const walker={airborneHit:false,launchLeft:0,recover:0,alive:true,_wallTouch:false,_wallCool:0};
assert(!VF._t.wallImpactArmed(walker,2,true),'walking into a wall does not arm huge FX');
const launched={airborneHit:true,launchLeft:8,recover:0.4,alive:true,_wallTouch:false,_wallCool:0};
assert(VF._t.wallImpactArmed(launched,22,true),'launched wall crash arms once');
assert(!VF._t.wallImpactArmed(launched,22,true),'still touching the wall does not re-arm');
assert(!VF._t.wallImpactArmed(launched,22,false)&&launched._wallTouch===false,'leaving the wall clears latch');
launched._wallCool = 0.48;
assert(VF._t.wallImpactArmed(launched,22,true)===false,'cooldown blocks spam after first crash');
const grounded={airborneHit:false,launchLeft:0,recover:0,alive:true,_groundCool:0};
assert(!VF._t.groundImpactArmed(grounded,3,0),'idle standing does not slam');
assert(VF._t.groundImpactArmed({airborneHit:true,launchLeft:4,recover:0.2,alive:true,_groundCool:0},30,12),'launched fall slams');
const S=new VF.SecondaryImpactController();
const camFar={shake:0,impulse:function(s,f){ this.shake=s; this.fov=f; }};
const fxLog=[];
const mockFx={wallImpact:function(ev,spec){ fxLog.push({surface:'wall',level:ev.level,x:ev.x,nx:ev.nx}); },groundImpact:function(ev){ fxLog.push({surface:'ground',level:ev.level}); },launchTrail:function(){ fxLog.push({trail:true}); },trailBurst:function(){ fxLog.push({burst:true}); }};
const combatMock={hitStop:0};
S.handle({surface:'wall',x:0,y:1,z:0,nx:1,ny:0,nz:0,speed:40,vx:40,vy:2,vz:0,enemy:{}}, {x:0,z:0}, combatMock, camFar, mockFx, null);
assert(fxLog[0]&&fxLog[0].surface==='wall'&&fxLog[0].nx===1,'wall FX uses contact normal');
assert(combatMock.hitStop>=0.06&&S.slowT>0,'extreme wall sets hit-stop + slow-mo');
assert(camFar.shake>0.7,'near extreme wall shakes hard');
const camDist={shake:0,impulse:function(s){ this.shake=s; }};
S.handle({surface:'wall',x:40,y:1,z:0,nx:1,ny:0,nz:0,speed:40,vx:40,vy:0,vz:0,enemy:{}}, {x:0,z:0}, {hitStop:0}, camDist, mockFx, null);
assert(camDist.shake<0.2,'far extreme wall barely shakes');
S.handle({surface:'ground',x:0,y:0,z:0,nx:0,ny:1,nz:0,speed:18,fall:8,vx:8,vy:-10,vz:0,enemy:{}}, {x:0,z:0}, {hitStop:0}, {impulse:function(){}}, mockFx, null);
assert(fxLog.some(function(e){ return e.surface==='ground' && e.level==='MEDIUM'; }),'medium ground uses ground FX');
assert(impactFx.includes('wallImpact')&&impactFx.includes('_placeDecal')&&impactFx.includes('launchTrail'),'pooled wall/ground/trail FX exist');
assert(read('minigames/vocab-force/enemies/zombie-enemy.js').includes('pendingImpacts')&&read('minigames/vocab-force/enemies/enemy-manager.js').includes('impacts'),'zombie emits secondary impacts');
assert(read('minigames/vocab-force/enemies/zombie-enemy.js').includes('canShatterWall')&&read('minigames/vocab-force/enemies/zombie-enemy.js').includes('throughKeep'),'launched zombie can punch through a shattered panel');
assert(impactFx.includes('wallShatter')&&impactFx.includes("'shard'"),'pooled wall shards');
assert(read('minigames/vocab-force/map/prototype-arena.js').includes('{breakable: true}')&&read('minigames/vocab-force/map/prototype-arena.js').includes('b.broken'),'arena marks a few panels breakable and skips them after shatter');
const BW=VF.BreakableWallTune;
assert(BW.shatterSpeed===16&&BW.extremeSpeed===28,'breakable wall speed thresholds');
assert(VF._t.breakableTier(10)===null&&VF._t.breakableTier(16)==='HEAVY'&&VF._t.breakableTier(28)==='EXTREME','shatter tiers');
assert(!VF._t.canShatterWall({breakable:false,broken:false},40),'solid walls never shatter');
assert(!VF._t.canShatterWall({breakable:true,broken:false},10),'low-speed contact does not shatter');
const panel={breakable:true,broken:false,mesh:{visible:true}};
assert(VF._t.canShatterWall(panel,20),'hard launched impact can shatter a flagged panel');
assert(VF._t.breakWall(panel)&&panel.broken&&panel.mesh.visible===false,'intact mesh hides on break');
assert(!VF._t.canShatterWall(panel,40)&&!VF._t.breakWall(panel),'already-broken panels do not shatter again');
const smashArena=new VF.PrototypeArena();
smashArena.boxes=[{minx:-1.6,maxx:1.6,miny:0,maxy:2.8,minz:-0.6,maxz:0.6,breakable:true,broken:false,platform:false,vault:false,mesh:{visible:true}}];
const smashHit=smashArena.collide(0,1,1.2,0.8);
assert(smashHit.wall&&smashHit.hitBox&&smashHit.hitBox.breakable,'collide reports the breakable hitBox');
VF._t.breakWall(smashHit.hitBox);
const smashOpen=smashArena.collide(0,1,1.2,0.8);
assert(!smashOpen.hitBox&&!smashOpen.wall,'broken panel becomes a passable opening');
const edgeArena=new VF.PrototypeArena();
edgeArena.boxes=[];
const edgeHit=edgeArena.collide(30,1,0,0.5);
assert(edgeHit.wall&&!edgeHit.hitBox,'map-edge clamp is not a breakable panel');
const skyBand=VF._t.skyBand(76,1280,446,3);
assert(skyBand.wraps===3&&skyBand.crop===0.58&&skyBand.height>24&&skyBand.height<45,'city skyline band keeps photo aspect');
assert(Math.abs((Math.PI*2*skyBand.radius/skyBand.wraps)/skyBand.height - 1280/(446*skyBand.crop))<0.02,'sky cylinder is not stretched');
const shatterFx=[];
const wallCtrl=new VF.BreakableWallController();
const camBreak={shake:0,fov:0,impulse:function(s,f){ this.shake=s; this.fov=f; }};
const livePanel={breakable:true,broken:false,mesh:{visible:true}};
assert(wallCtrl.tryShatter({surface:'wall',box:livePanel,speed:20,x:0,y:1,z:0,nx:1,nz:0},{wallShatter:function(){ shatterFx.push('heavy'); }},camBreak,{hitStop:0},null,{x:0,z:0}));
assert(livePanel.broken&&shatterFx[0]==='heavy'&&camBreak.shake>0.5&&camBreak.fov>4,'heavy shatter FX + camera');
assert(!wallCtrl.tryShatter({surface:'wall',box:livePanel,speed:40,x:0,y:1,z:0,nx:1,nz:0},{wallShatter:function(){ shatterFx.push('again'); }},null,null,null,{x:0,z:0}),'one shatter per wall');
assert(shatterFx.length===1,'no shatter spam');
const solidPanel={breakable:false,broken:false,mesh:{visible:true}};
assert(!wallCtrl.tryShatter({surface:'wall',box:solidPanel,speed:40,x:0,y:1,z:0,nx:1,nz:0},{wallShatter:function(){ shatterFx.push('solid'); }},null,null,null,{x:0,z:0}),'unflagged walls stay intact');
S.handle({surface:'wall',x:0,y:1,z:0,nx:1,ny:0,nz:0,speed:30,vx:30,vy:1,vz:0,enemy:{},box:{breakable:true,broken:false,mesh:{visible:true}}},{x:0,z:0},{hitStop:0},{impulse:function(){}},{wallShatter:function(){ shatterFx.push('wired'); },wallImpact:function(){ shatterFx.push('regular'); }},null);
assert(shatterFx.indexOf('wired')>=0&&shatterFx.indexOf('regular')<0,'shatter replaces regular wall FX');
assert(BW.POOL.shard<=32&&BW.maxLive<=3&&BW.shardLife<=0.8,'pooled shard caps');
assert(BW.cameraShake===0.92&&BW.extremeShake===1.2&&BW.fovPunch===5.6&&BW.extremeFov===7.4,'shatter camera values');
assert(BW.slowMo===0.09&&BW.slowScale===0.34&&BW.hitStop===0.07&&BW.extremeHitStop===0.1,'shatter hit-stop / slow-mo');
const DT=VF.DashTune;
assert(DT.dashDuration>=0.12 && DT.dashDuration<=0.22,'manual dash 120-220ms');
assert(DT.dashDistance>=3 && DT.dashDistance<=6,'manual dash 3-6m');
assert(DT.dashCooldown>=0.6 && DT.dashCooldown<=1.2,'dash cooldown 0.6-1.2s');
assert(DT.dashFovBoost>=4 && DT.dashFovBoost<=8,'dash FOV +4 to +8');
assert(DT.attackApproachMinGap>=1.5 && DT.attackApproachMaxGap<=4,'approach gap 1.5-4m');
const dashP=new VF.NexCharacterController();
dashP.ready=true;
dashP.anim={play:function(){return true;},isBusy:function(){return false;},busyUntil:0,has:function(){return true;},tick:function(){}};
assert(dashP.beginDash({dirX:0,dirZ:1,distance:4.6,duration:0.16,now:0}));
assert(dashP.isDashing()&&dashP.mode==='dash','dash is a real controller state');
dashP.tick(0.16,{moveX:0,moveZ:0},{yaw:0},null);
assert(!dashP.isDashing(),'dash ends');
assert(dashP.z>4.2 && dashP.z<5.1,'manual dash travels several meters');
assert(!dashP.tryManualDash({moveX:0,moveZ:1},{yaw:0},null,null,null,400),'cooldown blocks spam');
assert(dashP.tryManualDash({moveX:0,moveZ:1},{yaw:0},null,null,null,900),'cooldown recovers');
dashP.tick(0.2,{moveX:0,moveZ:0},{yaw:0},null);
const planNear=VF._t.approachPlan({x:0,y:0,z:0,yaw:0,radius:0.55,forward:function(){return {x:0,z:1};}},{list:[{alive:true,x:0,z:4}] },'punch',null);
assert(planNear && planNear.close>=1.5 && planNear.close<=4,'approach triggers just outside melee');
assert(!VF._t.approachPlan({x:0,y:0,z:0,yaw:0,radius:0.55,forward:function(){return {x:0,z:1};}},{list:[{alive:true,x:0,z:20}] },'punch',null),'no blink across the arena');
assert(!VF._t.approachPlan({x:0,y:0,z:0,yaw:0,radius:0.55,forward:function(){return {x:0,z:1};}},{list:[{alive:true,x:0,z:1.4}] },'punch',null),'no approach inside melee');
const wallArena={collide:function(x,y,z){ return {x:x,y:y,z:Math.min(z,0.9)}; }};
assert(!VF._t.dashPathClear(wallArena,0,0,0,0,1,4,0.55),'dash does not phase major walls');
const ap=new VF.NexCharacterController();
ap.ready=true;
ap.anim={play:function(){return true;},isBusy:function(){return false;},busyUntil:0,has:function(){return true;},tick:function(){}};
assert(C.tryAttackOrApproach('punch', ap, 2000, {list:[{alive:true,x:0,z:4}]}, null, null, null).approach,'attack approach dash starts');
ap.tick(0.14,{moveX:0,moveZ:0},{yaw:0},null);
assert(ap.consumeDashAttack()==='punch','approach chains into punch');
let paid=0;
sandbox.addCoins=function(n){ paid+=n; };
sandbox.state={coins:10};
const R=new VF.VocabularyRoundController();
R.start({w:'CAT',th:'แมว'});
R.onLetter('C'); R.onLetter('A'); R.onLetter('T');
assert(R.creditIfComplete()===1000&&paid===1000,'pays through addCoins');
assert(R.settle()===0,'does not double-pay');

if(process.exitCode){
  console.error('vocab-force tests failed after',n,'passes');
}else{
  console.log('vocab-force tests ok',n);
}
