'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),cp=require('child_process');
const repo=path.resolve(__dirname,'..'),root=path.resolve(process.env.VW_ARENA_SOURCE||repo),out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-fire-1390'),deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'),{chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
fs.mkdirSync(out,{recursive:true});const old=cp.execFileSync('git',['show','26f7684e:js/arena-field-visuals.js'],{cwd:repo,encoding:'utf8'});
const harness=legacy=>'<!doctype html><html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"><body><script>window.state={profileName:"admin",coins:16343652,arenaIntro:true,arenaHomeIntro:true,arenaItems:{},arenaHero:"fire",arenaMap:"sky",sound:false,haptic:false};window.isAdmin=()=>true;window.saveState=()=>{};window.addCoins=n=>state.coins+=n;window.vocabForStudent=()=>[["baby","ทารก"]];window.activePet=()=>null;window.toast=()=>{};</script>'+['vendor/three.min','arena-field-visuals','arena-elements','arena-spell-catalog','arena-strip','arena-grimoire','arena-relics','arena-heroes','arena-maps','arena3d'].map(n=>'<script src="'+(legacy&&n==='arena-field-visuals'?'/old.js':'/js/'+n+'.js')+'"></script>').join('')+'</body></html>';
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/favicon.ico'){res.statusCode=204;return res.end();}if(u.pathname==='/test'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(harness(u.searchParams.has('old')));}if(u.pathname==='/old.js'){res.setHeader('Content-Type','text/javascript');return res.end(old);}const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.avif')?'image/avif':f.endsWith('.webp')?'image/webp':'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[],checks=[],costs=[];const ok=(name,value)=>{assert.ok(value,name);checks.push(name);};page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
async function setup(map,legacy=false,low=false){await page.goto('http://127.0.0.1:'+server.address().port+'/test'+(legacy?'?old=1':''));await page.evaluate(async({map,low})=>{state.arenaMap=map;state.noAnim=low;await ArenaMaps.prepare(map);VocabArena3D.start();const t=VocabArena3D._t;t.player().pos.set(0,0,3);t.bots.forEach((b,i)=>{b.group.position.set((i%3-1)*3,0,-5-Math.floor(i/3)*2);b.hp=b.maxHp=100000;b.attackAt=performance.now()+600000;});t.resize();t.spellbook(true);document.querySelector('#va-spellbook').style.display='none';window.fireTime=0;}, {map,low});await page.waitForTimeout(250);}
async function cast(){await page.evaluate(async()=>{const t=VocabArena3D._t;await t.equip(0,'fire');t.spellbook(false);t.cast('fire');t.spellbook(true);document.querySelector('#va-spellbook').style.display='none';});}
async function advance(to){return page.evaluate(to=>{const t=VocabArena3D._t;while(fireTime+.016<to){t.frame(16);fireTime+=.016;}t.frame((to-fireTime)*1000);fireTime=to;return t.stats();},to);}
try{
await setup('sky',true);await cast();await advance(.75);await sharp(await page.screenshot()).webp({quality:90}).toFile(path.join(out,'before.webp'));
for(const map of ['sky','crystal','forest']){await setup(map);await cast();for(const t of [.12,.4,.8,1.6,2.9,3.8,4.8]){const s=await advance(t);costs.push({map,t,...s});ok(map+' pool bounded at '+t,s.fx.active<=640&&s.fx.meshes===48);await sharp(await page.screenshot()).webp({quality:90}).toFile(path.join(out,map+'-'+t+'.webp'));}ok(map+' no damage after fire expires',await page.evaluate(()=>VocabArena3D._t.elementStats().active===0));}
await page.setViewportSize({width:812,height:375});await setup('sky',false,true);await cast();const low=await advance(.8);ok('low-power uses original 256 particle / 28 mesh cap',low.fx.particles===256&&low.fx.meshes===28);await sharp(await page.screenshot()).webp({quality:90}).toFile(path.join(out,'mobile-low.webp'));
const isolated=await page.evaluate(()=>{const s=new THREE.Scene(),fx=ArenaFieldVisuals.createFx(s,false);fx.element('fire',new THREE.Vector3(),{r:7.4,life:3.4});fx.tick(.8);const plumes=s.children.filter(o=>o.material?.isShaderMaterial&&o.rotation.x>-.5);const values=plumes.map(o=>{o.onBeforeRender();return {seed:o.material.uniforms.seed.value,fade:o.material.uniforms.fade.value,mode:o.material.uniforms.mode.value};});fx.tick(2.5);const fading=plumes.filter(o=>o.visible).map(o=>{o.onBeforeRender();return o.material.uniforms.fade.value;});fx.tick(2);const still=s.children.filter(o=>o.isMesh&&o.visible).length;fx.dispose();return {values,fading,still,children:s.children.length};});
ok('shared shader receives distinct phase per plume',new Set(isolated.values.map(v=>v.seed)).size>4);ok('smoke and fire have separate shader modes',isolated.values.some(v=>v.mode===1)&&isolated.values.some(v=>v.mode===0));ok('fire opacity reaches shader during dissipation',isolated.fading.some(f=>f>0&&f<.5));ok('all fire meshes expire and dispose',isolated.still===0&&isolated.children===0);
await page.setViewportSize({width:1366,height:768});await setup('sky');await page.evaluate(()=>{const t=VocabArena3D._t;for(let i=0;i<5;i++)t.collect(t.drops.indexOf(t.crystalNodes[i].drop));t.spellbook(false);t.cast('ult');t.spellbook(true);document.querySelector('#va-spellbook').style.display='none';});await advance(.8);await sharp(await page.screenshot()).webp({quality:90}).toFile(path.join(out,'mega.webp'));ok('MEGA still consumes one charge',await page.evaluate(()=>VocabArena3D._t.megaUses===4));
if(process.env.VW_ARENA_VIDEO==='1'){
 const context=await browser.newContext({viewport:{width:1280,height:720},recordVideo:{dir:out,size:{width:1280,height:720}}}),vp=await context.newPage();vp.on('pageerror',e=>errors.push(e.message));vp.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await vp.goto('http://127.0.0.1:'+server.address().port+'/test');await vp.evaluate(async()=>{await ArenaMaps.prepare('sky');VocabArena3D.start();const t=VocabArena3D._t;t.player().pos.set(0,0,4);t.bots.forEach((b,i)=>{const a=i/8*Math.PI*2;b.group.position.set(Math.cos(a)*6,0,-7+Math.sin(a)*6);b.hp=b.maxHp=999;b.attackAt=performance.now()+600000;});t.resize();t.equip(0,'fire');});await vp.waitForTimeout(350);
 await vp.evaluate(()=>VocabArena3D._t.cast('fire'));await vp.waitForTimeout(4600);
 await vp.evaluate(()=>{const t=VocabArena3D._t;for(let i=0;i<5;i++)if(t.crystalNodes[i].drop)t.collect(t.drops.indexOf(t.crystalNodes[i].drop));t.cast('ult');});await vp.waitForTimeout(4500);
 await vp.evaluate(()=>VocabArena3D.stop());const video=vp.video();await context.close();fs.copyFileSync(await video.path(),path.join(out,'fire-in-game.webm'));
}

ok('no JavaScript or shader errors',errors.length===0);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({passed:checks.length,checks,costs,errors},null,2));console.log(JSON.stringify({passed:checks.length,costs,errors,out}));
}finally{await page.evaluate(()=>window.VocabArena3D?.stop()).catch(()=>{});await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
