'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),vm=require('vm'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),root=path.resolve(process.env.VW_ARENA_SOURCE||repo),out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-maps');fs.mkdirSync(out,{recursive:true});
const deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'),{chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
const checks=[],ok=(n,v)=>{assert.ok(v,n);checks.push(n);},wait=ms=>new Promise(r=>setTimeout(r,ms));
async function multiplayer(){
 const ctx={console,performance,setTimeout,clearTimeout,setInterval,clearInterval,document:{getElementById:()=>null}};ctx.window=ctx;
 for(const file of ['tools/fakedb.js','js/netroom.js','js/arena-maps.js'])vm.runInNewContext(fs.readFileSync(path.join(file.startsWith('tools')?repo:root,file),'utf8'),ctx,{filename:file});
 await ctx.FakeDB.install();ctx.NetRoom.CFG.VERIFY_MS=1;const players=[];
 function join(uid,map){ctx.onlineKey=()=>uid;const seen={};let room;room=ctx.NetRoom.create({map:'adv',roomMax:4,...ctx.ArenaMaps.roomOptions(map),push:()=>room.send({n:uid,x:0,z:0,yaw:0,hp:'A2|100|0|0'},true),onPeer:(u,d)=>seen[u]=d,onPeerGone:u=>delete seen[u]});room.uid=uid;room.seen=seen;room.join();players.push(room);return room;}
 for(const map of ['sky','crystal','forest'])for(let i=0;i<4;i++){const room=join(map+i,map);await wait(12);ok(map+i+' joins group 1 matching map',room.joined&&room.room===21+['sky','crystal','forest'].indexOf(map));}
 const fifth=join('next-sky','sky');await wait(30);ok('all three full opens next group automatically',fifth.joined&&fifth.room===24);
 const nextCrystal=join('next-crystal','crystal');await wait(25);ok('selected crystal map remains crystal in group 2',nextCrystal.room===25);
 ok('no cross-map peers or boss transport',players.filter(p=>p.room===21).every(p=>Object.keys(p.seen).every(u=>u.startsWith('sky'))));
 ok('friend navigation cannot cross map lane',!(await fifth.goToRoom(25)).ok);ok('friend navigation cannot enter legacy arena',!(await fifth.goToRoom(0)).ok);
 players[4].leave();await wait(15);const blocked=join('blocked-sky','sky');await wait(25);ok('selected full map waits while another map has space',blocked.full&&!blocked.joined);
 for(const p of players)p.leave();ctx.FakeDB.reset();
 const now=Date.now();ctx.FakeDB.seed('winfo/adv/r21',{ghost:{t:now-95000,j:1}});const ghost=join('fresh','sky');await wait(25);ok('stale seats do not fill a map',ghost.joined&&ghost.room===21);ghost.leave();ctx.FakeDB.reset();
 const pending=join('cancelled','forest');pending.leave();await wait(25);ok('leaving during admission cannot reattach',!pending.joined);
 ctx.FakeDB.reset();const race=[];for(let i=0;i<7;i++)race.push(join('race'+i,'sky'));await wait(35);for(const p of race){ctx.onlineKey=()=>p.uid;p._verify();}await wait(35);for(const p of race){ctx.onlineKey=()=>p.uid;p._verify();}await wait(35);
 ok('simultaneous arrivals settle at four seats',race.filter(p=>p.joined).length===4&&race.filter(p=>p.full).length===3);for(const p of race)p.leave();
 const all=await ctx.ArenaMaps.availability(async()=>4,'forest');ok('capacity exhaustion is explicit and bounded',all.exhausted&&all.idx===-1);
 ok('total map range stays inside existing r0..r35 rules',ctx.ArenaMaps.FIRST+ctx.ArenaMaps.GROUPS*3-1===35);
}
const harness=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"></head><body><button id="open">เลือกแผนที่</button><script>window.state={profileName:'admin',coins:16338327,arenaIntro:true,arenaHomeIntro:true,arenaItems:{},arenaHero:'meteor',sound:false,haptic:false};window.allowed=true;window.isAdmin=()=>allowed;window.saveState=()=>{};window.addCoins=n=>state.coins+=n;window.vocabForStudent=()=>[['purple','สีม่วง']];window.activePet=()=>null;window.toast=()=>{};</script><script src="/js/vendor/three.min.js"></script><script src="/js/arena-field-visuals.js"></script><script src="/js/arena-elements.js"></script><script src="/js/arena-spell-catalog.js"></script><script src="/js/arena-strip.js"></script><script src="/js/arena-grimoire.js"></script><script src="/js/arena-relics.js"></script><script src="/js/arena-heroes.js"></script><script src="/js/arena-maps.js"></script><script src="/js/arena3d.js"></script><script>document.querySelector('#open').onclick=async()=>{window.chosen=await ArenaMaps.choose();if(chosen)VocabArena3D.start();};</script></body></html>`;
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/test'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(harness);}const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.avif')?'image/avif':f.endsWith('.webp')?'image/webp':f.endsWith('.svg')?'image/svg+xml':'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await multiplayer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1366,height:768},hasTouch:true}),errors=[],requests=[],costs={};page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(new URL(r.url()).pathname));
 try{await page.goto(`http://127.0.0.1:${server.address().port}/test`);await page.evaluate(()=>{allowed=false;});await page.click('#open');ok('non-admin opens map picker',await page.locator('#va-map-picker').count()===1);await page.keyboard.press('Escape');await page.evaluate(()=>{allowed=true;});await page.click('#open');await page.waitForFunction(()=>!document.querySelector('#vam-play').disabled);
  ok('picker loads only thumbnails before confirmation',requests.filter(p=>/^\/img\/arena-maps\//.test(p)).every(p=>p.endsWith('-thumb.webp')));
  for(const [width,height] of [[1366,768],[812,375],[667,320],[390,844]]){await page.setViewportSize({width,height});ok('picker fits '+width+'x'+height,await page.evaluate(()=>[...document.querySelectorAll('#va-map-picker button,#va-map-picker footer')].every(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.top>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1&&e.scrollWidth<=e.clientWidth+2&&e.scrollHeight<=e.clientHeight+2;})));await sharp(await page.screenshot()).webp({quality:88}).toFile(path.join(out,'picker-'+width+'.webp'));}
  await page.keyboard.press('Escape');ok('cancel closes picker without entering arena',await page.locator('#va-root').count()===0);
  for(const id of ['sky','crystal','forest']){await page.setViewportSize({width:1366,height:768});await page.click('#open');await page.click('[data-map="'+id+'"]');await page.waitForFunction(()=>!document.querySelector('#vam-play').disabled);const before=requests.length;await page.click('#vam-play');await page.waitForFunction(()=>window.VocabArena3D._t.running);await page.waitForFunction(()=>VocabArena3D._t.ground()?.material.map.image?.complete);
   ok(id+' selected art and room map persisted',await page.evaluate(id=>state.arenaMap===id&&VocabArena3D._t.map()===id,id));ok(id+' downloads no unselected full plate',requests.slice(before).filter(p=>/^\/img\/arena-maps\/(sky|crystal|forest)\.(avif|webp)$/.test(p)).every(p=>p.includes('/'+id+'.')));
   await page.evaluate(()=>{const t=VocabArena3D._t;t.player().pos.set(0,0,0);t.bots.forEach((b,i)=>{const a=i/t.bots.length*Math.PI*2;b.group.position.set(Math.cos(a)*11,0,Math.sin(a)*11);b.attackAt=performance.now()+600000;b.hp=b.maxHp=100;});t.resize();});
   for(const [w,h] of [[1366,768],[812,375],[667,320]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(80);const geometry=await page.evaluate(()=>{const t=VocabArena3D._t,cam=t.camera(),pos=t.player().pos,wide=innerWidth/innerHeight>1.8,ref=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,120);ref.position.set(pos.x,wide?33:36,pos.z+(wide?20:23));ref.lookAt(pos.x,0,pos.z-2.3);ref.updateMatrixWorld();const expected=new THREE.Vector3(pos.x,2.2,pos.z).project(ref),actual=t.project({x:pos.x,y:2.2,z:pos.z});return {cameraMatch:cam.isPerspectiveCamera&&cam.fov===48&&Math.abs(cam.position.y-(wide?33:36))<.01&&actual.distanceTo(expected)<.001,worldFloor:!!t.ground()&&!document.querySelector('.va-map-art'),bounds:[...document.querySelectorAll('#va-root .va-top button,#va-home-nav,#va-map-change,#va-spells-open,#va-root .va-skill')].every(e=>{const r=e.getBoundingClientRect();return r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;}),cost:t.stats()};});ok(id+' HUD fits '+w+'x'+h,geometry.bounds);ok(id+' camera matches original height distance FOV and character projection',geometry.cameraMatch);ok(id+' ground is attached to world instead of screen',geometry.worldFloor);costs[id]=geometry.cost;await sharp(await page.screenshot()).webp({quality:89}).toFile(path.join(out,id+'-'+w+'.webp'));}
   const beforeMove=await page.evaluate(()=>VocabArena3D._t.player().pos.x);await page.keyboard.down('KeyD');await page.waitForTimeout(250);await page.keyboard.up('KeyD');ok(id+' movement remains live',await page.evaluate(x=>VocabArena3D._t.player().pos.x>x+.1,beforeMove));ok(id+' camera follows movement',await page.evaluate(x=>VocabArena3D._t.camera().position.x>x+.03,beforeMove));
   await page.setViewportSize({width:1366,height:768});for(const [side,x,z] of [['east',27,0],['north',0,-27]]){await page.evaluate(([x,z])=>{const t=VocabArena3D._t;t.player().pos.set(x,0,z);t.resize();},[x,z]);await page.waitForTimeout(70);await sharp(await page.screenshot()).webp({quality:89}).toFile(path.join(out,id+'-edge-'+side+'.webp'));}
   await page.evaluate(()=>{const t=VocabArena3D._t;for(let i=0;i<5;i++)t.collect(t.drops.indexOf(t.crystalNodes[i].drop));t.cast('ult');});await page.waitForTimeout(200);ok(id+' MEGA five-use counter survives reskin',await page.evaluate(()=>VocabArena3D._t.megaUses===4));await sharp(await page.screenshot()).webp({quality:89}).toFile(path.join(out,id+'-mega.webp'));
   await page.evaluate(()=>{VocabArena3D.stop();state.arenaHome.cargo=[];});ok(id+' exit removes scene and ambience',await page.locator('#va-root,.va-map-ambience').count()===0);
  }
  await page.evaluate(async()=>{await ArenaMaps.prepare('sky');state.arenaMap='sky';VocabArena3D.start();const t=VocabArena3D._t;t.drop(new THREE.Vector3(0,0,0),'A',0x55eaff);t.collect(t.drops.length-1);});
  await page.evaluate(()=>VocabArena3D._t.complete());const earned=await page.evaluate(()=>VocabArena3D._t.sessionCoins);
  const carried=await page.evaluate(()=>VocabArena3D._t.cargo.join(''));await page.click('#va-map-change');await page.click('[data-map="forest"]');await page.waitForFunction(()=>!document.querySelector('#vam-play').disabled);await page.click('#vam-play');await page.waitForFunction(()=>VocabArena3D._t.map()==='forest');
  ok('switching maps preserves session earnings',earned>0&&await page.evaluate(n=>VocabArena3D._t.sessionCoins===n,earned));
  ok('switching maps preserves carried letters',await page.evaluate(s=>VocabArena3D._t.cargo.join('')===s,carried));ok('map switch creates only one renderer surface',await page.locator('#va-canvas').count()===1);
  await page.click('#va-map-change');await page.keyboard.press('Escape');const x=await page.evaluate(()=>VocabArena3D._t.player().pos.x);await page.keyboard.down('KeyD');await page.waitForTimeout(180);await page.keyboard.up('KeyD');ok('cancel map switch resumes gameplay',await page.evaluate(n=>VocabArena3D._t.player().pos.x>n+.1,x));await page.evaluate(()=>VocabArena3D.stop());
  await page.route('**/img/arena-maps/crystal.avif',r=>r.abort());await page.evaluate(async()=>{await ArenaMaps.prepare('crystal');state.arenaMap='crystal';VocabArena3D.start();});await page.waitForFunction(()=>VocabArena3D._t.ground()?.material.map.image?.complete);ok('AVIF failure uses WebP fallback',await page.evaluate(()=>VocabArena3D._t.ground().material.map.image.src.endsWith('crystal.webp')));await page.evaluate(()=>VocabArena3D.stop());
  ok('no runtime errors',errors.length===0);ok('scene remains within existing mesh/particle caps',Object.values(costs).every(v=>v.fx.meshes<=48&&v.fx.particles<=640));console.log(JSON.stringify({passed:checks.length,checks,costs,errors,out}));
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
