"use strict";
// Browser regression for readable labels on every admin Noir ranking/navigation surface.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const repo=path.resolve(process.env.VW_THEME_ROOT||'C:/Users/rober/english-pet-game');
const deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const {chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
const out=process.env.VW_THEME_OUT||path.join(require('os').tmpdir(),'vocab-home-dark-labels');fs.mkdirSync(out,{recursive:true});
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/home-v2.css"><link rel="stylesheet" href="/css/rankgraph.css"><link rel="stylesheet" href="/css/home-dark-surfaces.css"><style>html,body{margin:0;background:#101114;color:#f1f2f4;font-family:Arial,sans-serif}#vw-home-v2-root{padding:14px}.vw2-wallet{display:flex;gap:8px}.vw2-wallet-pill{width:210px;height:70px}.vw2-stat-copy{display:flex;align-items:center;justify-content:center;height:100%}.classic{display:flex;gap:8px;margin-top:12px}.rg-box{width:760px;height:250px;margin:12px}.rg-box>header{padding:10px}.rg-tabs{display:flex;gap:6px;padding:8px}.rg-tab{padding:8px}.rg-chart-head{padding:8px}.rg-box>footer{padding:8px}</style></head><body><main id="vw-home-v2-root"><section class="vw2-wallet"><button class="vw2-wallet-pill hud-link graph"><span class="vw2-stat-copy"><b>กราฟอันดับ</b></span></button><button class="vw2-wallet-pill hud-link rank-shortcut"><span class="vw2-stat-copy"><b>อันดับ</b></span></button></section><section class="classic"><button class="rank-graph-btn">กราฟอันดับ</button><button class="rail-btn" id="btn-rail-rank"><span class="rail-ico">🥇</span><span>อันดับ</span></button></section><section class="rg-box"><header><h2>กราฟอันดับผู้เล่น</h2><p>Top 30 ของแต่ละหมวด</p></header><div class="rg-tabs"><button class="rg-tab">เหรียญ</button><button class="rg-tab active">ชนะ</button></div><div class="rg-chart-head"><b>อันดับล่าสุด</b><span>คะแนนจากผู้เล่น</span></div><footer>เลื่อนเพื่อดูผู้เล่นทั้งหมด</footer></section></main></body></html>`;
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://local').pathname);if(pathname==='/__labels.html'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'}).end(html);return}const file=path.resolve(repo,'.'+pathname);if(!file.startsWith(repo+path.sep)){res.writeHead(403).end();return}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'content-type':path.extname(file)==='.css'?'text/css; charset=utf-8':'application/octet-stream','cache-control':'no-store'}).end(err?'missing':data)})});
const checks=[];function ok(name,value){assert.ok(value,name);checks.push(name);console.log('PASS '+name)}
function lum(c){const rgb=(c.match(/[\d.]+/g)||[]).slice(0,3).map(Number);if(rgb.length<3)return null;return rgb.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0)}
function contrast(a,b){return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)}
(async()=>{
  const css=fs.readFileSync(path.join(repo,'css/home-dark-surfaces.css'),'utf8'),index=fs.readFileSync(path.join(repo,'index_classic.html'),'utf8');
  ok('late dark label override exists',css.includes('Round 1527: readable labels'));
  ok('readable compact type override exists',css.includes('Round 1528: readable compact type'));
  ok('dark surface stylesheet remains after daily box CSS',index.indexOf('home-dark-surfaces')>index.indexOf('dailybox'));
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});
  try{const page=await browser.newPage({viewport:{width:812,height:375}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/__labels.html`,{waitUntil:'networkidle'});await page.evaluate(()=>document.documentElement.classList.add('theme-noir'));
    const result=await page.evaluate(()=>{const lum=c=>{const rgb=(c.match(/[\d.]+/g)||[]).slice(0,3).map(Number);if(rgb.length<3)return null;return rgb.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0)};const cr=(a,b)=>(Math.max(a,b)+.05)/(Math.min(a,b)+.05);const bgLum=el=>{for(let node=el;node;node=node.parentElement){const s=getComputedStyle(node),stops=[...s.backgroundImage.matchAll(/rgba?\(([^)]+)\)/g)].map(m=>lum('rgb('+m[1]+')')).filter(v=>v!==null);if(stops.length)return Math.max(...stops);const alpha=(s.backgroundColor.match(/rgba?\(([^)]+)\)/)||[])[1];if(alpha){const a=alpha.split(',').map(Number)[3];if(Number.isFinite(a)&&a>0)return lum(s.backgroundColor)}}return lum('rgb(16,17,20)')};const pairs=[...document.querySelectorAll('.vw2-wallet-pill b,.rank-graph-btn,.rail-btn,.rg-box h2,.rg-box header p,.rg-tab,.rg-chart-head b,.rg-chart-head span,.rg-box>footer')].map(el=>{const s=getComputedStyle(el),p=el.closest('.vw2-wallet-pill,.classic,.rg-box')||el.parentElement,b=bgLum(el);return {text:el.textContent.trim(),ratio:cr(lum(s.color),b),color:s.color,bg:b}});const active=document.querySelector('.rg-tab.active'),as=getComputedStyle(active);return {pairs,allReadable:pairs.every(x=>x.ratio>=4.5),noPurple:pairs.every(x=>!['rgb(59, 32, 93)','rgb(49, 32, 82)'].includes(x.color)),activeReadable:cr(lum(as.color),bgLum(active))>=4.5,noOverflow:document.documentElement.scrollWidth<=innerWidth+1&&document.documentElement.scrollHeight<=innerHeight+1,compactFloor:[...document.querySelectorAll('.vw2-wallet-pill b,.rank-graph-btn,.rail-btn,.rg-tab,.rg-chart-head b,.rg-box>footer')].every(el=>parseFloat(getComputedStyle(el).fontSize)>=11),scrollbarHidden:getComputedStyle(document.querySelector('.rg-box')).scrollbarWidth==='none'}});
ok('all sample labels meet AA contrast',result.allReadable);ok('legacy violet label colors are gone',result.noPurple);ok('selected ranking tab remains readable',result.activeReadable);ok('labels fit the 812x375 viewport',result.noOverflow);ok('compact labels keep an 11px readable floor',result.compactFloor);ok('dark dialog scrollbars stay visually hidden',result.scrollbarHidden);ok('no browser runtime errors',errors.length===0);const raw=await page.screenshot({animations:'disabled'});await sharp(raw).webp({quality:90,effort:6}).toFile(path.join(out,'admin-dark-labels-812x375.webp'));fs.writeFileSync(path.join(out,'dark-label-checks.json'),JSON.stringify({passed:checks.length,checks,result},null,2));console.log(JSON.stringify({passed:checks.length,out}))
  }finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
