'use strict';
const fs=require('fs');
const home=fs.readFileSync('js/home-v2.js','utf8');
const util=fs.readFileSync('js/util.js','utf8');
const lobby=fs.readFileSync('css/lobby.css','utf8');
const css=fs.readFileSync('css/home-v2.css','utf8');
const rules=fs.readFileSync('handoff/GAME_RULES.md','utf8');
const index=fs.readFileSync('index_classic.html','utf8');
const ok=(condition,message)=>{ if(!condition){ console.error('FAIL',message); process.exitCode=1; } else console.log('ok',message); };
const helpStart=util.indexOf('function openHelp()');
const helpEnd=util.indexOf('function openTeacherGuide()',helpStart);
const help=util.slice(helpStart,helpEnd);
ok(helpStart>=0 && helpEnd>helpStart,'openHelp guide exists');
ok(home.includes("toolButton('help','book','คู่มือการเล่น')"),'primary Lobby has a labelled guide button');
ok(index.includes('css/lobby.css?v=1486') && index.includes('css/home-v2.css?v=1486') && index.includes('js/util.js?v=1486') && index.includes('js/home-v2.js?v=1486'),'changed guide assets have a fresh production cache key');
ok(home.includes("if(name === 'help')") && home.includes("typeof openHelp === 'function'"),'Home V2 guide action calls the authoritative guide');
ok(util.includes('id="set-help">📖 คู่มือการเล่น'),'settings keeps a second guide entry');
ok(help.includes('ให้ “แตะ” ที่ตัวน้องบน Lobby ก่อน') && help.includes('จึงจะเปิดหน้า Profile หรือหน้ารายละเอียดของน้อง'),'pet-care page explains that tapping the pet opens its Profile/details');
ok(help.includes("tab:'ที่พัก'") && help.includes('ที่พักมี 3 แบบ'),'guide explains all three shelter choices');
ok(help.includes("tab:'ไม่ให้ป่วย'") && help.includes('ห้าสิ่งที่ต้องระวังทุกวัน'),'guide explains current illness prevention');
ok(help.includes("tab:'ตั้งค่า'") && help.includes('เสียงเอฟเฟกต์และเสียงอ่านคำ'),'guide explains current settings in human language');
ok(help.includes('เกมหลักทั้งหมดเข้าเล่นฟรี') && !help.includes('ตั๋วโลกผจญภัย'),'obsolete paid-ticket instruction is removed');
ok(help.includes('อาหารคนหรือของที่เป็นอันตรายถูกซ่อนและกดป้อนไม่ได้') && !help.includes('ซื้อเก็บได้ แต่ถ้าหยิบของโทษให้กิน'),'safe-food-only rule replaces the obsolete toxin instruction');
ok(help.includes('CURE_COST') && help.includes('HOMES') && help.includes('AC_PRICE'),'prices come from live game constants where available');
ok(rules.includes('หิวมื้อเย็นวันละครั้งเวลา 18:00') && rules.includes('ค่ารักษาป่วยทุกกรณี 100 (`CURE_COST`)'),'authoritative rules match the current meal and cure constants');
ok(help.includes('help-guide-prev') && help.includes('help-guide-next') && help.includes('data-help-page'),'guide is paginated instead of one oversized wall of text');
ok(lobby.includes('.help-guide-box.help-guide-box') && lobby.includes('position:fixed;inset:0') && lobby.includes('overflow:hidden'),'guide uses the full viewport without a dialog scrollbar');
ok(lobby.includes('grid-template-columns:repeat(2,minmax(0,1fr))') && css.includes('Six current tools'),'two-card page and six-tool layout contracts are present');
if(process.exitCode) process.exit(process.exitCode);
console.log('lobby guide 1489 checks passed');
