'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
let n=0; const assert=(ok,msg)=>{ if(!ok){ console.error('FAIL',msg); process.exitCode=1; } else n++; };

const code=read('js/wordskirmish.js');
const css=read('css/wordskirmish.css');
const html=read('index_classic.html');
const ui=read('js/ui.js');
const city=read('js/city3d.js');
const home=read('js/home-v2.js');
const main=read('js/main.js');
const auth=read('js/auth.js');
const build=read('tools/build_web.mjs');
const net=read('js/netroom.js');
const rules=read('handoff/RULES.md');
const lobby=read('css/lobby.css');

assert(html.includes('id="btn-rail-skirmish"')&&html.includes('ยิงรบคำ'),'classic rail button');
assert(/\bid="btn-rail-skirmish"[^>]*\bhidden\b/.test(html),'classic rail starts hidden');
assert(ui.includes('function refreshSkirmishLock')&&ui.includes('b.hidden=!ok'),'rail visibility follows admin login');
assert(city.includes("b.go==='skirmish'")&&city.includes('cityAdminAccess'),'3D city explains admin lock');
assert(home.includes("'skirmish'")&&/'skirmish'/.test((home.match(/const ADMIN_ONLY_WORLD_ACTIONS = new Set\(\[([\s\S]*?)\]\)/)||[])[1]||''),'Home V2 hides card from non-admins');
assert(!/<script[^>]+js\/wordskirmish\.js/.test(html)&&!html.includes('href="css/wordskirmish.css"'),'game JS/CSS are not in lobby HTML');
assert(ui.includes("loadScriptOnce('js/wordskirmish.js')")&&ui.includes("loadStylesheetOnce('skirmish-css','css/wordskirmish.css')"),'lazy load');
assert(ui.includes('async function openWordSkirmish')&&ui.includes('btn-rail-skirmish'),'lobby binder');
assert(main.includes("skirmish:'#btn-rail-skirmish'"),'city go routes to rail');
assert(city.includes("bld('skirmish'")&&city.includes('ยิงรบคำ'),'3D city booth');
assert(home.includes("['skirmish','gun','ยิงรบคำ','#btn-rail-skirmish']")&&home.includes("skirmish:'🔫'"),'Home V2 card');
assert(home.includes("skirmish:'#btn-rail-skirmish'"),'Home V2 delegates to classic rail');
assert(build.includes("'js/wordskirmish.js'")&&build.includes("'css/wordskirmish.css'"),'production copy list');
assert(auth.includes('refreshSkirmishLock'),'auth refreshes lock');
assert(lobby.includes('#btn-rail-skirmish[hidden]'),'lobby hides locked rail');
assert(net.includes("'skirmish'")&&net.includes("map === 'skirmish'")&&net.includes('isAdmin'),'NetRoom map + admin gate');
assert(rules.includes("$map === 'skirmish'"),'rules allowlist covers the new map');
assert(code.includes('soft-cuboid-chibi-3d')&&code.includes('CAM_DIST')&&code.includes('camera.lookAt(a.x, a.y, a.z)'),'third-person chase camera on the cute chibi model');
assert(code.includes('elbowR')&&code.includes('shoulderR')&&code.includes('armR.wrist.add(gun)'),'gun is parented to a wrist bone');
assert(code.includes('function poseChibi')&&code.includes('r.elbowR.rotation.set(1.22'),'aim pose bends the shooting elbow');
assert(code.includes("barrel.position.set(0,.04,.72)")&&code.includes("stock=box")&&code.includes('-Z = พานท้าย'),'barrel faces +Z (forward), stock faces -Z (back)');
assert(code.includes("m.userData.hit='head'")||code.includes("stampHit(neck,'head')"),'head meshes stay tagged for headshots');
assert(code.includes('camera.updateMatrixWorld()'),'aim ray uses a fresh camera matrix');
assert(code.includes('BODY_DMG')&&code.includes("kind==='H'")&&code.includes('ตายทันที'),'headshot vs body damage');
assert(code.includes('LETTER_REWARD=1000')&&code.includes('tryDeposit')&&code.includes('tryPickup'),'Frontline-style letters');
assert(code.includes("map:'skirmish'")&&code.includes('roomMax:8'),'online rooms');
assert(css.includes('#skm-game')&&css.includes('max-height:430px'),'landscape HUD');
assert(css.includes('.skm-zone')&&code.includes('e.clientX < W*0.5'),'left half walks, right half looks');
assert(code.includes("data-hold=\"drop\"")&&code.includes('HOLD_MS=420')&&code.includes("p.act==='fire'"),'long-press repositions FIRE/DROP');
assert(code.includes('ฐานตามนิ้ว')||code.includes('placeCtl(hud.joy'),'walk base follows the thumb');
assert(code.includes('userData.safe')&&code.includes('ตัวอักษรในบ้านปลอดภัย'),'banked letters stay safe');

const vm=require('vm');
const sandbox={window:{},document:{readyState:'complete',createElement:()=>({style:{},appendChild(){},addEventListener(){}}),body:{appendChild(){}},addEventListener(){}},console,THREE:null};
sandbox.window=sandbox;
vm.createContext(sandbox);
vm.runInContext(code, sandbox);
const T=sandbox.window.WordSkirmish._t;
assert(T.adminAllowed()===false,'closed to non-admin by default');
assert(T.LETTER_REWARD===1000 && T.BODY_DMG===35 && T.MAX_HP===100,'economy/combat constants');
assert(T.COOLDOWN===310,'same airgun cadence as Shoot Word');
assert(T.HOMES.length===4,'four private homes');
const packed=T.packHp();
assert(packed.length<=28 && T.parseHp(packed).hp===100,'hp payload fits NetRoom');
T.setCarried('C'); T.setPlayer({x:T.HOMES[0].x,z:T.HOMES[0].z,seat:0,alive:true,hp:100});
assert(T.tryDeposit()==='C','bank at own home');
assert(T.hasWord('CAT','CAT')===true&&T.hasWord('CT','CAT')===false,'complete detection');
T.setPlayer({x:0,z:0,alive:true,hp:100,seat:0});
T.collideMove(999,999);
assert(Math.abs(T.player.x)<T.ARENA&&Math.abs(T.player.z)<T.ARENA,'arena walls hold the player in');
T.setPlayer({x:T.HOMES[1].x,z:T.HOMES[1].z+6,seat:0});
T.collideMove(T.HOMES[1].x,T.HOMES[1].z);
assert(T.homeBlocked(T.HOMES[1].x,T.HOMES[1].z)===true&&!T.homeBlocked(0,0),'house walls are solid, arena centre is open');
assert(Math.abs(T.player.z-T.HOMES[1].z)>=T.HOUSE_HALF,'walking into a house is stopped at the wall');
T.setPlayer({x:T.HOMES[0].x,z:T.HOMES[0].z+3.2,seat:0});
assert(Math.hypot(T.player.x-T.HOMES[0].x,T.player.z-T.HOMES[0].z)<T.HOME_R,'spawn point can still bank letters from outside the wall');
T.setPlayer({hp:100,alive:true});
T.applyDamage('body');
assert(T.player.hp===T.MAX_HP-T.BODY_DMG,'body shot reduces hp');
T.setPlayer({hp:100,alive:true}); T.applyDamage('head');
assert(T.player.alive===false && T.player.hp===0,'headshot is instant');
T.setPlayer({x:0,z:0,alive:true,hp:100,seat:0});
T.placeLetter('B',0,0); T.setCarried('');
assert(T.tryPickup()==='B','pickup nearby letter');
T.setStored('CA'); T.setCarried('X'); T.setPlayer({x:5,z:5,alive:true,hp:100,seat:0});
T.applyDamage('head');
assert(T.stored==='CA'&&T.player.alive===false,'banked house letters survive a knockout');
assert(T.carried==='','the letter in hand is the one that drops');
T.placeLetter('Q',0,0); T.letters.find(L=>L.letter==='Q').safe=true; T.setCarried(''); T.setPlayer({x:0,z:0,alive:true,hp:100});
assert(T.tryPickup()==='','a letter already in a house cannot be stolen');
/* จุดเกิดหันออกกลางสนาม และจุดเล็งขึ้นลงตามการลากนิ้ว */
T.setPlayer({seat:0}); T.resetRun();
const fwdX=-Math.sin(T.player.yaw), fwdZ=-Math.cos(T.player.yaw);
assert(fwdX>0.5&&fwdZ>0.5,'spawn faces the arena, not the house wall');
assert(Math.hypot(T.player.x-T.HOMES[0].x,T.player.z-T.HOMES[0].z)<T.HOME_R,'spawn stays inside its banking radius');
const low=T.setLook(0,0.5)&&T.aimPoint().y, high=T.setLook(0,0.1)&&T.aimPoint().y;
assert(high>low,'lower lookPitch aims higher');
T.setLook(0,0.28);
const mid=T.aimPoint().y;
T.applyLook(0,20);
assert(T.aimPoint().y<mid,'drag down looks down (FPS, not flight stick)');
T.setLook(0,0.28);
T.applyLook(0,-20);
assert(T.aimPoint().y>mid,'drag up looks up');
console.log('wordskirmish ok',n);
