'use strict';
// Real Three.js geometry + browser inputs. No login, Firebase or persistent player data.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const repo=path.resolve(process.env.SKM_ROOT||path.join(__dirname,'..'));
const deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const {chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp'));
const out=process.env.SKM_OUT||path.join(require('os').tmpdir(),'wordskirmish-poses');fs.mkdirSync(out,{recursive:true});
const fixture='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/wordskirmish.css"><style>body{margin:0}</style><body><script>window.state={sound:false,coins:100,profileName:"Preview"};window.isAdmin=()=>true;window.vocabForStudent=()=>[["cat","แมว"]];window.addCoins=()=>{};window.saveState=()=>{};window.Music={suspendBg(){},resumeBg(){}};</script><script src="/js/vendor/three.min.js"></script><script src="/js/wordskirmish.js"></script><script>WordSkirmish.open()</script>';
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local');if(url.pathname==='/favicon.ico'){res.writeHead(204).end();return;}if(url.pathname==='/preview'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'}).end(fixture);return;}const file=path.resolve(repo,'.'+url.pathname);if(!file.startsWith(repo+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'content-type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream','cache-control':'no-store'});res.end(e?'missing':b)});});
const checks=[];function ok(name,value){assert.ok(value,name);checks.push(name);console.log('PASS '+name)}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage({viewport:{width:1367,height:617}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});page.on('console',m=>{if(m.type()==='error')console.error(m.text())});await page.goto(`http://127.0.0.1:${server.address().port}/preview`);await page.waitForFunction(()=>window.WordSkirmish?._t.playerMesh);
await page.locator('#skm-intro button').click();await page.evaluate(()=>WordSkirmish._t.setRunning(false));await page.waitForTimeout(60);
const geometry=await page.evaluate(()=>{const T=WordSkirmish._t,v=new THREE.Vector3(),box=new THREE.Box3(),mesh=T.makeChibi({},true),r=mesh.userData.rig;const failures=[],heights={};let cases=0,maxFloor=-Infinity,minFloor=Infinity,maxYawError=0,maxAimError=0;const wp=o=>o.getWorldPosition(new THREE.Vector3());
for(const pose of ['stand','crouch','kneel','prone'])for(let heading=0;heading<8;heading++)for(const dodge of [-1,0,1])for(const bob of [0,Math.PI/2,Math.PI,Math.PI*1.5]){
mesh.position.set(0,0,0);mesh.rotation.set(0,heading*Math.PI/4,0);T.poseChibi(mesh,{pose,dodge,bob,moving:bob!==0,alive:true});mesh.updateMatrixWorld(true);box.setFromObject(mesh);minFloor=Math.min(minFloor,box.min.y);maxFloor=Math.max(maxFloor,box.min.y);if(box.min.y<0||box.min.y>.04)failures.push({pose,heading,dodge,bob,floor:box.min.y});
const aim=r.gun.getWorldDirection(v),fwd=new THREE.Vector3(-Math.sin(mesh.rotation.y),0,-Math.cos(mesh.rotation.y));maxAimError=Math.max(maxAimError,Math.abs(aim.y-.04/Math.hypot(5,.04)),1-aim.dot(fwd));
if(dodge===0&&bob===0){if(!heading)heights[pose]=box.max.y;else maxYawError=Math.max(maxYawError,Math.abs(heights[pose]-box.max.y));if(pose==='crouch'&&!heading){const hip=wp(r.hipL),knee=wp(r.kneeL),ankle=wp(r.ankleL);if(!(knee.z<hip.z-.2&&ankle.z>knee.z+.1&&ankle.y<knee.y))failures.push({knees:'wrong direction'});}}
if(pose==='prone'&&Math.abs(r.body.rotation.x+Math.PI/2)>.001)failures.push({prone:'torso not horizontal'});
if(pose!=='prone'&&dodge){const head=wp(r.neck),side=new THREE.Vector3(Math.cos(mesh.rotation.y),0,-Math.sin(mesh.rotation.y));if(head.dot(side)*dodge<=.1)failures.push({pose,heading,dodge,lean:'wrong side'});}
cases++;
}
const start=performance.now();for(let i=0;i<1000;i++)T.poseChibi(mesh,{pose:'crouch',moving:true,bob:i*.1,alive:true});const msPerPose=(performance.now()-start)/1000;
return {cases,failures:failures.slice(0,8),heights,minFloor,maxFloor,maxYawError,maxAimError,msPerPose};});
console.log(JSON.stringify(geometry));ok('384 actual rig poses stay above and in contact with the ground',!geometry.failures.length);ok('crouch lowers head and prone lowers it further',geometry.heights.crouch<geometry.heights.stand-.2&&geometry.heights.prone<geometry.heights.crouch-.4);ok('postures retain height at all eight headings',geometry.maxYawError<.001);ok('barrel stays forward and level in every posture',geometry.maxAimError<.001);
const movement=await page.evaluate(()=>{const T=WordSkirmish._t,results=[];for(const pose of ['stand','crouch','prone'])for(let heading=0;heading<8;heading++)for(const dir of [-1,1]){T.resetRun();T.setStance(pose);T.setPlayer({x:0,z:0,alive:true,yaw:heading*Math.PI/4});T.setLook(heading*Math.PI/4,.28);T.setAutoRun(false);T.clearInput();T.setRunning(true);T.startDodge(dir);const repeat=T.startDodge(-dir);for(let i=0;i<32;i++)T.step(.48/32);results.push({pose,heading,dir,repeat,x:T.player.x,z:T.player.z,yaw:T.player.yaw,left:T.dodgeT,stance:T.stance,lean:T.playerMesh.userData.rig.upper.rotation.z});T.setRunning(false);}return results;});
ok('dodge sidesteps exactly two units without turning away or changing stance',movement.every(r=>Math.abs(r.x-Math.cos(r.heading*Math.PI/4)*2*r.dir)<.001&&Math.abs(r.z+Math.sin(r.heading*Math.PI/4)*2*r.dir)<.001&&r.yaw===r.heading*Math.PI/4&&r.stance===r.pose));ok('dodge cannot restart mid-action and returns upright',movement.every(r=>r.repeat===0&&r.left===0&&r.lean===0));
const peer=await page.evaluate(()=>{const T=WordSkirmish._t;T.resetRun();T.setPlayer({x:0,z:0});T.setLook(1.1,.28);T.setStance('prone');T.setRunning(true);T.startDodge(-1);T.step(.24);const av=T.packAv(),local=T.playerMesh;T.setRoom({peers:{preview:{av,hp:T.packHp(),x:T.player.x,z:T.player.z,yaw:T.player.yaw}}});T.syncPeers();T.scene.updateMatrixWorld(true);const remote=T.peersVis.preview.mesh;const delta=Math.abs(local.userData.rig.neck.getWorldPosition(new THREE.Vector3()).y-remote.userData.rig.neck.getWorldPosition(new THREE.Vector3()).y);const result={av,delta,phase:T.parseAv(av).dodge,body:remote.userData.rig.body.rotation.x,lean:remote.userData.rig.upper.position.x};T.setRoom({peers:{}});T.syncPeers();T.setRoom(null);T.setRunning(false);return result;});ok('remote avatar reproduces prone and dodge phase from existing payload',peer.delta<.001&&peer.phase===-1&&Math.abs(peer.body+Math.PI/2)<.001&&peer.lean<0);
// Real controls, held keys, pointer cancellation, and movable-button compatibility.
await page.evaluate(()=>{const T=WordSkirmish._t;T.resetRun();T.setRunning(true)});
await page.keyboard.down('c');await page.keyboard.down('c');ok('holding C does not toggle repeatedly',await page.evaluate(()=>WordSkirmish._t.stance==='crouch'));await page.keyboard.up('c');await page.keyboard.press('z');ok('Z replaces crouch with prone',await page.evaluate(()=>WordSkirmish._t.stance==='prone'));await page.keyboard.press('z');ok('Z again stands up',await page.evaluate(()=>WordSkirmish._t.stance==='stand'));
await page.locator('#skm-crouch').click();ok('crouch button updates pressed state',await page.locator('#skm-crouch').getAttribute('aria-pressed')==='true');await page.locator('#skm-prone').click();ok('prone button clears crouch selection',await page.locator('#skm-prone').getAttribute('aria-pressed')==='true'&&await page.locator('#skm-crouch').getAttribute('aria-pressed')==='false');
const pos=await page.locator('#skm-prone').boundingBox();await page.mouse.move(pos.x+pos.width/2,pos.y+pos.height/2);await page.mouse.down();await page.waitForTimeout(470);await page.mouse.up();ok('a long stationary press still toggles the stance once',await page.evaluate(()=>WordSkirmish._t.stance==='stand'));
await page.locator('#skm-crouch').dispatchEvent('pointerdown',{pointerId:123,clientX:250,clientY:200,bubbles:true});await page.locator('#skm-crouch').dispatchEvent('pointercancel',{pointerId:123,bubbles:true});ok('cancelled touch does not activate a stance',await page.evaluate(()=>WordSkirmish._t.stance==='stand'));
const old=await page.locator('#skm-crouch').boundingBox();await page.mouse.move(old.x+old.width/2,old.y+old.height/2);await page.mouse.down();await page.waitForTimeout(470);await page.mouse.move(old.x+old.width/2+15,old.y+old.height/2+35);await page.mouse.up();const moved=await page.locator('#skm-crouch').boundingBox();ok('long press and drag repositions without activating',Math.abs(moved.y-old.y-35)<2&&await page.evaluate(()=>WordSkirmish._t.stance==='stand'));
await page.keyboard.down('w');await page.evaluate(()=>{window.dispatchEvent(new Event('blur'));WordSkirmish._t.setAutoRun(false);WordSkirmish._t.setPlayer({x:0,z:0});WordSkirmish._t.step(.1)});ok('focus loss releases movement',await page.evaluate(()=>WordSkirmish._t.player.x===0&&WordSkirmish._t.player.z===0));await page.keyboard.up('w');
await page.locator('#skm-dodge').click();ok('dodge button starts an action and shows pressed state',await page.evaluate(()=>WordSkirmish._t.dodgeT>0)&&await page.locator('#skm-dodge').getAttribute('aria-pressed')==='true');await page.evaluate(()=>WordSkirmish._t.step(.48));ok('dodge button clears when action finishes',await page.locator('#skm-dodge').getAttribute('aria-pressed')==='false');
await page.keyboard.down('a');await page.locator('#skm-dodge').click();ok('dodge immediately uses the held left direction',await page.evaluate(()=>WordSkirmish._t.parseAv(WordSkirmish._t.packAv()).dodge<=0&&WordSkirmish._t.packAv().includes('L')));await page.keyboard.up('a');await page.evaluate(()=>WordSkirmish._t.step(.48));
// Geometry-based hitboxes: a shot at standing head height must pass over a prone avatar.
const hit=await page.evaluate(()=>{const T=WordSkirmish._t,m=T.makeChibi({},false);m.rotation.y=0;T.poseChibi(m,{pose:'stand',alive:true});m.updateMatrixWorld(true);const ray=new THREE.Raycaster(new THREE.Vector3(0,1.7,-5),new THREE.Vector3(0,0,1));const standing=ray.intersectObject(m,true).some(h=>h.object.userData.hit==='head');T.poseChibi(m,{pose:'prone',alive:true});m.updateMatrixWorld(true);return {standing,prone:ray.intersectObject(m,true).length};});ok('actual prone hitbox ducks a shot at standing head height',hit.standing&&hit.prone===0);
const frames=[];for(const size of [{width:1367,height:617},{width:812,height:375}]){await page.setViewportSize(size);await page.evaluate(()=>{const T=WordSkirmish._t;T.resetRun();T.setPlayer({x:0,z:0});T.setLook(0,.28);T.setRunning(true)});await page.waitForTimeout(70);const bounds=await page.locator('#skm-game').evaluate(root=>[...root.querySelectorAll('.skm-float,.skm-joy,.skm-exit')].map(el=>{const r=el.getBoundingClientRect();return {id:el.id,x:r.x,y:r.y,right:r.right,bottom:r.bottom}}));ok(`controls stay in ${size.width}x${size.height}`,bounds.every(b=>b.x>=0&&b.y>=0&&b.right<=size.width+.1&&b.bottom<=size.height+.1));for(const pose of ['stand','crouch','prone']){await page.evaluate(p=>{const T=WordSkirmish._t;T.setStance(p);T.step(0);T.renderer.render(T.scene,T.camera)},pose);await page.waitForTimeout(70);const file=`${size.width}-${pose}.webp`;await sharp(await page.screenshot()).webp({quality:92}).toFile(path.join(out,file));frames.push(file);}}
ok('no browser errors',errors.length===0);await page.evaluate(()=>{WordSkirmish.close();localStorage.clear()});fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,geometry,movement,peer,frames,errors},null,2));console.log(`wordskirmish browser ok ${checks.length}; outputs ${out}`);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
