"use strict";
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.join(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const code=read('js/wordship.js');
const shoot=read('js/shootword.js');
const html=read('index_classic.html');
const ui=read('js/ui.js');
const city=read('js/city3d.js');
const main=read('js/main.js');
const home=read('js/home-v2.js');
const css=read('css/wordship.css');
const build=read('tools/build_web.mjs');
const stateCode=read('js/state.js');

assert(html.includes('id="btn-rail-wordship"')&&html.includes('กองเรือคำศัพท์'),'classic rail button');
assert(html.includes('id="btn-rail-wordship"')&&/\bid="btn-rail-wordship"[^>]*\bhidden\b/.test(html),'classic rail starts hidden so public first paint cannot open it');
assert(ui.includes('function wordShipAdminAllowed')&&ui.includes('WORDSHIP_LOCK_MSG')&&ui.includes('if(!wordShipAdminAllowed())'),'lobby refuses to download or open the game for non-admins');
assert(ui.includes('function refreshWordShipLock')&&ui.includes('b.hidden=!ok'),'rail visibility follows admin login');
assert(city.includes("b.go==='wordship'")&&city.includes('cityAdminAccess')&&city.includes('เปิดให้แอดมินเท่านั้น'),'3D city harbor explains the admin lock instead of travelling');
assert(home.includes("'wordship'")&&home.includes("ADMIN_ONLY_WORLD_ACTIONS")&&/'wordship'/.test((home.match(/const ADMIN_ONLY_WORLD_ACTIONS = new Set\(\[([\s\S]*?)\]\)/)||[])[1]||''),'Home V2 hides the card from non-admins');
assert(code.includes('function adminAllowed')&&code.includes("isAdmin()===true"),'game open itself re-checks admin');
assert(!/<script[^>]+js\/wordship\.js/.test(html)&&!html.includes('href="css/wordship.css"'),'game JS/CSS are not in the lobby HTML download');
assert(ui.includes("loadScriptOnce('js/wordship.js')")&&ui.includes("loadStylesheetOnce('wordship-css','css/wordship.css')"),'first click lazy-loads the module');
assert(ui.includes('async function openWordShip')&&ui.includes('btn-rail-wordship'),'lobby binder lives in ui.js');
assert(main.includes("wordship:'#btn-rail-wordship'"),'city go=wordship routes to the rail button');
assert(city.includes("bld('wordship'")&&city.includes('กองเรือคำศัพท์'),'3D city harbor');
assert(!city.includes('CapsuleGeometry'),'city marker uses existing cylinder helper');
assert(home.includes("['wordship','ship','กองเรือคำศัพท์','#btn-rail-wordship']")&&home.includes("wordship:'⚓'"),'Home V2 card');
assert(home.includes('wordship:\'#btn-rail-wordship\''),'Home V2 click delegates to classic rail');
assert(stateCode.includes('wshScore:0')&&stateCode.includes('wshWords:0')&&stateCode.includes('wshIntro:0'),'save fields');
assert(build.includes("'js/wordship.js'")&&build.includes("'css/wordship.css'"),'production copy list');
assert(!code.includes('http')&&!code.includes('.webp')&&!code.includes('.png')&&!code.includes('.avif'),'no extra image or vocab network calls');
assert(code.includes("fire-a6fea31058694941.mp3")&&code.includes('playFireClip')&&code.includes("fetch(path)"),'FIRE reuses the Arena fire-ring clip and cache');
assert(code.includes("typeof vocabForStudent==='function'")&&code.includes('MINLEN=3, MAXLEN=8'),'Frontline-length words from the same in-memory vocab');
assert(shoot.includes('const MINLEN=3, MAXLEN=10'),'ShootWord still owns the source length rule');
assert(css.includes('@media(max-height:430px)')&&css.includes('#wsh-game')&&!css.includes('overflow:auto'),'short landscape HUD without inner scrollbars');
assert(code.includes('SEA_COLOR=0x003464')&&code.includes('color:SEA_COLOR')&&css.includes('#003464'),'the sea matches the supplied deep-ocean photo');
assert(code.includes('CARD_SHADOW=0x284664')&&code.includes("rgba(40,70,100,.18)"),'letter-card ovals keep the original shadow ink');
assert(!code.includes('0x2f92c9')&&!code.includes('0x6a93a3'),'older sea tints are gone');

const awarded={n:0};
const sandbox={
  console, performance:{now:()=>0}, Math, setTimeout:fn=>0, clearTimeout(){},
  requestAnimationFrame:()=>1, cancelAnimationFrame(){},
  window:{AudioContext:null, webkitAudioContext:null, addEventListener(){}, devicePixelRatio:1},
  document:{readyState:'complete', addEventListener(){}, getElementById(){return null;}, createElement(){return {style:{},classList:{add(){},remove(){}},appendChild(){},addEventListener(){},querySelector(){return null},setAttribute(){}};}, body:{appendChild(){}}},
  state:{student:{grade:'ป.1'}, sound:false, wshScore:0, wshWords:0, wshIntro:0},
  vocabForStudent:()=>[['cat','แมว'],['dog','สุนัข'],['bird','นก'],['apple','แอปเปิล'],['to','ถึง'],['extraordinarily','ยาวเกิน'],['book','หนังสือ']],
  addCoins(n){awarded.n+=n;}, saveState(){}, Music:{suspendBg(){}, resumeBg(){}}, toast(){}
};
sandbox.window=sandbox; sandbox.document.body=sandbox.document.body;
vm.createContext(sandbox); vm.runInContext(code, sandbox);
const T=sandbox.WordShip._t;
assert(T.adminAllowed()===false,'missing admin identity cannot open the fleet');
sandbox.isAdmin=()=>true;
assert(T.adminAllowed()===true,'admin identity can open the fleet');

function shootPool(src){
  const seen=new Set(), out=[];
  src.forEach(pair=>{
    const w=String(pair[0]||'').toUpperCase().replace(/[^A-Z]/g,'');
    if(w.length>=3 && w.length<=8 && !seen.has(w)) out.push(w);
  });
  return out.sort();
}
assert.strictEqual(JSON.stringify(T.pool().map(x=>x.w).sort()), JSON.stringify(shootPool(sandbox.vocabForStudent())), 'Word Fleet pool matches Frontline 3–8 filtering of vocabForStudent');
assert(!T.pool().some(x=>x.w==='TO'||x.w==='EXTRAORDINARILY'), 'too-short and too-long words stay out');
assert(T.pool().some(x=>x.w==='CAT'&&x.th==='แมว'), 'Thai meaning rides along from vocabForStudent');

assert(ui.includes("loadScriptOnce('js/vendor/three.min.js')"),'THREE loads before the fleet module');
assert(code.includes('softBox')&&code.includes('PerspectiveCamera'),'Kart-style cuboid ships in a 3D scene');
assert(code.includes('makeGunHouse')&&code.includes('TURRET_FWD'),'ships are toy battleships with main batteries');
assert(code.includes('elevPivot')&&code.includes('-bl*.5'),'barrels pitch around the turret center, not mid-tube');
assert(code.includes('TorusGeometry')&&code.includes('hinge:'),'small hinge rings sit at the turret barrel roots');
assert(code.includes('-7.05')&&code.includes('.22,.26,.48'),'the bow tapers to a pointed stem');
assert(code.includes('sizeAttenuation')&&code.includes('fitWordLabel'),'word plate stays camera-facing and distance-readable');

T.setViewport(812,375); T.resetRun();
assert.strictEqual(T.MAX_FLEET,1,'only one enemy ship is allowed');
assert.strictEqual(T.fleet.filter(s=>s.alive).length,1, 'exactly one live ship');
assert.strictEqual(T.fleet[0].target, false, 'enemy hulls are not the vocab target');
const lim=T.waterLimits();
assert.strictEqual(T.fleet[0].y,0, 'spawn sits on the water plane');
assert(T.fleet[0].z>=lim.farZ && T.fleet[0].z<=lim.nearZ, 'spawn stays between near and far water');
const far=T.spawnWave(T.pickCourse('nearFar',1));
assert.strictEqual(far.mode,'nearFar','near-to-far course is available');
assert(far.vx>0 && far.vz<0,'left-to-right near-to-far moves right and away');
assert.strictEqual(Math.hypot(far.vx,far.vz).toFixed(3), T.shipSpeed().toFixed(3), 'course speed is constant');
const h=T.headingVec(far.yaw);
assert((far.vx*h.x+far.vz*h.z)>0,'bot sails bow-first from stern toward bow');
assert.strictEqual(far.gear,1,'bots do not reverse');
const bow=T.bowOf(far), stern=T.sternOf(far);
assert(Math.hypot(bow.x-far.x,bow.z-far.z)>Math.hypot(stern.x-far.x,stern.z-far.z)-1e-9,'bow sits ahead of midships');
assert(T.apparentHull(far.startZ)>T.apparentHull(far.endZ), 'perspective makes a far hull look smaller');
far.z=far.endZ; T.applyShipScale(far);
assert.strictEqual(far.scale,1,'3D hull keeps world size; the camera does the shrinking');
assert.strictEqual(far.w,far.baseW,'hull width is not faked with a 2D depth scale');
const nearLab=T.labelWorldScale(16), farLab=T.labelWorldScale(48);
assert(farLab.w>nearLab.w, 'word plate grows in world units so it stays readable when far');
const left=T.spawnWave(T.pickCourse('flat',-1));
assert(left.vx<0 && Math.abs(left.vz)<1e-9,'right-to-left flat course keeps a constant depth');
T.step(.05);
assert.strictEqual(T.fleet[0].y,0, 'after moving, the ship is still on the water');
assert.strictEqual(Math.hypot(T.fleet[0].vx,T.fleet[0].vz).toFixed(3), T.shipSpeed().toFixed(3), 'speed does not change while sailing');

assert.strictEqual(T.pointerHalf(10,{left:0,width:100}),'cam','left half orbits the camera');
assert.strictEqual(T.pointerHalf(80,{left:0,width:100}),'gun','right half traverses the turret');
assert.strictEqual(T.setAuto(1),1,'AUTO FORWARD latches like Frontline');
assert.strictEqual(T.setAuto(1),0,'pressing the same AUTO button again releases it');
assert.strictEqual(T.setScope(true),true,'SCOPE zooms toward the target ship');
assert.strictEqual(T.setScope(false),false,'SCOPE can be turned off');

T.resetRun(); T.setRunning(true); T.setPaused(false);
const z0=T.player.z;
T.setHoldDrive(-1); T.step(.2);
assert(T.player.z>z0,'player reverse moves stern-ward');
T.setHoldDrive(1); T.step(.2);
assert(T.player.z<z0+1,'player forward sails bow-first');
T.setHoldDrive(0);
assert.strictEqual(T.NO_GAME_OVER,true,'the fleet never game-overs');
const hearts0=T.hearts;
for(let i=0;i<8;i++) T.hurt('wave');
assert.strictEqual(T.hearts,hearts0,'misses do not drain lives into a game over');
T.setScope(true);
const gun0=T.player.turretRel;
T.applyAimSwipe(40,0,true);
const fine=Math.abs(T.player.turretRel-gun0);
assert(Math.abs(fine-40*T.TURRET_SWIPE_FINE)<1e-9,'scope swipe matches the fine barrel rate');
assert(fine<40*T.TURRET_SWIPE,'scope traverse is finer than unscope gun swipe');
T.setScope(false);
T.resetRun();
const el0=T.player.elev;
T.applyAimSwipe(0,-30,false);
assert(T.player.elev>el0,'right-half swipe up raises the barrels');
T.applyAimSwipe(0,80,false);
assert(T.player.elev<el0,'right-half swipe down depresses the barrels');
assert(T.player.elev>=T.ELEV_MIN&&T.player.elev<=T.ELEV_MAX,'barrel pitch stays in range');
assert(T.ELEV_MIN>=0,'barrels cannot depress below the horizon into the deck');
T.applyAimSwipe(0,9999,false);
assert.strictEqual(T.player.elev, T.ELEV_MIN, 'swipe-down stops at the deck-safe pitch');
assert(T.barrelDir(0,0,T.ELEV_MIN).y>=0,'max depression still aims at or above the water, not into the deck');
const hi=T.barrelDir(0,0,T.ELEV_MAX), lo=T.barrelDir(0,0,T.ELEV_MIN);
assert(hi.y>lo.y,'higher elevation aims the shells upward');
T.setScope(false);
const px=T.player.x, pz=T.player.z, yaw0=T.player.yaw;
T.setHoldDrive(0); T.setHoldTurn(1); T.step(.25);
assert.strictEqual(T.player.x.toFixed(5), px.toFixed(5), 'turning does not sideslip off the keel');
assert.strictEqual(T.player.z.toFixed(5), pz.toFixed(5), 'turning pivots on the bow-stern axis');
assert(T.player.yaw>yaw0,'left/right yaws around midships');
T.setHoldTurn(0); T.setHoldDrive(1); T.step(.05);
const hh=T.headingVec(T.player.yaw);
assert(Math.abs(T.player.vx*hh.z-T.player.vz*hh.x)<1e-6,'drive velocity stays on the keel');
T.player.yaw=0; T.setHoldTurn(0); T.setHoldDrive(1); T.setSpeedLevel(2); T.step(.08);
assert(Math.abs(T.player.vx)<1e-6,'bow-forward never slides to port or starboard');
T.setHoldDrive(0);
const cam0=T.player.camYaw;
T.setHoldDrive(0); T.setHoldTurn(-1); T.step(.2);
assert.strictEqual(T.player.camYaw, cam0, 'LEFT/RIGHT yaw the hull, not the camera');
T.setHoldTurn(0);
const look=T.cameraLookTarget();
assert.strictEqual(look.x, T.player.x, 'camera is anchored to the player hull, not screen center');
assert.strictEqual(look.z, T.player.z, 'camera look target stays on the player ship');
T.setHoldDrive(1); T.step(.2);
assert.strictEqual(T.cameraLookTarget().z, T.player.z, 'camera pivot follows the moving player ship');
T.setHoldDrive(0);

const coins0=awarded.n;
T.resetRun();
assert.strictEqual(T.LETTER_REWARD,1000,'word pay matches Frontline');
assert.strictEqual(T.STORY_H*3>9,true,'home mesa is about three storeys tall');
assert(code.includes('function makeMesaHome')&&code.includes('function makeSpireIsland'),'two extra tall islands have different silhouettes');
assert(T.HOME.z<18&&T.HOME.x<0,'home island sits ahead-left of the spawn so the starting camera can see it');
assert(T.SPIRE.x>0&&T.SPIRE.z<T.HOME.z,'the spire island stays a different landmark on the starboard bow');
T.setStored(''); T.setCarried('');
const miss=T.word.w[0];
T.placeLetter(miss, T.player.x+30, T.player.z-8);
const nav=T.neededLetterHints({x:T.player.x,z:T.player.z});
assert(nav.some(h=>h.letter===miss),'edge arrows point at the nearest missing letter card');
T.setCarried(miss);
assert.strictEqual(T.neededLetterHints().length,0,'letter arrows hide while a card is carried');
T.setCarried('');
const edge=T.placeHint(-80,200,800,400);
assert(edge.visible&&edge.x>=50&&edge.x<=54,'hints sit on the HUD-safe frame like Frontline');
assert(css.includes('#wsh-arrows')&&css.includes('.wsh-nav'),'arrow overlay is styled without extra images');
assert(css.includes('.wsh-nav[hidden]'),'stale home arrows actually hide instead of stacking');
assert((code.match(/letter:'บ้าน'/g)||[]).length===1,'only one home arrow is ever queued');
const need=T.word.w[0];
T.placeLetter(need, T.player.x, T.player.z);
assert.strictEqual(T.tryPickup(), need, 'sailing onto a card picks up one letter');
assert.strictEqual(T.carried, need, 'only one letter is carried');
assert.strictEqual(T.tryPickup(), '', 'a second card cannot be carried');
T.player.x=T.HOME.x; T.player.z=T.HOME.z;
assert.strictEqual(T.tryDeposit(), need, 'the letter is banked at the player home');
assert.strictEqual(T.carried, '', 'hands are empty after the vault deposit');
assert.strictEqual(T.dropCarried(), '', 'DROP does nothing with empty hands');
T.placeLetter(need, T.player.x, T.player.z);
assert.strictEqual(T.tryPickup(), need, 'a wrong or extra letter can be picked again');
assert.strictEqual(T.dropCarried(), need, 'DROP puts the carried letter back on the water');
assert.strictEqual(T.carried, '', 'hands are empty after DROP');
const dumped=T.letters.find(L=>L.letter===need);
assert(dumped&&Math.hypot(dumped.x-T.player.x, dumped.z-T.player.z)<22,'dropped card lands near the hull');
assert(T.PICKUP_R>=6&&T.CARD_W>=5&&T.CARD_H>=6,'letter cards are large world sprites');
assert.strictEqual(T.CARD_FADE,.20,'occluding letters fade to 20 percent');
T.player.x=0; T.player.z=0;
const camStub={position:{x:0,y:6,z:20}};
const meshStub={position:{y:2.15},scale:{x:T.CARD_W}};
assert(T.letterOccludesShip({x:0,z:8,mesh:meshStub}, camStub),'a card on the camera-ship line occludes the hull');
assert(!T.letterOccludesShip({x:40,z:8,mesh:meshStub}, camStub),'a side card does not fade');
assert(!T.letterOccludesShip({x:0,z:28,mesh:meshStub}, camStub),'a card behind the camera does not fade');
assert(code.includes('function makeLetterCard')&&code.includes('id="wsh-drop"'),'cute letter cards and a DROP button');
assert(css.includes('#wsh-drop'),'DROP is styled in the attack column');
assert(T.stored.includes(need), 'banked letters stay in the private home');
T.setStored(T.word.w);
const beforeDone=T.wordsDone;
assert.strictEqual(T.completeWord(), true, 'a full home bank completes the target word');
assert.strictEqual(T.wordsDone, beforeDone+1, 'completed word advances the round counter');
assert.strictEqual(T.coinsRun, T.LETTER_REWARD, 'session coins wait like Frontline');
assert.strictEqual(awarded.n, coins0, 'the central wallet is not paid until settle');
assert.strictEqual(T.settleCoinSession(), T.LETTER_REWARD, 'settlement pays addCoins once');
assert.strictEqual(awarded.n, coins0+T.LETTER_REWARD, 'central coins receive the Frontline reward');
assert(T.settleScoreRun()>0,'lifetime score settles once');
assert.strictEqual(T.settleScoreRun(),0,'second settle does not double-count');

T.resetRun(); T.setRunning(true); T.setPaused(false);
const ang=T.shellLandingAngle(20,T.MUZZLE,T.G);
assert(ang>0 && ang<Math.PI/2, 'guns use a ballistic elevation angle');
T.player.yaw=0; T.player.turretRel=0; T.player.elev=T.ELEV;
const splash0=T.shellSplashPoint(T.muzzle());
assert(splash0.ok&&splash0.t>0,'aim plus sits on the ballistic water hit');
const grav=T.G*T.SHELL_MASS, mz=T.muzzle();
assert(Math.abs(mz.y+mz.fy*T.MUZZLE*splash0.t-0.5*grav*splash0.t*splash0.t)<.3,'predicted splash meets y=0');
const near0=Math.hypot(splash0.x-T.player.x, splash0.z-T.player.z);
T.player.elev=T.ELEV_MAX;
const splashHi=T.shellSplashPoint(T.muzzle());
assert(Math.hypot(splashHi.x-T.player.x, splashHi.z-T.player.z)>near0,'raising the barrels moves the plus farther');
assert(code.includes('function makeAimCross')&&!code.includes('RingGeometry(.55'),'aim mark is a thin plus, not the old ring');
T.player.elev=T.ELEV;
const m0=T.muzzle();
const guns=T.muzzles();
assert.strictEqual(T.BARREL_COUNT,4,'the ship has four gun barrels');
assert.strictEqual(guns.length,4,'all four barrels have a muzzle');
assert(guns.every(g=>Math.abs(g.fx-guns[0].fx)<1e-9&&Math.abs(g.fz-guns[0].fz)<1e-9),'every barrel points the same traverse');
const span=Math.hypot(guns[0].x-guns[2].x,guns[0].z-guns[2].z);
assert(span>T.TURRET_FWD+T.TURRET_AFT-1,'fore and aft muzzles sit on both turrets');
assert(!code.includes("beep('shot')"),'cannon fire no longer uses the oscillator shot beep');
const fired=T.fire(); assert(fired,'player can fire a shell');
const live=T.shells.filter(s=>s.alive);
assert.strictEqual(live.length,4,'one salvo leaves all four barrels');
const sh=live.find(s=>Math.hypot(s.x-m0.x,s.y-m0.y,s.z-m0.z)<.05);
assert(sh,'a shell leaves the first gun barrel');
assert(Math.abs(sh.vx-m0.fx*T.MUZZLE)<1e-6&&Math.abs(sh.vz-m0.fz*T.MUZZLE)<1e-6,'shell flies along the barrel');
T.player.turretRel=.45;
const aim=T.barrelDir(T.player.yaw, T.player.turretRel), mAim=T.muzzle();
assert(Math.abs(mAim.fx-aim.x)<1e-9&&Math.abs(mAim.fz-aim.z)<1e-9,'muzzle matches the pointed barrels');
assert(aim.y>0,'barrels elevate toward the ballistic arc');
const port=T.barrelDir(0,-Math.PI/2), fwd=T.barrelDir(0,0);
assert(port.x>0&&Math.abs(fwd.x)<1e-9&&fwd.z<0,'traverse follows the visible barrel yaw');
T.player.turretRel=0;
assert(Math.hypot(sh.vx,sh.vz)>Math.abs(T.player.z-T.FAR_Z)/2.5,'range reaches past the enemy water band');
const vx0=sh.vx, vz0=sh.vz, vy0=sh.vy;
T.tickShell(sh,.05);
assert.strictEqual(sh.vx,vx0,'horizontal aim stays a straight line');
assert.strictEqual(sh.vz,vz0,'horizontal aim stays a straight line on z');
assert(sh.vy<vy0,'gravity times shell mass pulls the round down');
assert(code.includes('function fireSplash')&&code.includes('rotation.x=-.42')&&code.includes('MAX_SPLASH'),'impacts spawn Arena-like upright flame cards');
assert(code.includes('SPLASH_SCALE=10')&&code.includes('*SPLASH_SCALE'),'impact flames are ten times larger');
assert(!code.includes('mat(0xffffff)'),'splash sparks are no longer white pellets');
assert(code.includes('function makeFireball')&&code.includes('getShellFireMat'),'shells use Arena-like combustion fireballs');
assert(code.includes('0xffc090')&&code.includes('AdditiveBlending')&&!code.includes('0xff3b10'),'fireball core is additive orange-white');
assert(code.includes('vec3(1.0,.94,.82)'),'flame heat blooms to orange-white');
assert(code.includes('setFromUnitVectors')&&code.includes('poseFireball'),'flame tails follow shell velocity');
assert(!code.includes('SphereGeometry(.18,8,8), mat(0xffe36b)'),'gold pellet shells are gone');
assert(T.shells.some(s=>s.alive),'shell is pooled rather than allocated unbounded');
for(let i=0;i<80;i++) T.fire();
assert(T.shells.length<=T.MAX_SHELLS,'shell pool is capped');
assert(code.includes('data-hold="left"')&&code.includes('เลี้ยวซ้าย'),'LEFT/RIGHT buttons are hull rudder');
assert.strictEqual(T.SPEED_NAMES.length,5,'player speed has five steps like a Frontline bar');
assert(code.includes('id="wsh-speed"')&&code.includes('max="4"'),'speed slider sits in the bottom center');
assert(css.includes('.wsh-speed'),'speed bar is styled in the empty bottom middle');
assert(css.includes('.wsh-word')&&css.includes('rgba(255,255,255,.30)'),'center word plate background is 30 percent opaque');
T.setHoldDrive(1); T.setSpeedLevel(0); T.step(.05);
const slow=Math.hypot(T.player.vx,T.player.vz);
T.setSpeedLevel(4); T.step(.05);
const fast=Math.hypot(T.player.vx,T.player.vz);
assert(fast>slow,'level 5 is faster than level 1');
T.setSpeedLevel(2); T.setHoldDrive(0);
assert(T.SEA_RIGHT-T.SEA_LEFT>=480,'playable water is much wider than the old pond');
assert(T.SEA_MESH>=800,'the visible sea plane covers the wider territory');
assert(T.SEA_BACK>=140,'the player can sail farther astern');
assert(!code.includes('Math.abs(o.x)>140'),'shells are not culled at the old 140 pond edge');
assert(!code.includes('0x9fe7ff')&&!code.includes('0x3eb4e8'),'sea and sky use a softer palette');
assert(!code.includes('เรือเป้าหมายแล่นหนีไปแล้ว'),'escaping ships do not toast a miss message');
assert(!code.includes('function makeWake')&&!code.includes('0xf4fbff'),'no white foam wake around the hull');
assert(T.ICE_SHOW>=24&&T.ICE_HIDE>T.ICE_SHOW,'ice cliffs appear only near the playable rim');
T.resetRun();
assert(!T.iceWanted().far&&!T.iceWanted().back&&!T.iceWanted().left&&!T.iceWanted().right,'spawn is not on the map rim');
const plim=T.playerLimits();
T.setPlayer(0, plim.minZ+6);
assert(T.iceWanted().far&&!T.iceWanted().left,'far ice is wanted only at the forward rim');
T.setPlayer(plim.minX+5, 18);
assert(T.iceWanted().left&&!T.iceWanted().far,'left ice is wanted only at the port rim');
T.resetRun();
assert(!T.iceWalls.far&&!T.iceWalls.left,'ice meshes stay unloaded until a live scene is close');
assert(code.includes('function makeIceCliff')&&code.includes('tickIce()'),'ice cliffs are built lazily when the hull nears an edge');
assert(!code.slice(code.indexOf('function buildWorld'), code.indexOf('function tickPlayer')).includes('makeIceCliff('),'the world build does not spawn ice walls up front');
assert.strictEqual(T.STUCK_MSG,'เรือติดสิ่งกีดขวาง ให้กดถอยหลัง','stuck copy tells the player to reverse');
T.resetRun();
T.setPlayer(0, T.playerLimits().minZ);
T.player.yaw=0; T.setHoldDrive(1); T.step(.05);
assert(T.player.blocked,'driving bow-first into the rim is blocked');
assert(T.warnStuck(true),'the stuck toast arms while still pushing forward');
T.setHoldDrive(-1); T.step(.08);
assert(!T.player.blocked,'reverse clears the rim block');

console.log('wordship ok');
