'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),vm=require('vm'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),root=path.resolve(process.env.VW_ARENA_SOURCE||repo),out=process.env.VW_ARENA_OUTPUT||path.join(repo,'work/arena-crystals');fs.mkdirSync(out,{recursive:true});
const deps=path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'),{chromium}=require(path.join(deps,'playwright')),sharp=require(path.join(deps,'sharp')),THREE=require(path.join(repo,'js/vendor/three.min.js'));
const checks=[],ok=(n,v)=>{assert.ok(v,n);checks.push(n);};const scope={window:{},performance};vm.runInNewContext(fs.readFileSync(path.join(root,'js/arena-elements.js'),'utf8'),scope);const E=scope.window.ArenaElements;
for(const kind of ['fire','wind','ice','meteor','earth','gravity','water','light']){const near={group:{position:new THREE.Vector3(10,0,0)},hp:1000},far={group:{position:new THREE.Vector3(25,0,0)},hp:1000};let heal=0,visualRadius=0;const e=E.create({enemies:()=>[near,far],hit:(b,n)=>b.hp-=n,heal:n=>heal+=n,fx:{mega:(p,k,r)=>visualRadius=r,ring(){},burst(){}},storm:()=>false});ok(kind+' mega cast',e.castMega(kind,new THREE.Vector3(),new THREE.Vector3(0,0,1),1));ok(kind+' visual radius equals damage radius 18',visualRadius===18&&e.stats().mega[0].radius===18);for(let i=0;i<30;i++)e.tick(.1);ok(kind+' three real pulses inside and no damage outside',near.hp===880&&far.hp===1000&&e.stats().active===0);if(kind==='light')ok('light mega heals',heal===30);if(kind==='ice')ok('ice mega slows',near.slow>performance.now());}
const harness=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/css/arena3d.css"></head><body><script>window.state={profileName:'admin',coins:1000,arenaHomeIntro:true,arenaItems:{},arenaHero:'fire',sound:false};window.isAdmin=()=>true;window.saveState=()=>{};window.addCoins=n=>state.coins+=n;window.vocabForStudent=()=>[['cat','แมว']];window.activePet=()=>null;window.toast=()=>{};</script><script src="/js/vendor/three.min.js"></script><script src="/js/arena-field-visuals.js"></script><script src="/js/arena-elements.js"></script><script src="/js/arena-heroes.js"></script><script src="/js/arena3d.js"></script></body></html>`;
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/test'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(harness);}const f=path.resolve(root,'.'+u.pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:812,height:375}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
await page.goto(`http://127.0.0.1:${server.address().port}/test`);await page.evaluate(()=>{VocabArena3D.start();const t=VocabArena3D._t;t.player().pos.set(0,0,0);t.bots.forEach(b=>{b.attackAt=performance.now()+60000;b.hp=b.maxHp=10000;});});
ok('six decorative pedestals now carry collectable A-Z crystals',await page.evaluate(()=>{const t=VocabArena3D._t;return t.crystalNodes.length===6&&t.crystalNodes.every(n=>n.drop&&/^[A-Z]$/.test(n.drop.ch));}));
await page.evaluate(()=>{const t=VocabArena3D._t;t.player().pos.copy(t.crystalNodes[0].pos);t.tickDrops(.01,performance.now());t.player().pos.set(0,0,0);});ok('walking onto pedestal collects one letter and one charge',await page.evaluate(()=>{const t=VocabArena3D._t;return t.cargo.length===1&&t.crystalCharge===1&&!t.crystalNodes[0].drop;}));
await page.evaluate(()=>{const t=VocabArena3D._t;for(let i=1;i<4;i++)t.collect(t.drops.indexOf(t.crystalNodes[i].drop));t.cast('ult');});ok('four crystals cannot cast mega',await page.evaluate(()=>VocabArena3D._t.crystalCharge===4&&VocabArena3D._t.cooldowns.ult===0&&VocabArena3D._t.elementStats().mega.length===0));
await page.evaluate(()=>{const t=VocabArena3D._t;t.collect(t.drops.indexOf(t.crystalNodes[4].drop));});ok('fifth pickup grants five uses with visible remaining counter',await page.evaluate(()=>document.querySelector('[data-skill="ult"]').classList.contains('ready')&&document.querySelector('#va-crystal-count').textContent.includes('5 ครั้ง')&&VocabArena3D._t.megaUses===5));
const cargo=await page.evaluate(()=>VocabArena3D._t.cargo.join(''));await page.keyboard.press('Digit3');ok('one mega consumes one of five uses and preserves letters',await page.evaluate(c=>{const t=VocabArena3D._t;return t.megaUses===4&&t.crystalCharge===5&&t.cargo.join('')===c&&t.elementStats().mega[0].radius===18;},cargo));await page.keyboard.press('Digit3');await page.waitForFunction(()=>document.querySelector('[data-skill="ult"] .cd').textContent.includes('วิ'));ok('remaining uses badge is distinct from cooldown seconds',await page.evaluate(()=>document.querySelector('#va-mega-uses').textContent==='เหลือ 4'&&document.querySelector('[data-skill="ult"] .cd').textContent.includes('วิ')));ok('repeated input cannot cast twice',await page.evaluate(()=>VocabArena3D._t.elementStats().mega.length===1));
await page.evaluate(()=>{const t=VocabArena3D._t;t.collect(t.drops.indexOf(t.crystalNodes[5].drop));t.drop(new THREE.Vector3(0,0,8),'Z',0xffc678);t.collect(t.drops.length-1);});ok('full cargo preserves crystal and does not charge',await page.evaluate(()=>{const t=VocabArena3D._t;return t.cargo.length===6&&t.crystalCharge===5&&t.megaUses===4&&t.drops.some(d=>d.ch==='Z'&&!d.node);}));
await page.evaluate(()=>{const t=VocabArena3D._t;t.tickDrops(18.1,performance.now());});ok('collected pedestals respawn after eighteen gameplay seconds',await page.evaluate(()=>VocabArena3D._t.crystalNodes.every(n=>n.drop)));
const sequence=await page.evaluate(()=>{const t=VocabArena3D._t,original=performance.now.bind(performance),base=original(),left=[];try{for(let i=1;i<=4;i++){performance.now=()=>base+i*16000;t.cast('ult');left.push(t.megaUses);}performance.now=()=>base+100000;t.cast('ult');}finally{performance.now=original;}return left;});ok('remaining uses count 3,2,1,0 and sixth cast stays locked',sequence.join(',')==='3,2,1,0'&&await page.evaluate(()=>VocabArena3D._t.megaUses===0&&VocabArena3D._t.crystalCharge===0));
await page.evaluate(()=>{const t=VocabArena3D._t;t.player().pos.copy(t.home().position);t.bank();t.player().pos.set(0,0,0);for(let i=0;i<5;i++)t.collect(t.drops.indexOf(t.crystalNodes[i].drop));});ok('next five crystals refill exactly five uses after exhaustion',await page.evaluate(()=>VocabArena3D._t.megaUses===5));
const beforeDown=await page.evaluate(()=>VocabArena3D._t.cargo.length);await page.evaluate(()=>{const t=VocabArena3D._t;t.down();t.recover();for(const d of t.drops.slice())if(!d.chargeable)t.collect(t.drops.indexOf(d));});ok('recovering dropped cargo cannot farm mega charge',await page.evaluate(n=>VocabArena3D._t.crystalCharge===0&&VocabArena3D._t.megaUses===0&&VocabArena3D._t.cargo.length===n,beforeDown));
await page.evaluate(()=>{const t=VocabArena3D._t;t.player().pos.copy(t.home().position);t.bank();});ok('crystal letters still bank at home',await page.evaluate(()=>VocabArena3D._t.cargo.length===0&&Object.keys(VocabArena3D._t.bag).length>0));
const costs={};for(const kind of ['fire','wind','ice','meteor','earth','gravity','water','light']){
 await page.evaluate(kind=>{VocabArena3D.stop();state.arenaHome={letters:{},cargo:[]};state.arenaHero=kind;VocabArena3D.start();const t=VocabArena3D._t;t.player().pos.set(0,0,0);t.bots.forEach((b,i)=>{b.group.position.set((i%3-1)*5,0,-6-Math.floor(i/3)*3);b.hp=b.maxHp=10000;b.attackAt=performance.now()+60000;});for(let i=0;i<5;i++)t.collect(t.drops.indexOf(t.crystalNodes[i].drop));},kind);await page.waitForTimeout(300);await page.keyboard.press('Digit3');await page.waitForTimeout(650);costs[kind]=await page.evaluate(()=>VocabArena3D._t.stats());ok(kind+' mega from actual hero button stays in pool budget',costs[kind].fx.active<=640&&costs[kind].fx.meshes===48);await sharp(await page.screenshot()).webp({quality:92}).toFile(path.join(out,'mega-'+kind+'.webp'));
}
for(const [w,h]of [[667,320],[812,375],[1366,768]]){await page.setViewportSize({width:w,height:h});ok('counter and mega label fit '+w,await page.evaluate(()=>['#va-crystal-count','#va-mega-uses','[data-skill="ult"] .key'].every(s=>{const e=document.querySelector(s),r=e.getBoundingClientRect();return e.scrollWidth<=e.clientWidth+1&&r.left>=0&&r.right<=innerWidth;})));}
await page.evaluate(()=>{VocabArena3D.stop();state.noAnim=true;state.arenaHome={letters:{},cargo:[]};VocabArena3D.start();const t=VocabArena3D._t;t.player().pos.set(0,0,0);for(let i=0;i<5;i++)t.collect(t.drops.indexOf(t.crystalNodes[i].drop));t.cast('ult');});ok('low-power mega retains 28 mesh pool',await page.evaluate(()=>VocabArena3D._t.stats().fx.meshes===28));await page.evaluate(()=>{VocabArena3D.stop();VocabArena3D.start();});ok('reentry clears mega and respawn state',await page.evaluate(()=>{const t=VocabArena3D._t;return t.crystalCharge===0&&t.megaUses===0&&t.elementStats().mega.length===0&&t.crystalNodes.length===6;}));await page.evaluate(()=>VocabArena3D.stop());ok('zero browser errors',errors.length===0);
fs.writeFileSync(path.join(out,'crystal-report.json'),JSON.stringify({checks,costs,errors},null,2));console.log(JSON.stringify({passed:checks.length,costs,errors,out}));
}catch(e){console.error(e);console.error(errors);await sharp(await page.screenshot()).webp({quality:92}).toFile(path.join(out,'failure.webp'));process.exitCode=1;}finally{await browser.close();server.close();}})();
